-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mine_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    block_words_read : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_read_10 : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_read_11 : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_read_12 : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_read_13 : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_read_14 : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_read_15 : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_read_16 : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_read_17 : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_read_18 : IN STD_LOGIC_VECTOR (9 downto 0);
    w_80_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_80_out_ap_vld : OUT STD_LOGIC;
    w_79_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_79_out_ap_vld : OUT STD_LOGIC;
    w_78_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_78_out_ap_vld : OUT STD_LOGIC;
    w_77_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_77_out_ap_vld : OUT STD_LOGIC;
    w_76_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_76_out_ap_vld : OUT STD_LOGIC;
    w_75_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_75_out_ap_vld : OUT STD_LOGIC;
    w_74_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_74_out_ap_vld : OUT STD_LOGIC;
    w_73_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_73_out_ap_vld : OUT STD_LOGIC;
    w_72_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_72_out_ap_vld : OUT STD_LOGIC;
    w_71_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_71_out_ap_vld : OUT STD_LOGIC;
    w_70_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_70_out_ap_vld : OUT STD_LOGIC;
    w_69_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_69_out_ap_vld : OUT STD_LOGIC;
    w_68_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_68_out_ap_vld : OUT STD_LOGIC;
    w_67_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_67_out_ap_vld : OUT STD_LOGIC;
    w_66_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_66_out_ap_vld : OUT STD_LOGIC;
    w_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of mine_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln118_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal i_fu_118 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln118_fu_376_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_2 : STD_LOGIC_VECTOR (4 downto 0);
    signal w_fu_122 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_32_fu_386_p35 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln118_fu_382_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal w_17_fu_126 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_18_fu_130 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_19_fu_134 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_20_fu_138 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_21_fu_142 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_22_fu_146 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_23_fu_150 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_24_fu_154 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_25_fu_158 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_26_fu_162 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_27_fu_166 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_28_fu_170 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_29_fu_174 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_30_fu_178 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_31_fu_182 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_32_fu_386_p32 : STD_LOGIC_VECTOR (31 downto 0);
    signal w_32_fu_386_p33 : STD_LOGIC_VECTOR (31 downto 0);
    signal w_32_fu_386_p34 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal w_32_fu_386_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal w_32_fu_386_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal w_32_fu_386_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal w_32_fu_386_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal w_32_fu_386_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal w_32_fu_386_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal w_32_fu_386_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal w_32_fu_386_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal w_32_fu_386_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal w_32_fu_386_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal w_32_fu_386_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal w_32_fu_386_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal w_32_fu_386_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal w_32_fu_386_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal w_32_fu_386_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal w_32_fu_386_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component mine_sparsemux_33_4_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (3 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (3 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (3 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (3 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (3 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (3 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (3 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (3 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (3 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (3 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (3 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (3 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (3 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (3 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (3 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (3 downto 0);
        din15_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (31 downto 0);
        din9 : IN STD_LOGIC_VECTOR (31 downto 0);
        din10 : IN STD_LOGIC_VECTOR (31 downto 0);
        din11 : IN STD_LOGIC_VECTOR (31 downto 0);
        din12 : IN STD_LOGIC_VECTOR (31 downto 0);
        din13 : IN STD_LOGIC_VECTOR (31 downto 0);
        din14 : IN STD_LOGIC_VECTOR (31 downto 0);
        din15 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component mine_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_33_4_32_1_1_U105 : component mine_sparsemux_33_4_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 32,
        CASE1 => "0001",
        din1_WIDTH => 32,
        CASE2 => "0010",
        din2_WIDTH => 32,
        CASE3 => "0011",
        din3_WIDTH => 32,
        CASE4 => "0100",
        din4_WIDTH => 32,
        CASE5 => "0101",
        din5_WIDTH => 32,
        CASE6 => "0110",
        din6_WIDTH => 32,
        CASE7 => "0111",
        din7_WIDTH => 32,
        CASE8 => "1000",
        din8_WIDTH => 32,
        CASE9 => "1001",
        din9_WIDTH => 32,
        CASE10 => "1010",
        din10_WIDTH => 32,
        CASE11 => "1011",
        din11_WIDTH => 32,
        CASE12 => "1100",
        din12_WIDTH => 32,
        CASE13 => "1101",
        din13_WIDTH => 32,
        CASE14 => "1110",
        din14_WIDTH => 32,
        CASE15 => "1111",
        din15_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 4,
        dout_WIDTH => 32)
    port map (
        din0 => block_words_read,
        din1 => block_words_read_10,
        din2 => block_words_read_11,
        din3 => block_words_read_12,
        din4 => block_words_read_13,
        din5 => block_words_read_14,
        din6 => block_words_read_15,
        din7 => block_words_read_16,
        din8 => block_words_read_17,
        din9 => ap_const_lv32_0,
        din10 => ap_const_lv32_0,
        din11 => ap_const_lv32_0,
        din12 => ap_const_lv32_0,
        din13 => ap_const_lv32_0,
        din14 => ap_const_lv32_0,
        din15 => w_32_fu_386_p32,
        def => w_32_fu_386_p33,
        sel => w_32_fu_386_p34,
        dout => w_32_fu_386_p35);

    flow_control_loop_pipe_sequential_init_U : component mine_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln118_fu_370_p2 = ap_const_lv1_0)) then 
                    i_fu_118 <= add_ln118_fu_376_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_118 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln118_fu_382_p1 = ap_const_lv4_1) and (icmp_ln118_fu_370_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_17_fu_126 <= w_32_fu_386_p35;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln118_fu_382_p1 = ap_const_lv4_2) and (icmp_ln118_fu_370_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_18_fu_130 <= w_32_fu_386_p35;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln118_fu_382_p1 = ap_const_lv4_3) and (icmp_ln118_fu_370_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_19_fu_134 <= w_32_fu_386_p35;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln118_fu_382_p1 = ap_const_lv4_4) and (icmp_ln118_fu_370_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_20_fu_138 <= w_32_fu_386_p35;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln118_fu_382_p1 = ap_const_lv4_5) and (icmp_ln118_fu_370_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_21_fu_142 <= w_32_fu_386_p35;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln118_fu_382_p1 = ap_const_lv4_6) and (icmp_ln118_fu_370_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_22_fu_146 <= w_32_fu_386_p35;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln118_fu_382_p1 = ap_const_lv4_7) and (icmp_ln118_fu_370_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_23_fu_150 <= w_32_fu_386_p35;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln118_fu_382_p1 = ap_const_lv4_8) and (icmp_ln118_fu_370_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_24_fu_154 <= w_32_fu_386_p35;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln118_fu_382_p1 = ap_const_lv4_9) and (icmp_ln118_fu_370_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_25_fu_158 <= w_32_fu_386_p35;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln118_fu_382_p1 = ap_const_lv4_A) and (icmp_ln118_fu_370_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_26_fu_162 <= w_32_fu_386_p35;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln118_fu_382_p1 = ap_const_lv4_B) and (icmp_ln118_fu_370_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_27_fu_166 <= w_32_fu_386_p35;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln118_fu_382_p1 = ap_const_lv4_C) and (icmp_ln118_fu_370_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_28_fu_170 <= w_32_fu_386_p35;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln118_fu_382_p1 = ap_const_lv4_D) and (icmp_ln118_fu_370_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_29_fu_174 <= w_32_fu_386_p35;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln118_fu_382_p1 = ap_const_lv4_E) and (icmp_ln118_fu_370_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_30_fu_178 <= w_32_fu_386_p35;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln118_fu_382_p1 = ap_const_lv4_F) and (icmp_ln118_fu_370_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_31_fu_182 <= w_32_fu_386_p35;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln118_fu_382_p1 = ap_const_lv4_0) and (icmp_ln118_fu_370_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_fu_122 <= w_32_fu_386_p35;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln118_fu_376_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_2) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln118_fu_370_p2)
    begin
        if (((icmp_ln118_fu_370_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_2_assign_proc : process(ap_CS_fsm_state1, i_fu_118, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_i_2 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_i_2 <= i_fu_118;
        end if; 
    end process;

    icmp_ln118_fu_370_p2 <= "1" when (ap_sig_allocacmp_i_2 = ap_const_lv5_10) else "0";
    trunc_ln118_fu_382_p1 <= ap_sig_allocacmp_i_2(4 - 1 downto 0);
    w_32_fu_386_p32 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(block_words_read_18),32));
    w_32_fu_386_p33 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    w_32_fu_386_p34 <= ap_sig_allocacmp_i_2(4 - 1 downto 0);
    w_66_out <= w_17_fu_126;

    w_66_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln118_fu_370_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_370_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_66_out_ap_vld <= ap_const_logic_1;
        else 
            w_66_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_67_out <= w_18_fu_130;

    w_67_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln118_fu_370_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_370_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_67_out_ap_vld <= ap_const_logic_1;
        else 
            w_67_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_68_out <= w_19_fu_134;

    w_68_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln118_fu_370_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_370_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_68_out_ap_vld <= ap_const_logic_1;
        else 
            w_68_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_69_out <= w_20_fu_138;

    w_69_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln118_fu_370_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_370_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_69_out_ap_vld <= ap_const_logic_1;
        else 
            w_69_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_70_out <= w_21_fu_142;

    w_70_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln118_fu_370_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_370_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_70_out_ap_vld <= ap_const_logic_1;
        else 
            w_70_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_71_out <= w_22_fu_146;

    w_71_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln118_fu_370_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_370_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_71_out_ap_vld <= ap_const_logic_1;
        else 
            w_71_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_72_out <= w_23_fu_150;

    w_72_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln118_fu_370_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_370_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_72_out_ap_vld <= ap_const_logic_1;
        else 
            w_72_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_73_out <= w_24_fu_154;

    w_73_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln118_fu_370_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_370_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_73_out_ap_vld <= ap_const_logic_1;
        else 
            w_73_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_74_out <= w_25_fu_158;

    w_74_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln118_fu_370_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_370_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_74_out_ap_vld <= ap_const_logic_1;
        else 
            w_74_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_75_out <= w_26_fu_162;

    w_75_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln118_fu_370_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_370_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_75_out_ap_vld <= ap_const_logic_1;
        else 
            w_75_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_76_out <= w_27_fu_166;

    w_76_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln118_fu_370_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_370_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_76_out_ap_vld <= ap_const_logic_1;
        else 
            w_76_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_77_out <= w_28_fu_170;

    w_77_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln118_fu_370_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_370_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_77_out_ap_vld <= ap_const_logic_1;
        else 
            w_77_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_78_out <= w_29_fu_174;

    w_78_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln118_fu_370_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_370_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_78_out_ap_vld <= ap_const_logic_1;
        else 
            w_78_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_79_out <= w_30_fu_178;

    w_79_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln118_fu_370_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_370_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_79_out_ap_vld <= ap_const_logic_1;
        else 
            w_79_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_80_out <= w_31_fu_182;

    w_80_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln118_fu_370_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_370_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_80_out_ap_vld <= ap_const_logic_1;
        else 
            w_80_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_out <= w_fu_122;

    w_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln118_fu_370_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_370_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_out_ap_vld <= ap_const_logic_1;
        else 
            w_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

end behav;
