-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mine_sha256_compress_words_1_Pipeline_SHA256_ROUNDS is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    w_15_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_14_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_13_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_12_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_11_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_10_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_9_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_8_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_7_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_6_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_5_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_4_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_2_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_1_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    a_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    a_2_out_ap_vld : OUT STD_LOGIC;
    b_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    b_out_ap_vld : OUT STD_LOGIC;
    c_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    c_out_ap_vld : OUT STD_LOGIC;
    d_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    d_out_ap_vld : OUT STD_LOGIC;
    e_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    e_2_out_ap_vld : OUT STD_LOGIC;
    f_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    f_out_ap_vld : OUT STD_LOGIC;
    g_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    g_out_ap_vld : OUT STD_LOGIC;
    h_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    h_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of mine_sha256_compress_words_1_Pipeline_SHA256_ROUNDS is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv32_5BE0CD19 : STD_LOGIC_VECTOR (31 downto 0) := "01011011111000001100110100011001";
    constant ap_const_lv32_A54FF53A : STD_LOGIC_VECTOR (31 downto 0) := "10100101010011111111010100111010";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_1F83D9AB : STD_LOGIC_VECTOR (31 downto 0) := "00011111100000111101100110101011";
    constant ap_const_lv32_9B05688C : STD_LOGIC_VECTOR (31 downto 0) := "10011011000001010110100010001100";
    constant ap_const_lv32_510E527F : STD_LOGIC_VECTOR (31 downto 0) := "01010001000011100101001001111111";
    constant ap_const_lv32_3C6EF372 : STD_LOGIC_VECTOR (31 downto 0) := "00111100011011101111001101110010";
    constant ap_const_lv32_BB67AE85 : STD_LOGIC_VECTOR (31 downto 0) := "10111011011001111010111010000101";
    constant ap_const_lv32_6A09E667 : STD_LOGIC_VECTOR (31 downto 0) := "01101010000010011110011001100111";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln133_fu_695_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal K_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal K_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln133_reg_1791 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln133_fu_712_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln138_fu_727_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal wt_5_fu_1165_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_512_p35 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_wt_2_reg_473 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_wt_2_reg_473 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter2_wt_2_reg_473 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln133_fu_707_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal h_fu_208 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal d_fu_212 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal i_1_fu_216 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln133_fu_701_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal w_fu_220 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_33_fu_224 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_34_fu_228 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_35_fu_232 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_36_fu_236 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_37_fu_240 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_38_fu_244 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_39_fu_248 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_40_fu_252 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_41_fu_256 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_42_fu_260 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_43_fu_264 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_44_fu_268 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_45_fu_272 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_46_fu_276 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_47_fu_280 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal h_3_fu_284 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal g_fu_288 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal f_fu_292 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal e_fu_1488_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal d_3_fu_296 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal c_fu_300 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal b_fu_304 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal a_fu_1560_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal K_ce0_local : STD_LOGIC;
    signal grp_fu_512_p33 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_717_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal x15_fu_797_p33 : STD_LOGIC_VECTOR (31 downto 0);
    signal x2_fu_869_p33 : STD_LOGIC_VECTOR (31 downto 0);
    signal x15_fu_797_p35 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln1_fu_969_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal x2_fu_869_p35 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln2_fu_1011_p4 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_s_fu_1025_p33 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln33_10_fu_965_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal lshr_ln33_1_fu_955_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln33_fu_951_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal lshr_ln_fu_941_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal trunc_ln33_12_fu_1007_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal lshr_ln33_3_fu_997_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal or_ln159_1_fu_1105_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln149_fu_979_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln159_fu_1121_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln_fu_1097_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln33_11_fu_993_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal lshr_ln33_2_fu_983_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln154_fu_1021_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln159_3_fu_1133_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln159_2_fu_1141_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln159_2_fu_1113_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_1025_p35 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln159_3_fu_1147_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln159_1_fu_1127_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln159_fu_1159_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln159_1_fu_1153_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln173_fu_1362_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln33_13_fu_1330_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal lshr_ln33_4_fu_1320_p4 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln33_14_fu_1344_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal lshr_ln33_5_fu_1334_p4 : STD_LOGIC_VECTOR (20 downto 0);
    signal and_ln173_fu_1368_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln173_1_fu_1374_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln33_15_fu_1358_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal lshr_ln33_6_fu_1348_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln173_1_fu_1388_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln173_2_fu_1402_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln173_2_fu_1410_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln1_fu_1380_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln173_3_fu_1416_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln173_1_fu_1396_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln173_1_fu_1428_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln173_2_fu_1434_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln173_fu_1422_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal t1_fu_1440_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln195_fu_1494_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln33_16_fu_1456_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal lshr_ln33_7_fu_1446_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal trunc_ln33_17_fu_1470_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal lshr_ln33_8_fu_1460_p4 : STD_LOGIC_VECTOR (18 downto 0);
    signal and_ln195_fu_1500_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln195_1_fu_1506_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln33_18_fu_1484_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal lshr_ln33_9_fu_1474_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln195_1_fu_1520_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln195_2_fu_1534_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln195_2_fu_1542_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln2_fu_1512_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln195_3_fu_1548_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln195_fu_1554_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln195_1_fu_1528_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_819 : BOOLEAN;
    signal ap_condition_822 : BOOLEAN;
    signal ap_condition_825 : BOOLEAN;
    signal ap_condition_828 : BOOLEAN;
    signal ap_condition_831 : BOOLEAN;
    signal ap_condition_834 : BOOLEAN;
    signal ap_condition_837 : BOOLEAN;
    signal ap_condition_840 : BOOLEAN;
    signal ap_condition_843 : BOOLEAN;
    signal ap_condition_846 : BOOLEAN;
    signal ap_condition_849 : BOOLEAN;
    signal ap_condition_852 : BOOLEAN;
    signal ap_condition_855 : BOOLEAN;
    signal ap_condition_858 : BOOLEAN;
    signal ap_condition_861 : BOOLEAN;
    signal ap_condition_864 : BOOLEAN;
    signal grp_fu_512_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_512_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_512_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_512_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_512_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_512_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_512_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_512_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_512_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_512_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_512_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_512_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_512_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_512_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_512_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_512_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal x15_fu_797_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal x15_fu_797_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal x15_fu_797_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal x15_fu_797_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal x15_fu_797_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal x15_fu_797_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal x15_fu_797_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal x15_fu_797_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal x15_fu_797_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal x15_fu_797_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal x15_fu_797_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal x15_fu_797_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal x15_fu_797_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal x15_fu_797_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal x15_fu_797_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal x15_fu_797_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal x2_fu_869_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal x2_fu_869_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal x2_fu_869_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal x2_fu_869_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal x2_fu_869_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal x2_fu_869_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal x2_fu_869_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal x2_fu_869_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal x2_fu_869_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal x2_fu_869_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal x2_fu_869_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal x2_fu_869_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal x2_fu_869_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal x2_fu_869_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal x2_fu_869_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal x2_fu_869_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_1025_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_1025_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_1025_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_1025_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_1025_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_1025_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_1025_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_1025_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_1025_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_1025_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_1025_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_1025_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_1025_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_1025_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_1025_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_1025_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component mine_sparsemux_33_4_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (3 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (3 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (3 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (3 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (3 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (3 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (3 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (3 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (3 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (3 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (3 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (3 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (3 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (3 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (3 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (3 downto 0);
        din15_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (31 downto 0);
        din9 : IN STD_LOGIC_VECTOR (31 downto 0);
        din10 : IN STD_LOGIC_VECTOR (31 downto 0);
        din11 : IN STD_LOGIC_VECTOR (31 downto 0);
        din12 : IN STD_LOGIC_VECTOR (31 downto 0);
        din13 : IN STD_LOGIC_VECTOR (31 downto 0);
        din14 : IN STD_LOGIC_VECTOR (31 downto 0);
        din15 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component mine_sparsemux_33_4_32_1_1_x IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (3 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (3 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (3 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (3 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (3 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (3 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (3 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (3 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (3 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (3 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (3 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (3 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (3 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (3 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (3 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (3 downto 0);
        din15_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (31 downto 0);
        din9 : IN STD_LOGIC_VECTOR (31 downto 0);
        din10 : IN STD_LOGIC_VECTOR (31 downto 0);
        din11 : IN STD_LOGIC_VECTOR (31 downto 0);
        din12 : IN STD_LOGIC_VECTOR (31 downto 0);
        din13 : IN STD_LOGIC_VECTOR (31 downto 0);
        din14 : IN STD_LOGIC_VECTOR (31 downto 0);
        din15 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component mine_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_K_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component mine_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    K_U : component mine_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_K_ROM_AUTO_1R
    generic map (
        DataWidth => 32,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => K_address0,
        ce0 => K_ce0_local,
        q0 => K_q0);

    sparsemux_33_4_32_1_1_U57 : component mine_sparsemux_33_4_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 32,
        CASE1 => "0001",
        din1_WIDTH => 32,
        CASE2 => "0010",
        din2_WIDTH => 32,
        CASE3 => "0011",
        din3_WIDTH => 32,
        CASE4 => "0100",
        din4_WIDTH => 32,
        CASE5 => "0101",
        din5_WIDTH => 32,
        CASE6 => "0110",
        din6_WIDTH => 32,
        CASE7 => "0111",
        din7_WIDTH => 32,
        CASE8 => "1000",
        din8_WIDTH => 32,
        CASE9 => "1001",
        din9_WIDTH => 32,
        CASE10 => "1010",
        din10_WIDTH => 32,
        CASE11 => "1011",
        din11_WIDTH => 32,
        CASE12 => "1100",
        din12_WIDTH => 32,
        CASE13 => "1101",
        din13_WIDTH => 32,
        CASE14 => "1110",
        din14_WIDTH => 32,
        CASE15 => "1111",
        din15_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 4,
        dout_WIDTH => 32)
    port map (
        din0 => w_fu_220,
        din1 => w_33_fu_224,
        din2 => w_34_fu_228,
        din3 => w_35_fu_232,
        din4 => w_36_fu_236,
        din5 => w_37_fu_240,
        din6 => w_38_fu_244,
        din7 => w_39_fu_248,
        din8 => w_40_fu_252,
        din9 => w_41_fu_256,
        din10 => w_42_fu_260,
        din11 => w_43_fu_264,
        din12 => w_44_fu_268,
        din13 => w_45_fu_272,
        din14 => w_46_fu_276,
        din15 => w_47_fu_280,
        def => grp_fu_512_p33,
        sel => trunc_ln133_fu_712_p1,
        dout => grp_fu_512_p35);

    sparsemux_33_4_32_1_1_x_U58 : component mine_sparsemux_33_4_32_1_1_x
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "1111",
        din0_WIDTH => 32,
        CASE1 => "0000",
        din1_WIDTH => 32,
        CASE2 => "0001",
        din2_WIDTH => 32,
        CASE3 => "0010",
        din3_WIDTH => 32,
        CASE4 => "0011",
        din4_WIDTH => 32,
        CASE5 => "0100",
        din5_WIDTH => 32,
        CASE6 => "0101",
        din6_WIDTH => 32,
        CASE7 => "0110",
        din7_WIDTH => 32,
        CASE8 => "0111",
        din8_WIDTH => 32,
        CASE9 => "1000",
        din9_WIDTH => 32,
        CASE10 => "1001",
        din10_WIDTH => 32,
        CASE11 => "1010",
        din11_WIDTH => 32,
        CASE12 => "1011",
        din12_WIDTH => 32,
        CASE13 => "1100",
        din13_WIDTH => 32,
        CASE14 => "1101",
        din14_WIDTH => 32,
        CASE15 => "1110",
        din15_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 4,
        dout_WIDTH => 32)
    port map (
        din0 => w_fu_220,
        din1 => w_33_fu_224,
        din2 => w_34_fu_228,
        din3 => w_35_fu_232,
        din4 => w_36_fu_236,
        din5 => w_37_fu_240,
        din6 => w_38_fu_244,
        din7 => w_39_fu_248,
        din8 => w_40_fu_252,
        din9 => w_41_fu_256,
        din10 => w_42_fu_260,
        din11 => w_43_fu_264,
        din12 => w_44_fu_268,
        din13 => w_45_fu_272,
        din14 => w_46_fu_276,
        din15 => w_47_fu_280,
        def => x15_fu_797_p33,
        sel => trunc_ln133_fu_712_p1,
        dout => x15_fu_797_p35);

    sparsemux_33_4_32_1_1_x_U59 : component mine_sparsemux_33_4_32_1_1_x
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0010",
        din0_WIDTH => 32,
        CASE1 => "0011",
        din1_WIDTH => 32,
        CASE2 => "0100",
        din2_WIDTH => 32,
        CASE3 => "0101",
        din3_WIDTH => 32,
        CASE4 => "0110",
        din4_WIDTH => 32,
        CASE5 => "0111",
        din5_WIDTH => 32,
        CASE6 => "1000",
        din6_WIDTH => 32,
        CASE7 => "1001",
        din7_WIDTH => 32,
        CASE8 => "1010",
        din8_WIDTH => 32,
        CASE9 => "1011",
        din9_WIDTH => 32,
        CASE10 => "1100",
        din10_WIDTH => 32,
        CASE11 => "1101",
        din11_WIDTH => 32,
        CASE12 => "1110",
        din12_WIDTH => 32,
        CASE13 => "1111",
        din13_WIDTH => 32,
        CASE14 => "0000",
        din14_WIDTH => 32,
        CASE15 => "0001",
        din15_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 4,
        dout_WIDTH => 32)
    port map (
        din0 => w_fu_220,
        din1 => w_33_fu_224,
        din2 => w_34_fu_228,
        din3 => w_35_fu_232,
        din4 => w_36_fu_236,
        din5 => w_37_fu_240,
        din6 => w_38_fu_244,
        din7 => w_39_fu_248,
        din8 => w_40_fu_252,
        din9 => w_41_fu_256,
        din10 => w_42_fu_260,
        din11 => w_43_fu_264,
        din12 => w_44_fu_268,
        din13 => w_45_fu_272,
        din14 => w_46_fu_276,
        din15 => w_47_fu_280,
        def => x2_fu_869_p33,
        sel => trunc_ln133_fu_712_p1,
        dout => x2_fu_869_p35);

    sparsemux_33_4_32_1_1_x_U60 : component mine_sparsemux_33_4_32_1_1_x
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0111",
        din0_WIDTH => 32,
        CASE1 => "1000",
        din1_WIDTH => 32,
        CASE2 => "1001",
        din2_WIDTH => 32,
        CASE3 => "1010",
        din3_WIDTH => 32,
        CASE4 => "1011",
        din4_WIDTH => 32,
        CASE5 => "1100",
        din5_WIDTH => 32,
        CASE6 => "1101",
        din6_WIDTH => 32,
        CASE7 => "1110",
        din7_WIDTH => 32,
        CASE8 => "1111",
        din8_WIDTH => 32,
        CASE9 => "0000",
        din9_WIDTH => 32,
        CASE10 => "0001",
        din10_WIDTH => 32,
        CASE11 => "0010",
        din11_WIDTH => 32,
        CASE12 => "0011",
        din12_WIDTH => 32,
        CASE13 => "0100",
        din13_WIDTH => 32,
        CASE14 => "0101",
        din14_WIDTH => 32,
        CASE15 => "0110",
        din15_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 4,
        dout_WIDTH => 32)
    port map (
        din0 => w_fu_220,
        din1 => w_33_fu_224,
        din2 => w_34_fu_228,
        din3 => w_35_fu_232,
        din4 => w_36_fu_236,
        din5 => w_37_fu_240,
        din6 => w_38_fu_244,
        din7 => w_39_fu_248,
        din8 => w_40_fu_252,
        din9 => w_41_fu_256,
        din10 => w_42_fu_260,
        din11 => w_43_fu_264,
        din12 => w_44_fu_268,
        din13 => w_45_fu_272,
        din14 => w_46_fu_276,
        din15 => w_47_fu_280,
        def => tmp_s_fu_1025_p33,
        sel => trunc_ln133_fu_712_p1,
        dout => tmp_s_fu_1025_p35);

    flow_control_loop_pipe_sequential_init_U : component mine_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_exit_ready = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_wt_2_reg_473_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln138_fu_727_p2 = ap_const_lv1_1))) then 
                ap_phi_reg_pp0_iter2_wt_2_reg_473 <= grp_fu_512_p35;
            elsif ((((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_E)) or ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_0)) or ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_1)) or ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) 
    and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_2)) or ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_3)) or ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_4)) or ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_5)) or ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) 
    and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_6)) or ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_7)) or ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_8)) or ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_9)) 
    or ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_A)) or ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_B)) or ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_C)) or ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) 
    and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_D)) or ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_F)))) then 
                ap_phi_reg_pp0_iter2_wt_2_reg_473 <= wt_5_fu_1165_p2;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter2_wt_2_reg_473 <= ap_phi_reg_pp0_iter1_wt_2_reg_473;
            end if; 
        end if;
    end process;

    b_fu_304_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    b_fu_304 <= ap_const_lv32_6A09E667;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln133_reg_1791 = ap_const_lv1_0))) then 
                    b_fu_304 <= a_fu_1560_p2;
                end if;
            end if; 
        end if;
    end process;

    c_fu_300_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    c_fu_300 <= ap_const_lv32_BB67AE85;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln133_reg_1791 = ap_const_lv1_0))) then 
                    c_fu_300 <= b_fu_304;
                end if;
            end if; 
        end if;
    end process;

    d_3_fu_296_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    d_3_fu_296 <= ap_const_lv32_3C6EF372;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln133_reg_1791 = ap_const_lv1_0))) then 
                    d_3_fu_296 <= c_fu_300;
                end if;
            end if; 
        end if;
    end process;

    d_fu_212_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    d_fu_212 <= ap_const_lv32_A54FF53A;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln133_reg_1791 = ap_const_lv1_0))) then 
                    d_fu_212 <= d_3_fu_296;
                end if;
            end if; 
        end if;
    end process;

    f_fu_292_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    f_fu_292 <= ap_const_lv32_510E527F;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln133_reg_1791 = ap_const_lv1_0))) then 
                    f_fu_292 <= e_fu_1488_p2;
                end if;
            end if; 
        end if;
    end process;

    g_fu_288_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    g_fu_288 <= ap_const_lv32_9B05688C;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln133_reg_1791 = ap_const_lv1_0))) then 
                    g_fu_288 <= f_fu_292;
                end if;
            end if; 
        end if;
    end process;

    h_3_fu_284_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    h_3_fu_284 <= ap_const_lv32_1F83D9AB;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln133_reg_1791 = ap_const_lv1_0))) then 
                    h_3_fu_284 <= g_fu_288;
                end if;
            end if; 
        end if;
    end process;

    h_fu_208_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    h_fu_208 <= ap_const_lv32_5BE0CD19;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln133_reg_1791 = ap_const_lv1_0))) then 
                    h_fu_208 <= h_3_fu_284;
                end if;
            end if; 
        end if;
    end process;

    i_1_fu_216_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_1_fu_216 <= ap_const_lv7_0;
                elsif (((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    i_1_fu_216 <= add_ln133_fu_701_p2;
                end if;
            end if; 
        end if;
    end process;

    w_33_fu_224_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    w_33_fu_224 <= w_1_reload;
                elsif ((ap_const_boolean_1 = ap_condition_819)) then 
                    w_33_fu_224 <= wt_5_fu_1165_p2;
                end if;
            end if; 
        end if;
    end process;

    w_34_fu_228_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    w_34_fu_228 <= w_2_reload;
                elsif ((ap_const_boolean_1 = ap_condition_822)) then 
                    w_34_fu_228 <= wt_5_fu_1165_p2;
                end if;
            end if; 
        end if;
    end process;

    w_35_fu_232_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    w_35_fu_232 <= w_3_reload;
                elsif ((ap_const_boolean_1 = ap_condition_825)) then 
                    w_35_fu_232 <= wt_5_fu_1165_p2;
                end if;
            end if; 
        end if;
    end process;

    w_36_fu_236_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    w_36_fu_236 <= w_4_reload;
                elsif ((ap_const_boolean_1 = ap_condition_828)) then 
                    w_36_fu_236 <= wt_5_fu_1165_p2;
                end if;
            end if; 
        end if;
    end process;

    w_37_fu_240_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    w_37_fu_240 <= w_5_reload;
                elsif ((ap_const_boolean_1 = ap_condition_831)) then 
                    w_37_fu_240 <= wt_5_fu_1165_p2;
                end if;
            end if; 
        end if;
    end process;

    w_38_fu_244_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    w_38_fu_244 <= w_6_reload;
                elsif ((ap_const_boolean_1 = ap_condition_834)) then 
                    w_38_fu_244 <= wt_5_fu_1165_p2;
                end if;
            end if; 
        end if;
    end process;

    w_39_fu_248_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    w_39_fu_248 <= w_7_reload;
                elsif ((ap_const_boolean_1 = ap_condition_837)) then 
                    w_39_fu_248 <= wt_5_fu_1165_p2;
                end if;
            end if; 
        end if;
    end process;

    w_40_fu_252_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    w_40_fu_252 <= w_8_reload;
                elsif ((ap_const_boolean_1 = ap_condition_840)) then 
                    w_40_fu_252 <= wt_5_fu_1165_p2;
                end if;
            end if; 
        end if;
    end process;

    w_41_fu_256_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    w_41_fu_256 <= w_9_reload;
                elsif ((ap_const_boolean_1 = ap_condition_843)) then 
                    w_41_fu_256 <= wt_5_fu_1165_p2;
                end if;
            end if; 
        end if;
    end process;

    w_42_fu_260_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    w_42_fu_260 <= w_10_reload;
                elsif ((ap_const_boolean_1 = ap_condition_846)) then 
                    w_42_fu_260 <= wt_5_fu_1165_p2;
                end if;
            end if; 
        end if;
    end process;

    w_43_fu_264_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    w_43_fu_264 <= w_11_reload;
                elsif ((ap_const_boolean_1 = ap_condition_849)) then 
                    w_43_fu_264 <= wt_5_fu_1165_p2;
                end if;
            end if; 
        end if;
    end process;

    w_44_fu_268_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    w_44_fu_268 <= w_12_reload;
                elsif ((ap_const_boolean_1 = ap_condition_852)) then 
                    w_44_fu_268 <= wt_5_fu_1165_p2;
                end if;
            end if; 
        end if;
    end process;

    w_45_fu_272_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    w_45_fu_272 <= w_13_reload;
                elsif ((ap_const_boolean_1 = ap_condition_855)) then 
                    w_45_fu_272 <= wt_5_fu_1165_p2;
                end if;
            end if; 
        end if;
    end process;

    w_46_fu_276_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    w_46_fu_276 <= w_14_reload;
                elsif ((ap_const_boolean_1 = ap_condition_858)) then 
                    w_46_fu_276 <= wt_5_fu_1165_p2;
                end if;
            end if; 
        end if;
    end process;

    w_47_fu_280_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    w_47_fu_280 <= w_15_reload;
                elsif ((ap_const_boolean_1 = ap_condition_861)) then 
                    w_47_fu_280 <= wt_5_fu_1165_p2;
                end if;
            end if; 
        end if;
    end process;

    w_fu_220_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    w_fu_220 <= w_reload;
                elsif ((ap_const_boolean_1 = ap_condition_864)) then 
                    w_fu_220 <= wt_5_fu_1165_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter1_wt_2_reg_473 <= ap_phi_reg_pp0_iter0_wt_2_reg_473;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln133_reg_1791 <= icmp_ln133_fu_695_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    K_address0 <= zext_ln133_fu_707_p1(6 - 1 downto 0);

    K_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            K_ce0_local <= ap_const_logic_1;
        else 
            K_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    a_2_out <= b_fu_304;

    a_2_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln133_reg_1791, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln133_reg_1791 = ap_const_lv1_1))) then 
            a_2_out_ap_vld <= ap_const_logic_1;
        else 
            a_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    a_fu_1560_p2 <= std_logic_vector(unsigned(add_ln195_fu_1554_p2) + unsigned(xor_ln195_1_fu_1528_p2));
    add_ln133_fu_701_p2 <= std_logic_vector(unsigned(i_1_fu_216) + unsigned(ap_const_lv7_1));
    add_ln159_1_fu_1153_p2 <= std_logic_vector(unsigned(tmp_s_fu_1025_p35) + unsigned(xor_ln159_3_fu_1147_p2));
    add_ln159_fu_1159_p2 <= std_logic_vector(unsigned(xor_ln159_1_fu_1127_p2) + unsigned(grp_fu_512_p35));
    add_ln173_1_fu_1428_p2 <= std_logic_vector(unsigned(h_fu_208) + unsigned(xor_ln173_1_fu_1396_p2));
    add_ln173_2_fu_1434_p2 <= std_logic_vector(unsigned(ap_phi_reg_pp0_iter2_wt_2_reg_473) + unsigned(add_ln173_1_fu_1428_p2));
    add_ln173_fu_1422_p2 <= std_logic_vector(unsigned(K_q0) + unsigned(xor_ln173_3_fu_1416_p2));
    add_ln195_fu_1554_p2 <= std_logic_vector(unsigned(t1_fu_1440_p2) + unsigned(xor_ln195_3_fu_1548_p2));
    and_ln173_1_fu_1374_p2 <= (g_fu_288 and f_fu_292);
    and_ln173_fu_1368_p2 <= (xor_ln173_fu_1362_p2 and h_3_fu_284);
    and_ln195_1_fu_1506_p2 <= (d_3_fu_296 and c_fu_300);
    and_ln195_fu_1500_p2 <= (xor_ln195_fu_1494_p2 and b_fu_304);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_819_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln133_fu_695_p2, trunc_ln133_fu_712_p1, icmp_ln138_fu_727_p2)
    begin
                ap_condition_819 <= ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_1));
    end process;


    ap_condition_822_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln133_fu_695_p2, trunc_ln133_fu_712_p1, icmp_ln138_fu_727_p2)
    begin
                ap_condition_822 <= ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_2));
    end process;


    ap_condition_825_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln133_fu_695_p2, trunc_ln133_fu_712_p1, icmp_ln138_fu_727_p2)
    begin
                ap_condition_825 <= ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_3));
    end process;


    ap_condition_828_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln133_fu_695_p2, trunc_ln133_fu_712_p1, icmp_ln138_fu_727_p2)
    begin
                ap_condition_828 <= ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_4));
    end process;


    ap_condition_831_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln133_fu_695_p2, trunc_ln133_fu_712_p1, icmp_ln138_fu_727_p2)
    begin
                ap_condition_831 <= ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_5));
    end process;


    ap_condition_834_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln133_fu_695_p2, trunc_ln133_fu_712_p1, icmp_ln138_fu_727_p2)
    begin
                ap_condition_834 <= ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_6));
    end process;


    ap_condition_837_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln133_fu_695_p2, trunc_ln133_fu_712_p1, icmp_ln138_fu_727_p2)
    begin
                ap_condition_837 <= ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_7));
    end process;


    ap_condition_840_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln133_fu_695_p2, trunc_ln133_fu_712_p1, icmp_ln138_fu_727_p2)
    begin
                ap_condition_840 <= ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_8));
    end process;


    ap_condition_843_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln133_fu_695_p2, trunc_ln133_fu_712_p1, icmp_ln138_fu_727_p2)
    begin
                ap_condition_843 <= ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_9));
    end process;


    ap_condition_846_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln133_fu_695_p2, trunc_ln133_fu_712_p1, icmp_ln138_fu_727_p2)
    begin
                ap_condition_846 <= ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_A));
    end process;


    ap_condition_849_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln133_fu_695_p2, trunc_ln133_fu_712_p1, icmp_ln138_fu_727_p2)
    begin
                ap_condition_849 <= ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_B));
    end process;


    ap_condition_852_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln133_fu_695_p2, trunc_ln133_fu_712_p1, icmp_ln138_fu_727_p2)
    begin
                ap_condition_852 <= ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_C));
    end process;


    ap_condition_855_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln133_fu_695_p2, trunc_ln133_fu_712_p1, icmp_ln138_fu_727_p2)
    begin
                ap_condition_855 <= ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_D));
    end process;


    ap_condition_858_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln133_fu_695_p2, trunc_ln133_fu_712_p1, icmp_ln138_fu_727_p2)
    begin
                ap_condition_858 <= ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_E));
    end process;


    ap_condition_861_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln133_fu_695_p2, trunc_ln133_fu_712_p1, icmp_ln138_fu_727_p2)
    begin
                ap_condition_861 <= ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_F));
    end process;


    ap_condition_864_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln133_fu_695_p2, trunc_ln133_fu_712_p1, icmp_ln138_fu_727_p2)
    begin
                ap_condition_864 <= ((icmp_ln133_fu_695_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln138_fu_727_p2 = ap_const_lv1_0) and (trunc_ln133_fu_712_p1 = ap_const_lv4_0));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln133_fu_695_p2)
    begin
        if (((icmp_ln133_fu_695_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter2_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_phi_reg_pp0_iter0_wt_2_reg_473 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    b_out <= c_fu_300;

    b_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln133_reg_1791, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln133_reg_1791 = ap_const_lv1_1))) then 
            b_out_ap_vld <= ap_const_logic_1;
        else 
            b_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    c_out <= d_3_fu_296;

    c_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln133_reg_1791, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln133_reg_1791 = ap_const_lv1_1))) then 
            c_out_ap_vld <= ap_const_logic_1;
        else 
            c_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    d_out <= d_fu_212;

    d_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln133_reg_1791, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln133_reg_1791 = ap_const_lv1_1))) then 
            d_out_ap_vld <= ap_const_logic_1;
        else 
            d_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    e_2_out <= f_fu_292;

    e_2_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln133_reg_1791, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln133_reg_1791 = ap_const_lv1_1))) then 
            e_2_out_ap_vld <= ap_const_logic_1;
        else 
            e_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    e_fu_1488_p2 <= std_logic_vector(unsigned(t1_fu_1440_p2) + unsigned(d_fu_212));
    f_out <= g_fu_288;

    f_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln133_reg_1791, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln133_reg_1791 = ap_const_lv1_1))) then 
            f_out_ap_vld <= ap_const_logic_1;
        else 
            f_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    g_out <= h_3_fu_284;

    g_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln133_reg_1791, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln133_reg_1791 = ap_const_lv1_1))) then 
            g_out_ap_vld <= ap_const_logic_1;
        else 
            g_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_512_p33 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    h_out <= h_fu_208;

    h_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln133_reg_1791, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln133_reg_1791 = ap_const_lv1_1))) then 
            h_out_ap_vld <= ap_const_logic_1;
        else 
            h_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln133_fu_695_p2 <= "1" when (i_1_fu_216 = ap_const_lv7_40) else "0";
    icmp_ln138_fu_727_p2 <= "1" when (tmp_2_fu_717_p4 = ap_const_lv3_0) else "0";
    lshr_ln1_fu_969_p4 <= x15_fu_797_p35(31 downto 3);
    lshr_ln2_fu_1011_p4 <= x2_fu_869_p35(31 downto 10);
    lshr_ln33_1_fu_955_p4 <= x15_fu_797_p35(31 downto 18);
    lshr_ln33_2_fu_983_p4 <= x2_fu_869_p35(31 downto 17);
    lshr_ln33_3_fu_997_p4 <= x2_fu_869_p35(31 downto 19);
    lshr_ln33_4_fu_1320_p4 <= f_fu_292(31 downto 6);
    lshr_ln33_5_fu_1334_p4 <= f_fu_292(31 downto 11);
    lshr_ln33_6_fu_1348_p4 <= f_fu_292(31 downto 25);
    lshr_ln33_7_fu_1446_p4 <= b_fu_304(31 downto 2);
    lshr_ln33_8_fu_1460_p4 <= b_fu_304(31 downto 13);
    lshr_ln33_9_fu_1474_p4 <= b_fu_304(31 downto 22);
    lshr_ln_fu_941_p4 <= x15_fu_797_p35(31 downto 7);
    or_ln159_1_fu_1105_p3 <= (trunc_ln33_fu_951_p1 & lshr_ln_fu_941_p4);
    or_ln159_2_fu_1113_p3 <= (trunc_ln33_12_fu_1007_p1 & lshr_ln33_3_fu_997_p4);
    or_ln159_3_fu_1133_p3 <= (trunc_ln33_11_fu_993_p1 & lshr_ln33_2_fu_983_p4);
    or_ln173_1_fu_1388_p3 <= (trunc_ln33_14_fu_1344_p1 & lshr_ln33_5_fu_1334_p4);
    or_ln173_2_fu_1402_p3 <= (trunc_ln33_15_fu_1358_p1 & lshr_ln33_6_fu_1348_p4);
    or_ln195_1_fu_1520_p3 <= (trunc_ln33_17_fu_1470_p1 & lshr_ln33_8_fu_1460_p4);
    or_ln195_2_fu_1534_p3 <= (trunc_ln33_18_fu_1484_p1 & lshr_ln33_9_fu_1474_p4);
    or_ln1_fu_1380_p3 <= (trunc_ln33_13_fu_1330_p1 & lshr_ln33_4_fu_1320_p4);
    or_ln2_fu_1512_p3 <= (trunc_ln33_16_fu_1456_p1 & lshr_ln33_7_fu_1446_p4);
    or_ln_fu_1097_p3 <= (trunc_ln33_10_fu_965_p1 & lshr_ln33_1_fu_955_p4);
    t1_fu_1440_p2 <= std_logic_vector(unsigned(add_ln173_2_fu_1434_p2) + unsigned(add_ln173_fu_1422_p2));
    tmp_2_fu_717_p4 <= i_1_fu_216(6 downto 4);
    tmp_s_fu_1025_p33 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    trunc_ln133_fu_712_p1 <= i_1_fu_216(4 - 1 downto 0);
    trunc_ln33_10_fu_965_p1 <= x15_fu_797_p35(18 - 1 downto 0);
    trunc_ln33_11_fu_993_p1 <= x2_fu_869_p35(17 - 1 downto 0);
    trunc_ln33_12_fu_1007_p1 <= x2_fu_869_p35(19 - 1 downto 0);
    trunc_ln33_13_fu_1330_p1 <= f_fu_292(6 - 1 downto 0);
    trunc_ln33_14_fu_1344_p1 <= f_fu_292(11 - 1 downto 0);
    trunc_ln33_15_fu_1358_p1 <= f_fu_292(25 - 1 downto 0);
    trunc_ln33_16_fu_1456_p1 <= b_fu_304(2 - 1 downto 0);
    trunc_ln33_17_fu_1470_p1 <= b_fu_304(13 - 1 downto 0);
    trunc_ln33_18_fu_1484_p1 <= b_fu_304(22 - 1 downto 0);
    trunc_ln33_fu_951_p1 <= x15_fu_797_p35(7 - 1 downto 0);
    wt_5_fu_1165_p2 <= std_logic_vector(unsigned(add_ln159_fu_1159_p2) + unsigned(add_ln159_1_fu_1153_p2));
    x15_fu_797_p33 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    x2_fu_869_p33 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    xor_ln159_1_fu_1127_p2 <= (xor_ln159_fu_1121_p2 xor or_ln_fu_1097_p3);
    xor_ln159_2_fu_1141_p2 <= (zext_ln154_fu_1021_p1 xor or_ln159_3_fu_1133_p3);
    xor_ln159_3_fu_1147_p2 <= (xor_ln159_2_fu_1141_p2 xor or_ln159_2_fu_1113_p3);
    xor_ln159_fu_1121_p2 <= (zext_ln149_fu_979_p1 xor or_ln159_1_fu_1105_p3);
    xor_ln173_1_fu_1396_p2 <= (and_ln173_fu_1368_p2 xor and_ln173_1_fu_1374_p2);
    xor_ln173_2_fu_1410_p2 <= (or_ln173_2_fu_1402_p3 xor or_ln173_1_fu_1388_p3);
    xor_ln173_3_fu_1416_p2 <= (xor_ln173_2_fu_1410_p2 xor or_ln1_fu_1380_p3);
    xor_ln173_fu_1362_p2 <= (f_fu_292 xor ap_const_lv32_FFFFFFFF);
    xor_ln195_1_fu_1528_p2 <= (and_ln195_fu_1500_p2 xor and_ln195_1_fu_1506_p2);
    xor_ln195_2_fu_1542_p2 <= (or_ln195_2_fu_1534_p3 xor or_ln195_1_fu_1520_p3);
    xor_ln195_3_fu_1548_p2 <= (xor_ln195_2_fu_1542_p2 xor or_ln2_fu_1512_p3);
    xor_ln195_fu_1494_p2 <= (d_3_fu_296 xor c_fu_300);
    zext_ln133_fu_707_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_1_fu_216),64));
    zext_ln149_fu_979_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln1_fu_969_p4),32));
    zext_ln154_fu_1021_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln2_fu_1011_p4),32));
end behav;
