-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mine_mine_Pipeline_BUILD_FIRST_BLOCK is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    hdr_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    hdr_ce0 : OUT STD_LOGIC;
    hdr_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    or7_i_i37_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    or7_i_i37_out_ap_vld : OUT STD_LOGIC;
    or7_i_i35_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    or7_i_i35_out_ap_vld : OUT STD_LOGIC;
    or7_i_i33_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    or7_i_i33_out_ap_vld : OUT STD_LOGIC;
    or7_i_i31_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    or7_i_i31_out_ap_vld : OUT STD_LOGIC;
    or7_i_i29_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    or7_i_i29_out_ap_vld : OUT STD_LOGIC;
    or7_i_i27_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    or7_i_i27_out_ap_vld : OUT STD_LOGIC;
    or7_i_i25_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    or7_i_i25_out_ap_vld : OUT STD_LOGIC;
    or7_i_i23_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    or7_i_i23_out_ap_vld : OUT STD_LOGIC;
    or7_i_i21_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    or7_i_i21_out_ap_vld : OUT STD_LOGIC;
    or7_i_i19_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    or7_i_i19_out_ap_vld : OUT STD_LOGIC;
    or7_i_i17_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    or7_i_i17_out_ap_vld : OUT STD_LOGIC;
    or7_i_i15_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    or7_i_i15_out_ap_vld : OUT STD_LOGIC;
    or7_i_i13_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    or7_i_i13_out_ap_vld : OUT STD_LOGIC;
    or7_i_i11_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    or7_i_i11_out_ap_vld : OUT STD_LOGIC;
    or7_i_i9_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    or7_i_i9_out_ap_vld : OUT STD_LOGIC;
    or7_i_i7_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    or7_i_i7_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of mine_mine_Pipeline_BUILD_FIRST_BLOCK is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln234_fu_309_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal trunc_ln234_fu_326_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln234_reg_665 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln234_fu_321_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal i_4_fu_108 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln234_fu_315_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i : STD_LOGIC_VECTOR (4 downto 0);
    signal or7_i_i7_fu_112 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal tmp_s_fu_403_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal or7_i_i9_fu_116 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal or7_i_i11_fu_120 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal or7_i_i13_fu_124 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal or7_i_i15_fu_128 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal or7_i_i17_fu_132 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal or7_i_i19_fu_136 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal or7_i_i21_fu_140 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal or7_i_i23_fu_144 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal or7_i_i25_fu_148 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal or7_i_i27_fu_152 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal or7_i_i29_fu_156 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal or7_i_i31_fu_160 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal or7_i_i33_fu_164 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal or7_i_i35_fu_168 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal or7_i_i37_fu_172 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal hdr_ce0_local : STD_LOGIC;
    signal empty_fu_369_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_1_fu_383_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_2_fu_393_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_3_fu_373_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component mine_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component mine_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_4_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln234_fu_309_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_4_fu_108 <= add_ln234_fu_315_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_4_fu_108 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln234_reg_665 = ap_const_lv4_C) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                or7_i_i11_fu_120 <= tmp_s_fu_403_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln234_reg_665 = ap_const_lv4_B) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                or7_i_i13_fu_124 <= tmp_s_fu_403_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln234_reg_665 = ap_const_lv4_A) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                or7_i_i15_fu_128 <= tmp_s_fu_403_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln234_reg_665 = ap_const_lv4_9) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                or7_i_i17_fu_132 <= tmp_s_fu_403_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln234_reg_665 = ap_const_lv4_8) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                or7_i_i19_fu_136 <= tmp_s_fu_403_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln234_reg_665 = ap_const_lv4_7) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                or7_i_i21_fu_140 <= tmp_s_fu_403_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln234_reg_665 = ap_const_lv4_6) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                or7_i_i23_fu_144 <= tmp_s_fu_403_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln234_reg_665 = ap_const_lv4_5) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                or7_i_i25_fu_148 <= tmp_s_fu_403_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln234_reg_665 = ap_const_lv4_4) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                or7_i_i27_fu_152 <= tmp_s_fu_403_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln234_reg_665 = ap_const_lv4_3) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                or7_i_i29_fu_156 <= tmp_s_fu_403_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln234_reg_665 = ap_const_lv4_2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                or7_i_i31_fu_160 <= tmp_s_fu_403_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln234_reg_665 = ap_const_lv4_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                or7_i_i33_fu_164 <= tmp_s_fu_403_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln234_reg_665 = ap_const_lv4_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                or7_i_i35_fu_168 <= tmp_s_fu_403_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln234_reg_665 = ap_const_lv4_F) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                or7_i_i37_fu_172 <= tmp_s_fu_403_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln234_reg_665 = ap_const_lv4_E) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                or7_i_i7_fu_112 <= tmp_s_fu_403_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln234_reg_665 = ap_const_lv4_D) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                or7_i_i9_fu_116 <= tmp_s_fu_403_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                trunc_ln234_reg_665 <= trunc_ln234_fu_326_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln234_fu_315_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln234_fu_309_p2)
    begin
        if (((icmp_ln234_fu_309_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_4_fu_108, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_i <= i_4_fu_108;
        end if; 
    end process;

    empty_fu_369_p1 <= hdr_q0(8 - 1 downto 0);
    hdr_address0 <= zext_ln234_fu_321_p1(5 - 1 downto 0);
    hdr_ce0 <= hdr_ce0_local;

    hdr_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hdr_ce0_local <= ap_const_logic_1;
        else 
            hdr_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln234_fu_309_p2 <= "1" when (ap_sig_allocacmp_i = ap_const_lv5_10) else "0";
    or7_i_i11_out <= or7_i_i11_fu_120;

    or7_i_i11_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln234_fu_309_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln234_fu_309_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            or7_i_i11_out_ap_vld <= ap_const_logic_1;
        else 
            or7_i_i11_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    or7_i_i13_out <= or7_i_i13_fu_124;

    or7_i_i13_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln234_fu_309_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln234_fu_309_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            or7_i_i13_out_ap_vld <= ap_const_logic_1;
        else 
            or7_i_i13_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    or7_i_i15_out <= or7_i_i15_fu_128;

    or7_i_i15_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln234_fu_309_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln234_fu_309_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            or7_i_i15_out_ap_vld <= ap_const_logic_1;
        else 
            or7_i_i15_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    or7_i_i17_out <= or7_i_i17_fu_132;

    or7_i_i17_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln234_fu_309_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln234_fu_309_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            or7_i_i17_out_ap_vld <= ap_const_logic_1;
        else 
            or7_i_i17_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    or7_i_i19_out <= or7_i_i19_fu_136;

    or7_i_i19_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln234_fu_309_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln234_fu_309_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            or7_i_i19_out_ap_vld <= ap_const_logic_1;
        else 
            or7_i_i19_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    or7_i_i21_out <= or7_i_i21_fu_140;

    or7_i_i21_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln234_fu_309_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln234_fu_309_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            or7_i_i21_out_ap_vld <= ap_const_logic_1;
        else 
            or7_i_i21_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    or7_i_i23_out <= or7_i_i23_fu_144;

    or7_i_i23_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln234_fu_309_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln234_fu_309_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            or7_i_i23_out_ap_vld <= ap_const_logic_1;
        else 
            or7_i_i23_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    or7_i_i25_out <= or7_i_i25_fu_148;

    or7_i_i25_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln234_fu_309_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln234_fu_309_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            or7_i_i25_out_ap_vld <= ap_const_logic_1;
        else 
            or7_i_i25_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    or7_i_i27_out <= or7_i_i27_fu_152;

    or7_i_i27_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln234_fu_309_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln234_fu_309_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            or7_i_i27_out_ap_vld <= ap_const_logic_1;
        else 
            or7_i_i27_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    or7_i_i29_out <= or7_i_i29_fu_156;

    or7_i_i29_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln234_fu_309_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln234_fu_309_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            or7_i_i29_out_ap_vld <= ap_const_logic_1;
        else 
            or7_i_i29_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    or7_i_i31_out <= or7_i_i31_fu_160;

    or7_i_i31_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln234_fu_309_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln234_fu_309_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            or7_i_i31_out_ap_vld <= ap_const_logic_1;
        else 
            or7_i_i31_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    or7_i_i33_out <= or7_i_i33_fu_164;

    or7_i_i33_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln234_fu_309_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln234_fu_309_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            or7_i_i33_out_ap_vld <= ap_const_logic_1;
        else 
            or7_i_i33_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    or7_i_i35_out <= or7_i_i35_fu_168;

    or7_i_i35_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln234_fu_309_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln234_fu_309_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            or7_i_i35_out_ap_vld <= ap_const_logic_1;
        else 
            or7_i_i35_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    or7_i_i37_out <= or7_i_i37_fu_172;

    or7_i_i37_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln234_fu_309_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln234_fu_309_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            or7_i_i37_out_ap_vld <= ap_const_logic_1;
        else 
            or7_i_i37_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    or7_i_i7_out <= or7_i_i7_fu_112;

    or7_i_i7_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln234_fu_309_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln234_fu_309_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            or7_i_i7_out_ap_vld <= ap_const_logic_1;
        else 
            or7_i_i7_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    or7_i_i9_out <= or7_i_i9_fu_116;

    or7_i_i9_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln234_fu_309_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln234_fu_309_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            or7_i_i9_out_ap_vld <= ap_const_logic_1;
        else 
            or7_i_i9_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_1_fu_383_p4 <= hdr_q0(15 downto 8);
    p_2_fu_393_p4 <= hdr_q0(23 downto 16);
    p_3_fu_373_p4 <= hdr_q0(31 downto 24);
    tmp_s_fu_403_p5 <= (((empty_fu_369_p1 & p_1_fu_383_p4) & p_2_fu_393_p4) & p_3_fu_373_p4);
    trunc_ln234_fu_326_p1 <= ap_sig_allocacmp_i(4 - 1 downto 0);
    zext_ln234_fu_321_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i),64));
end behav;
