-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mine_sha256_compress_words is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    state_read : IN STD_LOGIC_VECTOR (31 downto 0);
    state_read_30 : IN STD_LOGIC_VECTOR (31 downto 0);
    state_read_31 : IN STD_LOGIC_VECTOR (31 downto 0);
    state_read_32 : IN STD_LOGIC_VECTOR (31 downto 0);
    state_read_33 : IN STD_LOGIC_VECTOR (31 downto 0);
    state_read_34 : IN STD_LOGIC_VECTOR (31 downto 0);
    state_read_35 : IN STD_LOGIC_VECTOR (31 downto 0);
    state_read_36 : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_read : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_read_38 : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_read_39 : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_read_40 : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_read_41 : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_read_42 : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_read_43 : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_read_44 : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_read_45 : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_read_46 : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of mine_sha256_compress_words is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal empty_fu_337_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal empty_reg_563 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_done : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_idle : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_ready : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_80_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_80_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_79_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_79_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_78_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_78_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_77_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_77_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_76_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_76_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_75_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_75_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_74_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_74_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_73_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_73_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_72_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_72_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_71_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_71_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_70_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_70_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_69_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_69_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_68_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_68_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_67_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_67_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_66_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_66_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_start : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_done : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_idle : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_ready : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_a_4_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_a_4_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_b_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_b_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_c_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_c_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_d_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_d_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_e_4_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_e_4_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_f_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_f_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_g_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_g_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_h_01_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_h_01_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal add_ln198_fu_430_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln199_fu_435_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln200_fu_440_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln201_fu_445_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln202_fu_450_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln203_fu_455_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln204_fu_460_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln205_fu_465_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component mine_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        block_words_read : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_read_10 : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_read_11 : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_read_12 : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_read_13 : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_read_14 : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_read_15 : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_read_16 : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_read_17 : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_read_18 : IN STD_LOGIC_VECTOR (9 downto 0);
        w_80_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_80_out_ap_vld : OUT STD_LOGIC;
        w_79_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_79_out_ap_vld : OUT STD_LOGIC;
        w_78_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_78_out_ap_vld : OUT STD_LOGIC;
        w_77_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_77_out_ap_vld : OUT STD_LOGIC;
        w_76_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_76_out_ap_vld : OUT STD_LOGIC;
        w_75_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_75_out_ap_vld : OUT STD_LOGIC;
        w_74_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_74_out_ap_vld : OUT STD_LOGIC;
        w_73_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_73_out_ap_vld : OUT STD_LOGIC;
        w_72_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_72_out_ap_vld : OUT STD_LOGIC;
        w_71_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_71_out_ap_vld : OUT STD_LOGIC;
        w_70_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_70_out_ap_vld : OUT STD_LOGIC;
        w_69_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_69_out_ap_vld : OUT STD_LOGIC;
        w_68_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_68_out_ap_vld : OUT STD_LOGIC;
        w_67_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_67_out_ap_vld : OUT STD_LOGIC;
        w_66_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_66_out_ap_vld : OUT STD_LOGIC;
        w_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_out_ap_vld : OUT STD_LOGIC );
    end component;


    component mine_sha256_compress_words_Pipeline_SHA256_ROUNDS IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        w_80_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_79_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_78_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_77_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_76_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_75_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_74_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_73_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_72_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_71_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_70_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_69_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_68_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_67_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_66_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        state_read : IN STD_LOGIC_VECTOR (31 downto 0);
        state_read_8 : IN STD_LOGIC_VECTOR (31 downto 0);
        state_read_9 : IN STD_LOGIC_VECTOR (31 downto 0);
        state_read_10 : IN STD_LOGIC_VECTOR (31 downto 0);
        state_read_11 : IN STD_LOGIC_VECTOR (31 downto 0);
        state_read_12 : IN STD_LOGIC_VECTOR (31 downto 0);
        state_read_13 : IN STD_LOGIC_VECTOR (31 downto 0);
        state_read_14 : IN STD_LOGIC_VECTOR (31 downto 0);
        a_4_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        a_4_out_ap_vld : OUT STD_LOGIC;
        b_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        b_out_ap_vld : OUT STD_LOGIC;
        c_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        c_out_ap_vld : OUT STD_LOGIC;
        d_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        d_out_ap_vld : OUT STD_LOGIC;
        e_4_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        e_4_out_ap_vld : OUT STD_LOGIC;
        f_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        f_out_ap_vld : OUT STD_LOGIC;
        g_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        g_out_ap_vld : OUT STD_LOGIC;
        h_01_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        h_01_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252 : component mine_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start,
        ap_done => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_done,
        ap_idle => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_idle,
        ap_ready => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_ready,
        block_words_read => block_words_read,
        block_words_read_10 => block_words_read_38,
        block_words_read_11 => block_words_read_39,
        block_words_read_12 => block_words_read_40,
        block_words_read_13 => block_words_read_41,
        block_words_read_14 => block_words_read_42,
        block_words_read_15 => block_words_read_43,
        block_words_read_16 => block_words_read_44,
        block_words_read_17 => block_words_read_45,
        block_words_read_18 => empty_reg_563,
        w_80_out => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_80_out,
        w_80_out_ap_vld => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_80_out_ap_vld,
        w_79_out => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_79_out,
        w_79_out_ap_vld => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_79_out_ap_vld,
        w_78_out => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_78_out,
        w_78_out_ap_vld => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_78_out_ap_vld,
        w_77_out => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_77_out,
        w_77_out_ap_vld => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_77_out_ap_vld,
        w_76_out => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_76_out,
        w_76_out_ap_vld => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_76_out_ap_vld,
        w_75_out => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_75_out,
        w_75_out_ap_vld => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_75_out_ap_vld,
        w_74_out => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_74_out,
        w_74_out_ap_vld => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_74_out_ap_vld,
        w_73_out => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_73_out,
        w_73_out_ap_vld => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_73_out_ap_vld,
        w_72_out => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_72_out,
        w_72_out_ap_vld => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_72_out_ap_vld,
        w_71_out => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_71_out,
        w_71_out_ap_vld => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_71_out_ap_vld,
        w_70_out => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_70_out,
        w_70_out_ap_vld => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_70_out_ap_vld,
        w_69_out => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_69_out,
        w_69_out_ap_vld => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_69_out_ap_vld,
        w_68_out => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_68_out,
        w_68_out_ap_vld => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_68_out_ap_vld,
        w_67_out => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_67_out,
        w_67_out_ap_vld => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_67_out_ap_vld,
        w_66_out => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_66_out,
        w_66_out_ap_vld => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_66_out_ap_vld,
        w_out => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_out,
        w_out_ap_vld => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_out_ap_vld);

    grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291 : component mine_sha256_compress_words_Pipeline_SHA256_ROUNDS
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_start,
        ap_done => grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_done,
        ap_idle => grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_idle,
        ap_ready => grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_ready,
        w_80_reload => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_80_out,
        w_79_reload => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_79_out,
        w_78_reload => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_78_out,
        w_77_reload => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_77_out,
        w_76_reload => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_76_out,
        w_75_reload => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_75_out,
        w_74_reload => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_74_out,
        w_73_reload => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_73_out,
        w_72_reload => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_72_out,
        w_71_reload => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_71_out,
        w_70_reload => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_70_out,
        w_69_reload => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_69_out,
        w_68_reload => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_68_out,
        w_67_reload => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_67_out,
        w_66_reload => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_66_out,
        w_reload => grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_out,
        state_read => state_read,
        state_read_8 => state_read_30,
        state_read_9 => state_read_31,
        state_read_10 => state_read_32,
        state_read_11 => state_read_33,
        state_read_12 => state_read_34,
        state_read_13 => state_read_35,
        state_read_14 => state_read_36,
        a_4_out => grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_a_4_out,
        a_4_out_ap_vld => grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_a_4_out_ap_vld,
        b_out => grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_b_out,
        b_out_ap_vld => grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_b_out_ap_vld,
        c_out => grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_c_out,
        c_out_ap_vld => grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_c_out_ap_vld,
        d_out => grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_d_out,
        d_out_ap_vld => grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_d_out_ap_vld,
        e_4_out => grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_e_4_out,
        e_4_out_ap_vld => grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_e_4_out_ap_vld,
        f_out => grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_f_out,
        f_out_ap_vld => grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_f_out_ap_vld,
        g_out => grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_g_out,
        g_out_ap_vld => grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_g_out_ap_vld,
        h_01_out => grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_h_01_out,
        h_01_out_ap_vld => grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_h_01_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_ready = ap_const_logic_1)) then 
                    grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_ready = ap_const_logic_1)) then 
                    grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                empty_reg_563 <= empty_fu_337_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_done, grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln198_fu_430_p2 <= std_logic_vector(unsigned(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_a_4_out) + unsigned(state_read));
    add_ln199_fu_435_p2 <= std_logic_vector(unsigned(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_b_out) + unsigned(state_read_30));
    add_ln200_fu_440_p2 <= std_logic_vector(unsigned(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_c_out) + unsigned(state_read_31));
    add_ln201_fu_445_p2 <= std_logic_vector(unsigned(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_d_out) + unsigned(state_read_32));
    add_ln202_fu_450_p2 <= std_logic_vector(unsigned(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_e_4_out) + unsigned(state_read_33));
    add_ln203_fu_455_p2 <= std_logic_vector(unsigned(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_f_out) + unsigned(state_read_34));
    add_ln204_fu_460_p2 <= std_logic_vector(unsigned(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_g_out) + unsigned(state_read_35));
    add_ln205_fu_465_p2 <= std_logic_vector(unsigned(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_h_01_out) + unsigned(state_read_36));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_done)
    begin
        if ((grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_done)
    begin
        if ((grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= add_ln198_fu_430_p2;
    ap_return_1 <= add_ln199_fu_435_p2;
    ap_return_2 <= add_ln200_fu_440_p2;
    ap_return_3 <= add_ln201_fu_445_p2;
    ap_return_4 <= add_ln202_fu_450_p2;
    ap_return_5 <= add_ln203_fu_455_p2;
    ap_return_6 <= add_ln204_fu_460_p2;
    ap_return_7 <= add_ln205_fu_465_p2;
    empty_fu_337_p1 <= block_words_read_46(10 - 1 downto 0);
    grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start <= grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start_reg;
    grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_start <= grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_start_reg;
end behav;
