// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mine_sha256_compress_words (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        state_read,
        state_read_30,
        state_read_31,
        state_read_32,
        state_read_33,
        state_read_34,
        state_read_35,
        state_read_36,
        block_words_read,
        block_words_read_38,
        block_words_read_39,
        block_words_read_40,
        block_words_read_41,
        block_words_read_42,
        block_words_read_43,
        block_words_read_44,
        block_words_read_45,
        block_words_read_46,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] state_read;
input  [31:0] state_read_30;
input  [31:0] state_read_31;
input  [31:0] state_read_32;
input  [31:0] state_read_33;
input  [31:0] state_read_34;
input  [31:0] state_read_35;
input  [31:0] state_read_36;
input  [31:0] block_words_read;
input  [31:0] block_words_read_38;
input  [31:0] block_words_read_39;
input  [31:0] block_words_read_40;
input  [31:0] block_words_read_41;
input  [31:0] block_words_read_42;
input  [31:0] block_words_read_43;
input  [31:0] block_words_read_44;
input  [31:0] block_words_read_45;
input  [31:0] block_words_read_46;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
output  [31:0] ap_return_2;
output  [31:0] ap_return_3;
output  [31:0] ap_return_4;
output  [31:0] ap_return_5;
output  [31:0] ap_return_6;
output  [31:0] ap_return_7;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [9:0] empty_fu_337_p1;
reg   [9:0] empty_reg_563;
wire    ap_CS_fsm_state3;
wire    grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start;
wire    grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_done;
wire    grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_idle;
wire    grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_ready;
wire   [31:0] grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_80_out;
wire    grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_80_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_79_out;
wire    grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_79_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_78_out;
wire    grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_78_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_77_out;
wire    grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_77_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_76_out;
wire    grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_76_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_75_out;
wire    grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_75_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_74_out;
wire    grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_74_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_73_out;
wire    grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_73_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_72_out;
wire    grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_72_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_71_out;
wire    grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_71_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_70_out;
wire    grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_70_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_69_out;
wire    grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_69_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_68_out;
wire    grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_68_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_67_out;
wire    grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_67_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_66_out;
wire    grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_66_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_out;
wire    grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_out_ap_vld;
wire    grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_start;
wire    grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_done;
wire    grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_idle;
wire    grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_ready;
wire   [31:0] grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_a_4_out;
wire    grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_a_4_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_b_out;
wire    grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_b_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_c_out;
wire    grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_c_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_d_out;
wire    grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_d_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_e_4_out;
wire    grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_e_4_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_f_out;
wire    grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_f_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_g_out;
wire    grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_g_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_h_01_out;
wire    grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_h_01_out_ap_vld;
reg    grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire   [31:0] add_ln198_fu_430_p2;
wire   [31:0] add_ln199_fu_435_p2;
wire   [31:0] add_ln200_fu_440_p2;
wire   [31:0] add_ln201_fu_445_p2;
wire   [31:0] add_ln202_fu_450_p2;
wire   [31:0] add_ln203_fu_455_p2;
wire   [31:0] add_ln204_fu_460_p2;
wire   [31:0] add_ln205_fu_465_p2;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start_reg = 1'b0;
#0 grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_start_reg = 1'b0;
end

mine_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start),
    .ap_done(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_done),
    .ap_idle(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_idle),
    .ap_ready(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_ready),
    .block_words_read(block_words_read),
    .block_words_read_10(block_words_read_38),
    .block_words_read_11(block_words_read_39),
    .block_words_read_12(block_words_read_40),
    .block_words_read_13(block_words_read_41),
    .block_words_read_14(block_words_read_42),
    .block_words_read_15(block_words_read_43),
    .block_words_read_16(block_words_read_44),
    .block_words_read_17(block_words_read_45),
    .block_words_read_18(empty_reg_563),
    .w_80_out(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_80_out),
    .w_80_out_ap_vld(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_80_out_ap_vld),
    .w_79_out(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_79_out),
    .w_79_out_ap_vld(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_79_out_ap_vld),
    .w_78_out(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_78_out),
    .w_78_out_ap_vld(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_78_out_ap_vld),
    .w_77_out(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_77_out),
    .w_77_out_ap_vld(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_77_out_ap_vld),
    .w_76_out(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_76_out),
    .w_76_out_ap_vld(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_76_out_ap_vld),
    .w_75_out(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_75_out),
    .w_75_out_ap_vld(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_75_out_ap_vld),
    .w_74_out(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_74_out),
    .w_74_out_ap_vld(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_74_out_ap_vld),
    .w_73_out(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_73_out),
    .w_73_out_ap_vld(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_73_out_ap_vld),
    .w_72_out(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_72_out),
    .w_72_out_ap_vld(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_72_out_ap_vld),
    .w_71_out(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_71_out),
    .w_71_out_ap_vld(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_71_out_ap_vld),
    .w_70_out(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_70_out),
    .w_70_out_ap_vld(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_70_out_ap_vld),
    .w_69_out(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_69_out),
    .w_69_out_ap_vld(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_69_out_ap_vld),
    .w_68_out(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_68_out),
    .w_68_out_ap_vld(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_68_out_ap_vld),
    .w_67_out(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_67_out),
    .w_67_out_ap_vld(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_67_out_ap_vld),
    .w_66_out(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_66_out),
    .w_66_out_ap_vld(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_66_out_ap_vld),
    .w_out(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_out),
    .w_out_ap_vld(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_out_ap_vld)
);

mine_sha256_compress_words_Pipeline_SHA256_ROUNDS grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_start),
    .ap_done(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_done),
    .ap_idle(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_idle),
    .ap_ready(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_ready),
    .w_80_reload(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_80_out),
    .w_79_reload(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_79_out),
    .w_78_reload(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_78_out),
    .w_77_reload(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_77_out),
    .w_76_reload(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_76_out),
    .w_75_reload(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_75_out),
    .w_74_reload(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_74_out),
    .w_73_reload(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_73_out),
    .w_72_reload(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_72_out),
    .w_71_reload(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_71_out),
    .w_70_reload(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_70_out),
    .w_69_reload(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_69_out),
    .w_68_reload(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_68_out),
    .w_67_reload(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_67_out),
    .w_66_reload(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_66_out),
    .w_reload(grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_out),
    .state_read(state_read),
    .state_read_8(state_read_30),
    .state_read_9(state_read_31),
    .state_read_10(state_read_32),
    .state_read_11(state_read_33),
    .state_read_12(state_read_34),
    .state_read_13(state_read_35),
    .state_read_14(state_read_36),
    .a_4_out(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_a_4_out),
    .a_4_out_ap_vld(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_a_4_out_ap_vld),
    .b_out(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_b_out),
    .b_out_ap_vld(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_b_out_ap_vld),
    .c_out(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_c_out),
    .c_out_ap_vld(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_c_out_ap_vld),
    .d_out(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_d_out),
    .d_out_ap_vld(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_d_out_ap_vld),
    .e_4_out(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_e_4_out),
    .e_4_out_ap_vld(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_e_4_out_ap_vld),
    .f_out(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_f_out),
    .f_out_ap_vld(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_f_out_ap_vld),
    .g_out(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_g_out),
    .g_out_ap_vld(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_g_out_ap_vld),
    .h_01_out(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_h_01_out),
    .h_01_out_ap_vld(grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_h_01_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start_reg <= 1'b1;
        end else if ((grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_ready == 1'b1)) begin
            grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_start_reg <= 1'b1;
        end else if ((grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_ready == 1'b1)) begin
            grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        empty_reg_563 <= empty_fu_337_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln198_fu_430_p2 = (grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_a_4_out + state_read);

assign add_ln199_fu_435_p2 = (grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_b_out + state_read_30);

assign add_ln200_fu_440_p2 = (grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_c_out + state_read_31);

assign add_ln201_fu_445_p2 = (grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_d_out + state_read_32);

assign add_ln202_fu_450_p2 = (grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_e_4_out + state_read_33);

assign add_ln203_fu_455_p2 = (grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_f_out + state_read_34);

assign add_ln204_fu_460_p2 = (grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_g_out + state_read_35);

assign add_ln205_fu_465_p2 = (grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_h_01_out + state_read_36);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_return_0 = add_ln198_fu_430_p2;

assign ap_return_1 = add_ln199_fu_435_p2;

assign ap_return_2 = add_ln200_fu_440_p2;

assign ap_return_3 = add_ln201_fu_445_p2;

assign ap_return_4 = add_ln202_fu_450_p2;

assign ap_return_5 = add_ln203_fu_455_p2;

assign ap_return_6 = add_ln204_fu_460_p2;

assign ap_return_7 = add_ln205_fu_465_p2;

assign empty_fu_337_p1 = block_words_read_46[9:0];

assign grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start = grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start_reg;

assign grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_start = grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291_ap_start_reg;

endmodule //mine_sha256_compress_words
