// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mine_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        block_words_0_val,
        block_words_1_val,
        block_words_2_val,
        block_words_3_val,
        block_words_4_val,
        block_words_5_val,
        block_words_6_val,
        block_words_7_val,
        block_words_8_val,
        block_words_9_val,
        block_words_10_val,
        block_words_11_val,
        block_words_12_val,
        block_words_13_val,
        block_words_14_val,
        block_words_15_val,
        w_15_out,
        w_15_out_ap_vld,
        w_14_out,
        w_14_out_ap_vld,
        w_13_out,
        w_13_out_ap_vld,
        w_12_out,
        w_12_out_ap_vld,
        w_11_out,
        w_11_out_ap_vld,
        w_10_out,
        w_10_out_ap_vld,
        w_9_out,
        w_9_out_ap_vld,
        w_8_out,
        w_8_out_ap_vld,
        w_7_out,
        w_7_out_ap_vld,
        w_6_out,
        w_6_out_ap_vld,
        w_5_out,
        w_5_out_ap_vld,
        w_4_out,
        w_4_out_ap_vld,
        w_3_out,
        w_3_out_ap_vld,
        w_2_out,
        w_2_out_ap_vld,
        w_1_out,
        w_1_out_ap_vld,
        w_out,
        w_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] block_words_0_val;
input  [31:0] block_words_1_val;
input  [31:0] block_words_2_val;
input  [31:0] block_words_3_val;
input  [31:0] block_words_4_val;
input  [31:0] block_words_5_val;
input  [31:0] block_words_6_val;
input  [31:0] block_words_7_val;
input  [31:0] block_words_8_val;
input  [31:0] block_words_9_val;
input  [31:0] block_words_10_val;
input  [31:0] block_words_11_val;
input  [31:0] block_words_12_val;
input  [31:0] block_words_13_val;
input  [31:0] block_words_14_val;
input  [31:0] block_words_15_val;
output  [31:0] w_15_out;
output   w_15_out_ap_vld;
output  [31:0] w_14_out;
output   w_14_out_ap_vld;
output  [31:0] w_13_out;
output   w_13_out_ap_vld;
output  [31:0] w_12_out;
output   w_12_out_ap_vld;
output  [31:0] w_11_out;
output   w_11_out_ap_vld;
output  [31:0] w_10_out;
output   w_10_out_ap_vld;
output  [31:0] w_9_out;
output   w_9_out_ap_vld;
output  [31:0] w_8_out;
output   w_8_out_ap_vld;
output  [31:0] w_7_out;
output   w_7_out_ap_vld;
output  [31:0] w_6_out;
output   w_6_out_ap_vld;
output  [31:0] w_5_out;
output   w_5_out_ap_vld;
output  [31:0] w_4_out;
output   w_4_out_ap_vld;
output  [31:0] w_3_out;
output   w_3_out_ap_vld;
output  [31:0] w_2_out;
output   w_2_out_ap_vld;
output  [31:0] w_1_out;
output   w_1_out_ap_vld;
output  [31:0] w_out;
output   w_out_ap_vld;

reg ap_idle;
reg w_15_out_ap_vld;
reg w_14_out_ap_vld;
reg w_13_out_ap_vld;
reg w_12_out_ap_vld;
reg w_11_out_ap_vld;
reg w_10_out_ap_vld;
reg w_9_out_ap_vld;
reg w_8_out_ap_vld;
reg w_7_out_ap_vld;
reg w_6_out_ap_vld;
reg w_5_out_ap_vld;
reg w_4_out_ap_vld;
reg w_3_out_ap_vld;
reg w_2_out_ap_vld;
reg w_1_out_ap_vld;
reg w_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln118_fu_412_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [4:0] i_fu_128;
wire   [4:0] add_ln118_fu_418_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_i_3;
reg   [31:0] w_fu_132;
wire   [31:0] w_49_fu_428_p35;
wire   [3:0] trunc_ln118_fu_424_p1;
reg   [31:0] w_1_fu_136;
reg   [31:0] w_2_fu_140;
reg   [31:0] w_3_fu_144;
reg   [31:0] w_4_fu_148;
reg   [31:0] w_5_fu_152;
reg   [31:0] w_6_fu_156;
reg   [31:0] w_7_fu_160;
reg   [31:0] w_8_fu_164;
reg   [31:0] w_9_fu_168;
reg   [31:0] w_10_fu_172;
reg   [31:0] w_11_fu_176;
reg   [31:0] w_12_fu_180;
reg   [31:0] w_13_fu_184;
reg   [31:0] w_14_fu_188;
reg   [31:0] w_15_fu_192;
wire   [31:0] w_49_fu_428_p33;
wire   [3:0] w_49_fu_428_p34;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [3:0] w_49_fu_428_p1;
wire   [3:0] w_49_fu_428_p3;
wire   [3:0] w_49_fu_428_p5;
wire   [3:0] w_49_fu_428_p7;
wire   [3:0] w_49_fu_428_p9;
wire   [3:0] w_49_fu_428_p11;
wire   [3:0] w_49_fu_428_p13;
wire   [3:0] w_49_fu_428_p15;
wire  signed [3:0] w_49_fu_428_p17;
wire  signed [3:0] w_49_fu_428_p19;
wire  signed [3:0] w_49_fu_428_p21;
wire  signed [3:0] w_49_fu_428_p23;
wire  signed [3:0] w_49_fu_428_p25;
wire  signed [3:0] w_49_fu_428_p27;
wire  signed [3:0] w_49_fu_428_p29;
wire  signed [3:0] w_49_fu_428_p31;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 i_fu_128 = 5'd0;
#0 w_fu_132 = 32'd0;
#0 w_1_fu_136 = 32'd0;
#0 w_2_fu_140 = 32'd0;
#0 w_3_fu_144 = 32'd0;
#0 w_4_fu_148 = 32'd0;
#0 w_5_fu_152 = 32'd0;
#0 w_6_fu_156 = 32'd0;
#0 w_7_fu_160 = 32'd0;
#0 w_8_fu_164 = 32'd0;
#0 w_9_fu_168 = 32'd0;
#0 w_10_fu_172 = 32'd0;
#0 w_11_fu_176 = 32'd0;
#0 w_12_fu_180 = 32'd0;
#0 w_13_fu_184 = 32'd0;
#0 w_14_fu_188 = 32'd0;
#0 w_15_fu_192 = 32'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) mine_sparsemux_33_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
sparsemux_33_4_32_1_1_U23(
    .din0(block_words_0_val),
    .din1(block_words_1_val),
    .din2(block_words_2_val),
    .din3(block_words_3_val),
    .din4(block_words_4_val),
    .din5(block_words_5_val),
    .din6(block_words_6_val),
    .din7(block_words_7_val),
    .din8(block_words_8_val),
    .din9(block_words_9_val),
    .din10(block_words_10_val),
    .din11(block_words_11_val),
    .din12(block_words_12_val),
    .din13(block_words_13_val),
    .din14(block_words_14_val),
    .din15(block_words_15_val),
    .def(w_49_fu_428_p33),
    .sel(w_49_fu_428_p34),
    .dout(w_49_fu_428_p35)
);

mine_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln118_fu_412_p2 == 1'd0)) begin
            i_fu_128 <= add_ln118_fu_418_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_128 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_424_p1 == 4'd10) & (icmp_ln118_fu_412_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_10_fu_172 <= w_49_fu_428_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_424_p1 == 4'd11) & (icmp_ln118_fu_412_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_11_fu_176 <= w_49_fu_428_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_424_p1 == 4'd12) & (icmp_ln118_fu_412_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_12_fu_180 <= w_49_fu_428_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_424_p1 == 4'd13) & (icmp_ln118_fu_412_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_13_fu_184 <= w_49_fu_428_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_424_p1 == 4'd14) & (icmp_ln118_fu_412_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_14_fu_188 <= w_49_fu_428_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_424_p1 == 4'd15) & (icmp_ln118_fu_412_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_15_fu_192 <= w_49_fu_428_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_424_p1 == 4'd1) & (icmp_ln118_fu_412_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_1_fu_136 <= w_49_fu_428_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_424_p1 == 4'd2) & (icmp_ln118_fu_412_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_2_fu_140 <= w_49_fu_428_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_424_p1 == 4'd3) & (icmp_ln118_fu_412_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_3_fu_144 <= w_49_fu_428_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_424_p1 == 4'd4) & (icmp_ln118_fu_412_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_4_fu_148 <= w_49_fu_428_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_424_p1 == 4'd5) & (icmp_ln118_fu_412_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_5_fu_152 <= w_49_fu_428_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_424_p1 == 4'd6) & (icmp_ln118_fu_412_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_6_fu_156 <= w_49_fu_428_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_424_p1 == 4'd7) & (icmp_ln118_fu_412_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_7_fu_160 <= w_49_fu_428_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_424_p1 == 4'd8) & (icmp_ln118_fu_412_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_8_fu_164 <= w_49_fu_428_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_424_p1 == 4'd9) & (icmp_ln118_fu_412_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_9_fu_168 <= w_49_fu_428_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_424_p1 == 4'd0) & (icmp_ln118_fu_412_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_fu_132 <= w_49_fu_428_p35;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln118_fu_412_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_3 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_3 = i_fu_128;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_412_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_10_out_ap_vld = 1'b1;
    end else begin
        w_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_412_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_11_out_ap_vld = 1'b1;
    end else begin
        w_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_412_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_12_out_ap_vld = 1'b1;
    end else begin
        w_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_412_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_13_out_ap_vld = 1'b1;
    end else begin
        w_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_412_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_14_out_ap_vld = 1'b1;
    end else begin
        w_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_412_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_15_out_ap_vld = 1'b1;
    end else begin
        w_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_412_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_1_out_ap_vld = 1'b1;
    end else begin
        w_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_412_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_2_out_ap_vld = 1'b1;
    end else begin
        w_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_412_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_3_out_ap_vld = 1'b1;
    end else begin
        w_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_412_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_4_out_ap_vld = 1'b1;
    end else begin
        w_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_412_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_5_out_ap_vld = 1'b1;
    end else begin
        w_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_412_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_6_out_ap_vld = 1'b1;
    end else begin
        w_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_412_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_7_out_ap_vld = 1'b1;
    end else begin
        w_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_412_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_8_out_ap_vld = 1'b1;
    end else begin
        w_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_412_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_9_out_ap_vld = 1'b1;
    end else begin
        w_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_412_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_out_ap_vld = 1'b1;
    end else begin
        w_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln118_fu_418_p2 = (ap_sig_allocacmp_i_3 + 5'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln118_fu_412_p2 = ((ap_sig_allocacmp_i_3 == 5'd16) ? 1'b1 : 1'b0);

assign trunc_ln118_fu_424_p1 = ap_sig_allocacmp_i_3[3:0];

assign w_10_out = w_10_fu_172;

assign w_11_out = w_11_fu_176;

assign w_12_out = w_12_fu_180;

assign w_13_out = w_13_fu_184;

assign w_14_out = w_14_fu_188;

assign w_15_out = w_15_fu_192;

assign w_1_out = w_1_fu_136;

assign w_2_out = w_2_fu_140;

assign w_3_out = w_3_fu_144;

assign w_49_fu_428_p33 = 'bx;

assign w_49_fu_428_p34 = ap_sig_allocacmp_i_3[3:0];

assign w_4_out = w_4_fu_148;

assign w_5_out = w_5_fu_152;

assign w_6_out = w_6_fu_156;

assign w_7_out = w_7_fu_160;

assign w_8_out = w_8_fu_164;

assign w_9_out = w_9_fu_168;

assign w_out = w_fu_132;

endmodule //mine_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS
