// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mine_mine_Pipeline_BUILD_FIRST_BLOCK (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        hdr_address0,
        hdr_ce0,
        hdr_q0,
        or7_i_i37_out,
        or7_i_i37_out_ap_vld,
        or7_i_i35_out,
        or7_i_i35_out_ap_vld,
        or7_i_i33_out,
        or7_i_i33_out_ap_vld,
        or7_i_i31_out,
        or7_i_i31_out_ap_vld,
        or7_i_i29_out,
        or7_i_i29_out_ap_vld,
        or7_i_i27_out,
        or7_i_i27_out_ap_vld,
        or7_i_i25_out,
        or7_i_i25_out_ap_vld,
        or7_i_i23_out,
        or7_i_i23_out_ap_vld,
        or7_i_i21_out,
        or7_i_i21_out_ap_vld,
        or7_i_i19_out,
        or7_i_i19_out_ap_vld,
        or7_i_i17_out,
        or7_i_i17_out_ap_vld,
        or7_i_i15_out,
        or7_i_i15_out_ap_vld,
        or7_i_i13_out,
        or7_i_i13_out_ap_vld,
        or7_i_i11_out,
        or7_i_i11_out_ap_vld,
        or7_i_i9_out,
        or7_i_i9_out_ap_vld,
        or7_i_i7_out,
        or7_i_i7_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] hdr_address0;
output   hdr_ce0;
input  [31:0] hdr_q0;
output  [31:0] or7_i_i37_out;
output   or7_i_i37_out_ap_vld;
output  [31:0] or7_i_i35_out;
output   or7_i_i35_out_ap_vld;
output  [31:0] or7_i_i33_out;
output   or7_i_i33_out_ap_vld;
output  [31:0] or7_i_i31_out;
output   or7_i_i31_out_ap_vld;
output  [31:0] or7_i_i29_out;
output   or7_i_i29_out_ap_vld;
output  [31:0] or7_i_i27_out;
output   or7_i_i27_out_ap_vld;
output  [31:0] or7_i_i25_out;
output   or7_i_i25_out_ap_vld;
output  [31:0] or7_i_i23_out;
output   or7_i_i23_out_ap_vld;
output  [31:0] or7_i_i21_out;
output   or7_i_i21_out_ap_vld;
output  [31:0] or7_i_i19_out;
output   or7_i_i19_out_ap_vld;
output  [31:0] or7_i_i17_out;
output   or7_i_i17_out_ap_vld;
output  [31:0] or7_i_i15_out;
output   or7_i_i15_out_ap_vld;
output  [31:0] or7_i_i13_out;
output   or7_i_i13_out_ap_vld;
output  [31:0] or7_i_i11_out;
output   or7_i_i11_out_ap_vld;
output  [31:0] or7_i_i9_out;
output   or7_i_i9_out_ap_vld;
output  [31:0] or7_i_i7_out;
output   or7_i_i7_out_ap_vld;

reg ap_idle;
reg or7_i_i37_out_ap_vld;
reg or7_i_i35_out_ap_vld;
reg or7_i_i33_out_ap_vld;
reg or7_i_i31_out_ap_vld;
reg or7_i_i29_out_ap_vld;
reg or7_i_i27_out_ap_vld;
reg or7_i_i25_out_ap_vld;
reg or7_i_i23_out_ap_vld;
reg or7_i_i21_out_ap_vld;
reg or7_i_i19_out_ap_vld;
reg or7_i_i17_out_ap_vld;
reg or7_i_i15_out_ap_vld;
reg or7_i_i13_out_ap_vld;
reg or7_i_i11_out_ap_vld;
reg or7_i_i9_out_ap_vld;
reg or7_i_i7_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln234_fu_309_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [3:0] trunc_ln234_fu_326_p1;
reg   [3:0] trunc_ln234_reg_665;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln234_fu_321_p1;
wire    ap_block_pp0_stage0;
reg   [4:0] i_4_fu_108;
wire   [4:0] add_ln234_fu_315_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_i;
reg   [31:0] or7_i_i7_fu_112;
wire   [31:0] tmp_s_fu_403_p5;
reg   [31:0] or7_i_i9_fu_116;
reg   [31:0] or7_i_i11_fu_120;
reg   [31:0] or7_i_i13_fu_124;
reg   [31:0] or7_i_i15_fu_128;
reg   [31:0] or7_i_i17_fu_132;
reg   [31:0] or7_i_i19_fu_136;
reg   [31:0] or7_i_i21_fu_140;
reg   [31:0] or7_i_i23_fu_144;
reg   [31:0] or7_i_i25_fu_148;
reg   [31:0] or7_i_i27_fu_152;
reg   [31:0] or7_i_i29_fu_156;
reg   [31:0] or7_i_i31_fu_160;
reg   [31:0] or7_i_i33_fu_164;
reg   [31:0] or7_i_i35_fu_168;
reg   [31:0] or7_i_i37_fu_172;
wire    ap_block_pp0_stage0_01001;
reg    hdr_ce0_local;
wire   [7:0] empty_fu_369_p1;
wire   [7:0] p_1_fu_383_p4;
wire   [7:0] p_2_fu_393_p4;
wire   [7:0] p_3_fu_373_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 i_4_fu_108 = 5'd0;
#0 or7_i_i7_fu_112 = 32'd0;
#0 or7_i_i9_fu_116 = 32'd0;
#0 or7_i_i11_fu_120 = 32'd0;
#0 or7_i_i13_fu_124 = 32'd0;
#0 or7_i_i15_fu_128 = 32'd0;
#0 or7_i_i17_fu_132 = 32'd0;
#0 or7_i_i19_fu_136 = 32'd0;
#0 or7_i_i21_fu_140 = 32'd0;
#0 or7_i_i23_fu_144 = 32'd0;
#0 or7_i_i25_fu_148 = 32'd0;
#0 or7_i_i27_fu_152 = 32'd0;
#0 or7_i_i29_fu_156 = 32'd0;
#0 or7_i_i31_fu_160 = 32'd0;
#0 or7_i_i33_fu_164 = 32'd0;
#0 or7_i_i35_fu_168 = 32'd0;
#0 or7_i_i37_fu_172 = 32'd0;
#0 ap_done_reg = 1'b0;
end

mine_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln234_fu_309_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_4_fu_108 <= add_ln234_fu_315_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_4_fu_108 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln234_reg_665 == 4'd12) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i11_fu_120 <= tmp_s_fu_403_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln234_reg_665 == 4'd11) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i13_fu_124 <= tmp_s_fu_403_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln234_reg_665 == 4'd10) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i15_fu_128 <= tmp_s_fu_403_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln234_reg_665 == 4'd9) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i17_fu_132 <= tmp_s_fu_403_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln234_reg_665 == 4'd8) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i19_fu_136 <= tmp_s_fu_403_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln234_reg_665 == 4'd7) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i21_fu_140 <= tmp_s_fu_403_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln234_reg_665 == 4'd6) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i23_fu_144 <= tmp_s_fu_403_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln234_reg_665 == 4'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i25_fu_148 <= tmp_s_fu_403_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln234_reg_665 == 4'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i27_fu_152 <= tmp_s_fu_403_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln234_reg_665 == 4'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i29_fu_156 <= tmp_s_fu_403_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln234_reg_665 == 4'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i31_fu_160 <= tmp_s_fu_403_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln234_reg_665 == 4'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i33_fu_164 <= tmp_s_fu_403_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln234_reg_665 == 4'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i35_fu_168 <= tmp_s_fu_403_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln234_reg_665 == 4'd15) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i37_fu_172 <= tmp_s_fu_403_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln234_reg_665 == 4'd14) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i7_fu_112 <= tmp_s_fu_403_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln234_reg_665 == 4'd13) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i9_fu_116 <= tmp_s_fu_403_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln234_reg_665 <= trunc_ln234_fu_326_p1;
    end
end

always @ (*) begin
    if (((icmp_ln234_fu_309_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i = 5'd0;
    end else begin
        ap_sig_allocacmp_i = i_4_fu_108;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hdr_ce0_local = 1'b1;
    end else begin
        hdr_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln234_fu_309_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i11_out_ap_vld = 1'b1;
    end else begin
        or7_i_i11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln234_fu_309_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i13_out_ap_vld = 1'b1;
    end else begin
        or7_i_i13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln234_fu_309_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i15_out_ap_vld = 1'b1;
    end else begin
        or7_i_i15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln234_fu_309_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i17_out_ap_vld = 1'b1;
    end else begin
        or7_i_i17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln234_fu_309_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i19_out_ap_vld = 1'b1;
    end else begin
        or7_i_i19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln234_fu_309_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i21_out_ap_vld = 1'b1;
    end else begin
        or7_i_i21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln234_fu_309_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i23_out_ap_vld = 1'b1;
    end else begin
        or7_i_i23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln234_fu_309_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i25_out_ap_vld = 1'b1;
    end else begin
        or7_i_i25_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln234_fu_309_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i27_out_ap_vld = 1'b1;
    end else begin
        or7_i_i27_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln234_fu_309_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i29_out_ap_vld = 1'b1;
    end else begin
        or7_i_i29_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln234_fu_309_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i31_out_ap_vld = 1'b1;
    end else begin
        or7_i_i31_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln234_fu_309_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i33_out_ap_vld = 1'b1;
    end else begin
        or7_i_i33_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln234_fu_309_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i35_out_ap_vld = 1'b1;
    end else begin
        or7_i_i35_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln234_fu_309_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i37_out_ap_vld = 1'b1;
    end else begin
        or7_i_i37_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln234_fu_309_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i7_out_ap_vld = 1'b1;
    end else begin
        or7_i_i7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln234_fu_309_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or7_i_i9_out_ap_vld = 1'b1;
    end else begin
        or7_i_i9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln234_fu_315_p2 = (ap_sig_allocacmp_i + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_fu_369_p1 = hdr_q0[7:0];

assign hdr_address0 = zext_ln234_fu_321_p1;

assign hdr_ce0 = hdr_ce0_local;

assign icmp_ln234_fu_309_p2 = ((ap_sig_allocacmp_i == 5'd16) ? 1'b1 : 1'b0);

assign or7_i_i11_out = or7_i_i11_fu_120;

assign or7_i_i13_out = or7_i_i13_fu_124;

assign or7_i_i15_out = or7_i_i15_fu_128;

assign or7_i_i17_out = or7_i_i17_fu_132;

assign or7_i_i19_out = or7_i_i19_fu_136;

assign or7_i_i21_out = or7_i_i21_fu_140;

assign or7_i_i23_out = or7_i_i23_fu_144;

assign or7_i_i25_out = or7_i_i25_fu_148;

assign or7_i_i27_out = or7_i_i27_fu_152;

assign or7_i_i29_out = or7_i_i29_fu_156;

assign or7_i_i31_out = or7_i_i31_fu_160;

assign or7_i_i33_out = or7_i_i33_fu_164;

assign or7_i_i35_out = or7_i_i35_fu_168;

assign or7_i_i37_out = or7_i_i37_fu_172;

assign or7_i_i7_out = or7_i_i7_fu_112;

assign or7_i_i9_out = or7_i_i9_fu_116;

assign p_1_fu_383_p4 = {{hdr_q0[15:8]}};

assign p_2_fu_393_p4 = {{hdr_q0[23:16]}};

assign p_3_fu_373_p4 = {{hdr_q0[31:24]}};

assign tmp_s_fu_403_p5 = {{{{empty_fu_369_p1}, {p_1_fu_383_p4}}, {p_2_fu_393_p4}}, {p_3_fu_373_p4}};

assign trunc_ln234_fu_326_p1 = ap_sig_allocacmp_i[3:0];

assign zext_ln234_fu_321_p1 = ap_sig_allocacmp_i;

endmodule //mine_mine_Pipeline_BUILD_FIRST_BLOCK
