// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mine_mine_Pipeline_COMPARE_HASH (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        h_address0,
        h_ce0,
        h_q0,
        tgt_address0,
        tgt_ce0,
        tgt_q0,
        retval_1_i35_ce_out,
        retval_1_i35_ce_out_ap_vld,
        cleanup_dest_slot_1_i_ce_out,
        cleanup_dest_slot_1_i_ce_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] h_address0;
output   h_ce0;
input  [7:0] h_q0;
output  [2:0] tgt_address0;
output   tgt_ce0;
input  [31:0] tgt_q0;
output  [0:0] retval_1_i35_ce_out;
output   retval_1_i35_ce_out_ap_vld;
output  [0:0] cleanup_dest_slot_1_i_ce_out;
output   cleanup_dest_slot_1_i_ce_out_ap_vld;

reg ap_idle;
reg retval_1_i35_ce_out_ap_vld;
reg cleanup_dest_slot_1_i_ce_out_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln424_fu_213_p2;
wire   [0:0] icmp_ln420_fu_207_p2;
reg   [0:0] icmp_ln410_reg_230;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] retval_1_i35_ce_reg_100;
reg   [0:0] cleanup_dest_slot_1_i_ce_reg_116;
wire   [0:0] icmp_ln410_fu_140_p2;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [5:0] add_ln410_fu_146_p2;
reg   [5:0] add_ln410_reg_234;
wire   [1:0] trunc_ln417_fu_182_p1;
reg   [1:0] trunc_ln417_reg_249;
wire   [63:0] zext_ln411_fu_162_p1;
wire   [63:0] zext_ln417_fu_177_p1;
reg   [5:0] i_fu_56;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_i_5;
reg    h_ce0_local;
reg    tgt_ce0_local;
wire   [4:0] trunc_ln410_fu_152_p1;
wire   [4:0] xor_ln411_fu_156_p2;
wire   [2:0] word_index_fu_167_p4;
wire   [4:0] shl_ln_fu_186_p3;
wire   [31:0] zext_ln417_1_fu_193_p1;
wire   [31:0] lshr_ln417_fu_197_p2;
wire   [7:0] tb_fu_203_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 i_fu_56 = 6'd0;
#0 ap_done_reg = 1'b0;
end

mine_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln410_reg_230 == 1'd0) & (icmp_ln420_fu_207_p2 == 1'd0) & (icmp_ln424_fu_213_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln410_reg_230 == 1'd0) & (icmp_ln420_fu_207_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        cleanup_dest_slot_1_i_ce_reg_116 <= 1'd1;
    end else if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln410_fu_140_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        cleanup_dest_slot_1_i_ce_reg_116 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_56 <= 6'd0;
    end else if (((icmp_ln410_reg_230 == 1'd0) & (icmp_ln420_fu_207_p2 == 1'd0) & (icmp_ln424_fu_213_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_fu_56 <= add_ln410_reg_234;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln410_reg_230 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        if (((icmp_ln420_fu_207_p2 == 1'd0) & (icmp_ln424_fu_213_p2 == 1'd1))) begin
            retval_1_i35_ce_reg_100 <= 1'd0;
        end else if ((icmp_ln420_fu_207_p2 == 1'd1)) begin
            retval_1_i35_ce_reg_100 <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        add_ln410_reg_234 <= add_ln410_fu_146_p2;
        icmp_ln410_reg_230 <= icmp_ln410_fu_140_p2;
        trunc_ln417_reg_249 <= trunc_ln417_fu_182_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & ((icmp_ln410_reg_230 == 1'd1) | ((icmp_ln420_fu_207_p2 == 1'd1) | (icmp_ln424_fu_213_p2 == 1'd1))))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_5 = 6'd0;
    end else begin
        ap_sig_allocacmp_i_5 = i_fu_56;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state2) & ((icmp_ln410_reg_230 == 1'd1) | ((icmp_ln420_fu_207_p2 == 1'd1) | (icmp_ln424_fu_213_p2 == 1'd1))))) begin
        cleanup_dest_slot_1_i_ce_out_ap_vld = 1'b1;
    end else begin
        cleanup_dest_slot_1_i_ce_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        h_ce0_local = 1'b1;
    end else begin
        h_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state2) & ((icmp_ln410_reg_230 == 1'd1) | ((icmp_ln420_fu_207_p2 == 1'd1) | (icmp_ln424_fu_213_p2 == 1'd1))))) begin
        retval_1_i35_ce_out_ap_vld = 1'b1;
    end else begin
        retval_1_i35_ce_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        tgt_ce0_local = 1'b1;
    end else begin
        tgt_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln410_fu_146_p2 = (ap_sig_allocacmp_i_5 + 6'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign cleanup_dest_slot_1_i_ce_out = cleanup_dest_slot_1_i_ce_reg_116;

assign h_address0 = zext_ln411_fu_162_p1;

assign h_ce0 = h_ce0_local;

assign icmp_ln410_fu_140_p2 = ((ap_sig_allocacmp_i_5 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln420_fu_207_p2 = ((h_q0 < tb_fu_203_p1) ? 1'b1 : 1'b0);

assign icmp_ln424_fu_213_p2 = ((h_q0 > tb_fu_203_p1) ? 1'b1 : 1'b0);

assign lshr_ln417_fu_197_p2 = tgt_q0 >> zext_ln417_1_fu_193_p1;

assign retval_1_i35_ce_out = retval_1_i35_ce_reg_100;

assign shl_ln_fu_186_p3 = {{trunc_ln417_reg_249}, {3'd0}};

assign tb_fu_203_p1 = lshr_ln417_fu_197_p2[7:0];

assign tgt_address0 = zext_ln417_fu_177_p1;

assign tgt_ce0 = tgt_ce0_local;

assign trunc_ln410_fu_152_p1 = ap_sig_allocacmp_i_5[4:0];

assign trunc_ln417_fu_182_p1 = ap_sig_allocacmp_i_5[1:0];

assign word_index_fu_167_p4 = {{ap_sig_allocacmp_i_5[4:2]}};

assign xor_ln411_fu_156_p2 = (trunc_ln410_fu_152_p1 ^ 5'd31);

assign zext_ln411_fu_162_p1 = xor_ln411_fu_156_p2;

assign zext_ln417_1_fu_193_p1 = shl_ln_fu_186_p3;

assign zext_ln417_fu_177_p1 = word_index_fu_167_p4;

endmodule //mine_mine_Pipeline_COMPARE_HASH
