// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mine_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        block_words_read,
        block_words_read_10,
        block_words_read_11,
        block_words_read_12,
        block_words_read_13,
        block_words_read_14,
        block_words_read_15,
        block_words_read_16,
        block_words_read_17,
        block_words_read_18,
        w_80_out,
        w_80_out_ap_vld,
        w_79_out,
        w_79_out_ap_vld,
        w_78_out,
        w_78_out_ap_vld,
        w_77_out,
        w_77_out_ap_vld,
        w_76_out,
        w_76_out_ap_vld,
        w_75_out,
        w_75_out_ap_vld,
        w_74_out,
        w_74_out_ap_vld,
        w_73_out,
        w_73_out_ap_vld,
        w_72_out,
        w_72_out_ap_vld,
        w_71_out,
        w_71_out_ap_vld,
        w_70_out,
        w_70_out_ap_vld,
        w_69_out,
        w_69_out_ap_vld,
        w_68_out,
        w_68_out_ap_vld,
        w_67_out,
        w_67_out_ap_vld,
        w_66_out,
        w_66_out_ap_vld,
        w_out,
        w_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] block_words_read;
input  [31:0] block_words_read_10;
input  [31:0] block_words_read_11;
input  [31:0] block_words_read_12;
input  [31:0] block_words_read_13;
input  [31:0] block_words_read_14;
input  [31:0] block_words_read_15;
input  [31:0] block_words_read_16;
input  [31:0] block_words_read_17;
input  [9:0] block_words_read_18;
output  [31:0] w_80_out;
output   w_80_out_ap_vld;
output  [31:0] w_79_out;
output   w_79_out_ap_vld;
output  [31:0] w_78_out;
output   w_78_out_ap_vld;
output  [31:0] w_77_out;
output   w_77_out_ap_vld;
output  [31:0] w_76_out;
output   w_76_out_ap_vld;
output  [31:0] w_75_out;
output   w_75_out_ap_vld;
output  [31:0] w_74_out;
output   w_74_out_ap_vld;
output  [31:0] w_73_out;
output   w_73_out_ap_vld;
output  [31:0] w_72_out;
output   w_72_out_ap_vld;
output  [31:0] w_71_out;
output   w_71_out_ap_vld;
output  [31:0] w_70_out;
output   w_70_out_ap_vld;
output  [31:0] w_69_out;
output   w_69_out_ap_vld;
output  [31:0] w_68_out;
output   w_68_out_ap_vld;
output  [31:0] w_67_out;
output   w_67_out_ap_vld;
output  [31:0] w_66_out;
output   w_66_out_ap_vld;
output  [31:0] w_out;
output   w_out_ap_vld;

reg ap_idle;
reg w_80_out_ap_vld;
reg w_79_out_ap_vld;
reg w_78_out_ap_vld;
reg w_77_out_ap_vld;
reg w_76_out_ap_vld;
reg w_75_out_ap_vld;
reg w_74_out_ap_vld;
reg w_73_out_ap_vld;
reg w_72_out_ap_vld;
reg w_71_out_ap_vld;
reg w_70_out_ap_vld;
reg w_69_out_ap_vld;
reg w_68_out_ap_vld;
reg w_67_out_ap_vld;
reg w_66_out_ap_vld;
reg w_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln118_fu_370_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [4:0] i_fu_118;
wire   [4:0] add_ln118_fu_376_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_i_2;
reg   [31:0] w_fu_122;
wire   [31:0] w_32_fu_386_p35;
wire   [3:0] trunc_ln118_fu_382_p1;
reg   [31:0] w_17_fu_126;
reg   [31:0] w_18_fu_130;
reg   [31:0] w_19_fu_134;
reg   [31:0] w_20_fu_138;
reg   [31:0] w_21_fu_142;
reg   [31:0] w_22_fu_146;
reg   [31:0] w_23_fu_150;
reg   [31:0] w_24_fu_154;
reg   [31:0] w_25_fu_158;
reg   [31:0] w_26_fu_162;
reg   [31:0] w_27_fu_166;
reg   [31:0] w_28_fu_170;
reg   [31:0] w_29_fu_174;
reg   [31:0] w_30_fu_178;
reg   [31:0] w_31_fu_182;
wire   [31:0] w_32_fu_386_p32;
wire   [31:0] w_32_fu_386_p33;
wire   [3:0] w_32_fu_386_p34;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [3:0] w_32_fu_386_p1;
wire   [3:0] w_32_fu_386_p3;
wire   [3:0] w_32_fu_386_p5;
wire   [3:0] w_32_fu_386_p7;
wire   [3:0] w_32_fu_386_p9;
wire   [3:0] w_32_fu_386_p11;
wire   [3:0] w_32_fu_386_p13;
wire   [3:0] w_32_fu_386_p15;
wire  signed [3:0] w_32_fu_386_p17;
wire  signed [3:0] w_32_fu_386_p19;
wire  signed [3:0] w_32_fu_386_p21;
wire  signed [3:0] w_32_fu_386_p23;
wire  signed [3:0] w_32_fu_386_p25;
wire  signed [3:0] w_32_fu_386_p27;
wire  signed [3:0] w_32_fu_386_p29;
wire  signed [3:0] w_32_fu_386_p31;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 i_fu_118 = 5'd0;
#0 w_fu_122 = 32'd0;
#0 w_17_fu_126 = 32'd0;
#0 w_18_fu_130 = 32'd0;
#0 w_19_fu_134 = 32'd0;
#0 w_20_fu_138 = 32'd0;
#0 w_21_fu_142 = 32'd0;
#0 w_22_fu_146 = 32'd0;
#0 w_23_fu_150 = 32'd0;
#0 w_24_fu_154 = 32'd0;
#0 w_25_fu_158 = 32'd0;
#0 w_26_fu_162 = 32'd0;
#0 w_27_fu_166 = 32'd0;
#0 w_28_fu_170 = 32'd0;
#0 w_29_fu_174 = 32'd0;
#0 w_30_fu_178 = 32'd0;
#0 w_31_fu_182 = 32'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) mine_sparsemux_33_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
sparsemux_33_4_32_1_1_U105(
    .din0(block_words_read),
    .din1(block_words_read_10),
    .din2(block_words_read_11),
    .din3(block_words_read_12),
    .din4(block_words_read_13),
    .din5(block_words_read_14),
    .din6(block_words_read_15),
    .din7(block_words_read_16),
    .din8(block_words_read_17),
    .din9(32'd0),
    .din10(32'd0),
    .din11(32'd0),
    .din12(32'd0),
    .din13(32'd0),
    .din14(32'd0),
    .din15(w_32_fu_386_p32),
    .def(w_32_fu_386_p33),
    .sel(w_32_fu_386_p34),
    .dout(w_32_fu_386_p35)
);

mine_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln118_fu_370_p2 == 1'd0)) begin
            i_fu_118 <= add_ln118_fu_376_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_118 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_382_p1 == 4'd1) & (icmp_ln118_fu_370_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_17_fu_126 <= w_32_fu_386_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_382_p1 == 4'd2) & (icmp_ln118_fu_370_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_18_fu_130 <= w_32_fu_386_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_382_p1 == 4'd3) & (icmp_ln118_fu_370_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_19_fu_134 <= w_32_fu_386_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_382_p1 == 4'd4) & (icmp_ln118_fu_370_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_20_fu_138 <= w_32_fu_386_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_382_p1 == 4'd5) & (icmp_ln118_fu_370_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_21_fu_142 <= w_32_fu_386_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_382_p1 == 4'd6) & (icmp_ln118_fu_370_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_22_fu_146 <= w_32_fu_386_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_382_p1 == 4'd7) & (icmp_ln118_fu_370_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_23_fu_150 <= w_32_fu_386_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_382_p1 == 4'd8) & (icmp_ln118_fu_370_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_24_fu_154 <= w_32_fu_386_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_382_p1 == 4'd9) & (icmp_ln118_fu_370_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_25_fu_158 <= w_32_fu_386_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_382_p1 == 4'd10) & (icmp_ln118_fu_370_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_26_fu_162 <= w_32_fu_386_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_382_p1 == 4'd11) & (icmp_ln118_fu_370_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_27_fu_166 <= w_32_fu_386_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_382_p1 == 4'd12) & (icmp_ln118_fu_370_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_28_fu_170 <= w_32_fu_386_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_382_p1 == 4'd13) & (icmp_ln118_fu_370_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_29_fu_174 <= w_32_fu_386_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_382_p1 == 4'd14) & (icmp_ln118_fu_370_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_30_fu_178 <= w_32_fu_386_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_382_p1 == 4'd15) & (icmp_ln118_fu_370_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_31_fu_182 <= w_32_fu_386_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln118_fu_382_p1 == 4'd0) & (icmp_ln118_fu_370_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_fu_122 <= w_32_fu_386_p35;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln118_fu_370_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_2 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_118;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_370_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_66_out_ap_vld = 1'b1;
    end else begin
        w_66_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_370_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_67_out_ap_vld = 1'b1;
    end else begin
        w_67_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_370_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_68_out_ap_vld = 1'b1;
    end else begin
        w_68_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_370_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_69_out_ap_vld = 1'b1;
    end else begin
        w_69_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_370_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_70_out_ap_vld = 1'b1;
    end else begin
        w_70_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_370_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_71_out_ap_vld = 1'b1;
    end else begin
        w_71_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_370_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_72_out_ap_vld = 1'b1;
    end else begin
        w_72_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_370_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_73_out_ap_vld = 1'b1;
    end else begin
        w_73_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_370_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_74_out_ap_vld = 1'b1;
    end else begin
        w_74_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_370_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_75_out_ap_vld = 1'b1;
    end else begin
        w_75_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_370_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_76_out_ap_vld = 1'b1;
    end else begin
        w_76_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_370_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_77_out_ap_vld = 1'b1;
    end else begin
        w_77_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_370_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_78_out_ap_vld = 1'b1;
    end else begin
        w_78_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_370_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_79_out_ap_vld = 1'b1;
    end else begin
        w_79_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_370_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_80_out_ap_vld = 1'b1;
    end else begin
        w_80_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln118_fu_370_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_out_ap_vld = 1'b1;
    end else begin
        w_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln118_fu_376_p2 = (ap_sig_allocacmp_i_2 + 5'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln118_fu_370_p2 = ((ap_sig_allocacmp_i_2 == 5'd16) ? 1'b1 : 1'b0);

assign trunc_ln118_fu_382_p1 = ap_sig_allocacmp_i_2[3:0];

assign w_32_fu_386_p32 = block_words_read_18;

assign w_32_fu_386_p33 = 'bx;

assign w_32_fu_386_p34 = ap_sig_allocacmp_i_2[3:0];

assign w_66_out = w_17_fu_126;

assign w_67_out = w_18_fu_130;

assign w_68_out = w_19_fu_134;

assign w_69_out = w_20_fu_138;

assign w_70_out = w_21_fu_142;

assign w_71_out = w_22_fu_146;

assign w_72_out = w_23_fu_150;

assign w_73_out = w_24_fu_154;

assign w_74_out = w_25_fu_158;

assign w_75_out = w_26_fu_162;

assign w_76_out = w_27_fu_166;

assign w_77_out = w_28_fu_170;

assign w_78_out = w_29_fu_174;

assign w_79_out = w_30_fu_178;

assign w_80_out = w_31_fu_182;

assign w_out = w_fu_122;

endmodule //mine_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS
