// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mine_sha256_compress_words_Pipeline_SHA256_ROUNDS (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        w_80_reload,
        w_79_reload,
        w_78_reload,
        w_77_reload,
        w_76_reload,
        w_75_reload,
        w_74_reload,
        w_73_reload,
        w_72_reload,
        w_71_reload,
        w_70_reload,
        w_69_reload,
        w_68_reload,
        w_67_reload,
        w_66_reload,
        w_reload,
        state_read,
        state_read_8,
        state_read_9,
        state_read_10,
        state_read_11,
        state_read_12,
        state_read_13,
        state_read_14,
        a_4_out,
        a_4_out_ap_vld,
        b_out,
        b_out_ap_vld,
        c_out,
        c_out_ap_vld,
        d_out,
        d_out_ap_vld,
        e_4_out,
        e_4_out_ap_vld,
        f_out,
        f_out_ap_vld,
        g_out,
        g_out_ap_vld,
        h_01_out,
        h_01_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] w_80_reload;
input  [31:0] w_79_reload;
input  [31:0] w_78_reload;
input  [31:0] w_77_reload;
input  [31:0] w_76_reload;
input  [31:0] w_75_reload;
input  [31:0] w_74_reload;
input  [31:0] w_73_reload;
input  [31:0] w_72_reload;
input  [31:0] w_71_reload;
input  [31:0] w_70_reload;
input  [31:0] w_69_reload;
input  [31:0] w_68_reload;
input  [31:0] w_67_reload;
input  [31:0] w_66_reload;
input  [31:0] w_reload;
input  [31:0] state_read;
input  [31:0] state_read_8;
input  [31:0] state_read_9;
input  [31:0] state_read_10;
input  [31:0] state_read_11;
input  [31:0] state_read_12;
input  [31:0] state_read_13;
input  [31:0] state_read_14;
output  [31:0] a_4_out;
output   a_4_out_ap_vld;
output  [31:0] b_out;
output   b_out_ap_vld;
output  [31:0] c_out;
output   c_out_ap_vld;
output  [31:0] d_out;
output   d_out_ap_vld;
output  [31:0] e_4_out;
output   e_4_out_ap_vld;
output  [31:0] f_out;
output   f_out_ap_vld;
output  [31:0] g_out;
output   g_out_ap_vld;
output  [31:0] h_01_out;
output   h_01_out_ap_vld;

reg ap_idle;
reg a_4_out_ap_vld;
reg b_out_ap_vld;
reg c_out_ap_vld;
reg d_out_ap_vld;
reg e_4_out_ap_vld;
reg f_out_ap_vld;
reg g_out_ap_vld;
reg h_01_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln133_fu_743_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [5:0] K_address0;
wire   [31:0] K_q0;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln133_reg_1839;
wire   [3:0] trunc_ln133_fu_760_p1;
wire   [0:0] icmp_ln138_fu_775_p2;
wire   [31:0] wt_3_fu_1213_p2;
wire   [31:0] grp_fu_560_p35;
wire   [31:0] ap_phi_reg_pp0_iter0_wt_2_reg_521;
reg   [31:0] ap_phi_reg_pp0_iter1_wt_2_reg_521;
reg   [31:0] ap_phi_reg_pp0_iter2_wt_2_reg_521;
wire   [63:0] zext_ln133_fu_755_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] h_fu_208;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [31:0] d_fu_212;
reg   [6:0] i_fu_216;
wire   [6:0] add_ln133_fu_749_p2;
reg   [31:0] w_fu_220;
reg   [31:0] w_1_fu_224;
reg   [31:0] w_2_fu_228;
reg   [31:0] w_3_fu_232;
reg   [31:0] w_4_fu_236;
reg   [31:0] w_5_fu_240;
reg   [31:0] w_6_fu_244;
reg   [31:0] w_7_fu_248;
reg   [31:0] w_8_fu_252;
reg   [31:0] w_9_fu_256;
reg   [31:0] w_10_fu_260;
reg   [31:0] w_11_fu_264;
reg   [31:0] w_12_fu_268;
reg   [31:0] w_13_fu_272;
reg   [31:0] w_14_fu_276;
reg   [31:0] w_15_fu_280;
reg   [31:0] h_1_fu_284;
reg   [31:0] g_fu_288;
reg   [31:0] f_fu_292;
wire   [31:0] e_fu_1536_p2;
reg   [31:0] d_1_fu_296;
reg   [31:0] c_fu_300;
reg   [31:0] b_fu_304;
wire   [31:0] a_fu_1608_p2;
wire    ap_block_pp0_stage0_01001;
reg    K_ce0_local;
wire   [31:0] grp_fu_560_p33;
wire   [2:0] tmp_1_fu_765_p4;
wire   [31:0] x15_fu_845_p33;
wire   [31:0] x2_fu_917_p33;
wire   [31:0] x15_fu_845_p35;
wire   [28:0] lshr_ln3_fu_1017_p4;
wire   [31:0] x2_fu_917_p35;
wire   [21:0] lshr_ln4_fu_1059_p4;
wire   [31:0] tmp_s_fu_1073_p33;
wire   [17:0] trunc_ln33_1_fu_1013_p1;
wire   [13:0] lshr_ln33_s_fu_1003_p4;
wire   [6:0] trunc_ln33_fu_999_p1;
wire   [24:0] lshr_ln_fu_989_p4;
wire   [18:0] trunc_ln33_3_fu_1055_p1;
wire   [12:0] lshr_ln33_2_fu_1045_p4;
wire   [31:0] or_ln159_4_fu_1153_p3;
wire   [31:0] zext_ln149_fu_1027_p1;
wire   [31:0] xor_ln159_fu_1169_p2;
wire   [31:0] or_ln_fu_1145_p3;
wire   [16:0] trunc_ln33_2_fu_1041_p1;
wire   [14:0] lshr_ln33_1_fu_1031_p4;
wire   [31:0] zext_ln154_fu_1069_p1;
wire   [31:0] or_ln159_6_fu_1181_p3;
wire   [31:0] xor_ln159_2_fu_1189_p2;
wire   [31:0] or_ln159_5_fu_1161_p3;
wire   [31:0] tmp_s_fu_1073_p35;
wire   [31:0] xor_ln159_3_fu_1195_p2;
wire   [31:0] xor_ln159_1_fu_1175_p2;
wire   [31:0] add_ln159_fu_1207_p2;
wire   [31:0] add_ln159_1_fu_1201_p2;
wire   [31:0] xor_ln173_fu_1410_p2;
wire   [5:0] trunc_ln33_4_fu_1378_p1;
wire   [25:0] lshr_ln33_3_fu_1368_p4;
wire   [10:0] trunc_ln33_5_fu_1392_p1;
wire   [20:0] lshr_ln33_4_fu_1382_p4;
wire   [31:0] and_ln173_fu_1416_p2;
wire   [31:0] and_ln173_1_fu_1422_p2;
wire   [24:0] trunc_ln33_6_fu_1406_p1;
wire   [6:0] lshr_ln33_5_fu_1396_p4;
wire   [31:0] or_ln173_3_fu_1436_p3;
wire   [31:0] or_ln173_4_fu_1450_p3;
wire   [31:0] xor_ln173_2_fu_1458_p2;
wire   [31:0] or_ln3_fu_1428_p3;
wire   [31:0] xor_ln173_3_fu_1464_p2;
wire   [31:0] xor_ln173_1_fu_1444_p2;
wire   [31:0] add_ln173_1_fu_1476_p2;
wire   [31:0] add_ln173_2_fu_1482_p2;
wire   [31:0] add_ln173_fu_1470_p2;
wire   [31:0] t1_fu_1488_p2;
wire   [31:0] xor_ln195_fu_1542_p2;
wire   [1:0] trunc_ln33_7_fu_1504_p1;
wire   [29:0] lshr_ln33_6_fu_1494_p4;
wire   [12:0] trunc_ln33_8_fu_1518_p1;
wire   [18:0] lshr_ln33_7_fu_1508_p4;
wire   [31:0] and_ln195_fu_1548_p2;
wire   [31:0] and_ln195_1_fu_1554_p2;
wire   [21:0] trunc_ln33_9_fu_1532_p1;
wire   [9:0] lshr_ln33_8_fu_1522_p4;
wire   [31:0] or_ln195_3_fu_1568_p3;
wire   [31:0] or_ln195_4_fu_1582_p3;
wire   [31:0] xor_ln195_2_fu_1590_p2;
wire   [31:0] or_ln4_fu_1560_p3;
wire   [31:0] xor_ln195_3_fu_1596_p2;
wire   [31:0] add_ln195_fu_1602_p2;
wire   [31:0] xor_ln195_1_fu_1576_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_827;
reg    ap_condition_830;
reg    ap_condition_833;
reg    ap_condition_836;
reg    ap_condition_839;
reg    ap_condition_842;
reg    ap_condition_845;
reg    ap_condition_848;
reg    ap_condition_851;
reg    ap_condition_854;
reg    ap_condition_857;
reg    ap_condition_860;
reg    ap_condition_863;
reg    ap_condition_866;
reg    ap_condition_869;
reg    ap_condition_872;
wire   [3:0] grp_fu_560_p1;
wire   [3:0] grp_fu_560_p3;
wire   [3:0] grp_fu_560_p5;
wire   [3:0] grp_fu_560_p7;
wire   [3:0] grp_fu_560_p9;
wire   [3:0] grp_fu_560_p11;
wire   [3:0] grp_fu_560_p13;
wire   [3:0] grp_fu_560_p15;
wire  signed [3:0] grp_fu_560_p17;
wire  signed [3:0] grp_fu_560_p19;
wire  signed [3:0] grp_fu_560_p21;
wire  signed [3:0] grp_fu_560_p23;
wire  signed [3:0] grp_fu_560_p25;
wire  signed [3:0] grp_fu_560_p27;
wire  signed [3:0] grp_fu_560_p29;
wire  signed [3:0] grp_fu_560_p31;
wire  signed [3:0] x15_fu_845_p1;
wire   [3:0] x15_fu_845_p3;
wire   [3:0] x15_fu_845_p5;
wire   [3:0] x15_fu_845_p7;
wire   [3:0] x15_fu_845_p9;
wire   [3:0] x15_fu_845_p11;
wire   [3:0] x15_fu_845_p13;
wire   [3:0] x15_fu_845_p15;
wire   [3:0] x15_fu_845_p17;
wire  signed [3:0] x15_fu_845_p19;
wire  signed [3:0] x15_fu_845_p21;
wire  signed [3:0] x15_fu_845_p23;
wire  signed [3:0] x15_fu_845_p25;
wire  signed [3:0] x15_fu_845_p27;
wire  signed [3:0] x15_fu_845_p29;
wire  signed [3:0] x15_fu_845_p31;
wire   [3:0] x2_fu_917_p1;
wire   [3:0] x2_fu_917_p3;
wire   [3:0] x2_fu_917_p5;
wire   [3:0] x2_fu_917_p7;
wire   [3:0] x2_fu_917_p9;
wire   [3:0] x2_fu_917_p11;
wire  signed [3:0] x2_fu_917_p13;
wire  signed [3:0] x2_fu_917_p15;
wire  signed [3:0] x2_fu_917_p17;
wire  signed [3:0] x2_fu_917_p19;
wire  signed [3:0] x2_fu_917_p21;
wire  signed [3:0] x2_fu_917_p23;
wire  signed [3:0] x2_fu_917_p25;
wire  signed [3:0] x2_fu_917_p27;
wire   [3:0] x2_fu_917_p29;
wire   [3:0] x2_fu_917_p31;
wire   [3:0] tmp_s_fu_1073_p1;
wire  signed [3:0] tmp_s_fu_1073_p3;
wire  signed [3:0] tmp_s_fu_1073_p5;
wire  signed [3:0] tmp_s_fu_1073_p7;
wire  signed [3:0] tmp_s_fu_1073_p9;
wire  signed [3:0] tmp_s_fu_1073_p11;
wire  signed [3:0] tmp_s_fu_1073_p13;
wire  signed [3:0] tmp_s_fu_1073_p15;
wire  signed [3:0] tmp_s_fu_1073_p17;
wire   [3:0] tmp_s_fu_1073_p19;
wire   [3:0] tmp_s_fu_1073_p21;
wire   [3:0] tmp_s_fu_1073_p23;
wire   [3:0] tmp_s_fu_1073_p25;
wire   [3:0] tmp_s_fu_1073_p27;
wire   [3:0] tmp_s_fu_1073_p29;
wire   [3:0] tmp_s_fu_1073_p31;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 h_fu_208 = 32'd0;
#0 d_fu_212 = 32'd0;
#0 i_fu_216 = 7'd0;
#0 w_fu_220 = 32'd0;
#0 w_1_fu_224 = 32'd0;
#0 w_2_fu_228 = 32'd0;
#0 w_3_fu_232 = 32'd0;
#0 w_4_fu_236 = 32'd0;
#0 w_5_fu_240 = 32'd0;
#0 w_6_fu_244 = 32'd0;
#0 w_7_fu_248 = 32'd0;
#0 w_8_fu_252 = 32'd0;
#0 w_9_fu_256 = 32'd0;
#0 w_10_fu_260 = 32'd0;
#0 w_11_fu_264 = 32'd0;
#0 w_12_fu_268 = 32'd0;
#0 w_13_fu_272 = 32'd0;
#0 w_14_fu_276 = 32'd0;
#0 w_15_fu_280 = 32'd0;
#0 h_1_fu_284 = 32'd0;
#0 g_fu_288 = 32'd0;
#0 f_fu_292 = 32'd0;
#0 d_1_fu_296 = 32'd0;
#0 c_fu_300 = 32'd0;
#0 b_fu_304 = 32'd0;
#0 ap_done_reg = 1'b0;
end

mine_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_K_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
K_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(K_address0),
    .ce0(K_ce0_local),
    .q0(K_q0)
);

(* dissolve_hierarchy = "yes" *) mine_sparsemux_33_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
sparsemux_33_4_32_1_1_U132(
    .din0(w_fu_220),
    .din1(w_1_fu_224),
    .din2(w_2_fu_228),
    .din3(w_3_fu_232),
    .din4(w_4_fu_236),
    .din5(w_5_fu_240),
    .din6(w_6_fu_244),
    .din7(w_7_fu_248),
    .din8(w_8_fu_252),
    .din9(w_9_fu_256),
    .din10(w_10_fu_260),
    .din11(w_11_fu_264),
    .din12(w_12_fu_268),
    .din13(w_13_fu_272),
    .din14(w_14_fu_276),
    .din15(w_15_fu_280),
    .def(grp_fu_560_p33),
    .sel(trunc_ln133_fu_760_p1),
    .dout(grp_fu_560_p35)
);

(* dissolve_hierarchy = "yes" *) mine_sparsemux_33_4_32_1_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'hF ),
    .din0_WIDTH( 32 ),
    .CASE1( 4'h0 ),
    .din1_WIDTH( 32 ),
    .CASE2( 4'h1 ),
    .din2_WIDTH( 32 ),
    .CASE3( 4'h2 ),
    .din3_WIDTH( 32 ),
    .CASE4( 4'h3 ),
    .din4_WIDTH( 32 ),
    .CASE5( 4'h4 ),
    .din5_WIDTH( 32 ),
    .CASE6( 4'h5 ),
    .din6_WIDTH( 32 ),
    .CASE7( 4'h6 ),
    .din7_WIDTH( 32 ),
    .CASE8( 4'h7 ),
    .din8_WIDTH( 32 ),
    .CASE9( 4'h8 ),
    .din9_WIDTH( 32 ),
    .CASE10( 4'h9 ),
    .din10_WIDTH( 32 ),
    .CASE11( 4'hA ),
    .din11_WIDTH( 32 ),
    .CASE12( 4'hB ),
    .din12_WIDTH( 32 ),
    .CASE13( 4'hC ),
    .din13_WIDTH( 32 ),
    .CASE14( 4'hD ),
    .din14_WIDTH( 32 ),
    .CASE15( 4'hE ),
    .din15_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
sparsemux_33_4_32_1_1_x_U133(
    .din0(w_fu_220),
    .din1(w_1_fu_224),
    .din2(w_2_fu_228),
    .din3(w_3_fu_232),
    .din4(w_4_fu_236),
    .din5(w_5_fu_240),
    .din6(w_6_fu_244),
    .din7(w_7_fu_248),
    .din8(w_8_fu_252),
    .din9(w_9_fu_256),
    .din10(w_10_fu_260),
    .din11(w_11_fu_264),
    .din12(w_12_fu_268),
    .din13(w_13_fu_272),
    .din14(w_14_fu_276),
    .din15(w_15_fu_280),
    .def(x15_fu_845_p33),
    .sel(trunc_ln133_fu_760_p1),
    .dout(x15_fu_845_p35)
);

(* dissolve_hierarchy = "yes" *) mine_sparsemux_33_4_32_1_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h2 ),
    .din0_WIDTH( 32 ),
    .CASE1( 4'h3 ),
    .din1_WIDTH( 32 ),
    .CASE2( 4'h4 ),
    .din2_WIDTH( 32 ),
    .CASE3( 4'h5 ),
    .din3_WIDTH( 32 ),
    .CASE4( 4'h6 ),
    .din4_WIDTH( 32 ),
    .CASE5( 4'h7 ),
    .din5_WIDTH( 32 ),
    .CASE6( 4'h8 ),
    .din6_WIDTH( 32 ),
    .CASE7( 4'h9 ),
    .din7_WIDTH( 32 ),
    .CASE8( 4'hA ),
    .din8_WIDTH( 32 ),
    .CASE9( 4'hB ),
    .din9_WIDTH( 32 ),
    .CASE10( 4'hC ),
    .din10_WIDTH( 32 ),
    .CASE11( 4'hD ),
    .din11_WIDTH( 32 ),
    .CASE12( 4'hE ),
    .din12_WIDTH( 32 ),
    .CASE13( 4'hF ),
    .din13_WIDTH( 32 ),
    .CASE14( 4'h0 ),
    .din14_WIDTH( 32 ),
    .CASE15( 4'h1 ),
    .din15_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
sparsemux_33_4_32_1_1_x_U134(
    .din0(w_fu_220),
    .din1(w_1_fu_224),
    .din2(w_2_fu_228),
    .din3(w_3_fu_232),
    .din4(w_4_fu_236),
    .din5(w_5_fu_240),
    .din6(w_6_fu_244),
    .din7(w_7_fu_248),
    .din8(w_8_fu_252),
    .din9(w_9_fu_256),
    .din10(w_10_fu_260),
    .din11(w_11_fu_264),
    .din12(w_12_fu_268),
    .din13(w_13_fu_272),
    .din14(w_14_fu_276),
    .din15(w_15_fu_280),
    .def(x2_fu_917_p33),
    .sel(trunc_ln133_fu_760_p1),
    .dout(x2_fu_917_p35)
);

(* dissolve_hierarchy = "yes" *) mine_sparsemux_33_4_32_1_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h7 ),
    .din0_WIDTH( 32 ),
    .CASE1( 4'h8 ),
    .din1_WIDTH( 32 ),
    .CASE2( 4'h9 ),
    .din2_WIDTH( 32 ),
    .CASE3( 4'hA ),
    .din3_WIDTH( 32 ),
    .CASE4( 4'hB ),
    .din4_WIDTH( 32 ),
    .CASE5( 4'hC ),
    .din5_WIDTH( 32 ),
    .CASE6( 4'hD ),
    .din6_WIDTH( 32 ),
    .CASE7( 4'hE ),
    .din7_WIDTH( 32 ),
    .CASE8( 4'hF ),
    .din8_WIDTH( 32 ),
    .CASE9( 4'h0 ),
    .din9_WIDTH( 32 ),
    .CASE10( 4'h1 ),
    .din10_WIDTH( 32 ),
    .CASE11( 4'h2 ),
    .din11_WIDTH( 32 ),
    .CASE12( 4'h3 ),
    .din12_WIDTH( 32 ),
    .CASE13( 4'h4 ),
    .din13_WIDTH( 32 ),
    .CASE14( 4'h5 ),
    .din14_WIDTH( 32 ),
    .CASE15( 4'h6 ),
    .din15_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
sparsemux_33_4_32_1_1_x_U135(
    .din0(w_fu_220),
    .din1(w_1_fu_224),
    .din2(w_2_fu_228),
    .din3(w_3_fu_232),
    .din4(w_4_fu_236),
    .din5(w_5_fu_240),
    .din6(w_6_fu_244),
    .din7(w_7_fu_248),
    .din8(w_8_fu_252),
    .din9(w_9_fu_256),
    .din10(w_10_fu_260),
    .din11(w_11_fu_264),
    .din12(w_12_fu_268),
    .din13(w_13_fu_272),
    .din14(w_14_fu_276),
    .din15(w_15_fu_280),
    .def(tmp_s_fu_1073_p33),
    .sel(trunc_ln133_fu_760_p1),
    .dout(tmp_s_fu_1073_p35)
);

mine_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln133_fu_743_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln138_fu_775_p2 == 1'd1))) begin
        ap_phi_reg_pp0_iter2_wt_2_reg_521 <= grp_fu_560_p35;
    end else if ((((icmp_ln133_fu_743_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd14)) | ((icmp_ln133_fu_743_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd0)) | ((icmp_ln133_fu_743_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd1)) | ((icmp_ln133_fu_743_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd2)) | ((icmp_ln133_fu_743_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 
    == 4'd3)) | ((icmp_ln133_fu_743_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd4)) | ((icmp_ln133_fu_743_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd5)) | ((icmp_ln133_fu_743_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd6)) | ((icmp_ln133_fu_743_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd7)) | ((icmp_ln133_fu_743_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 
    == 4'd8)) | ((icmp_ln133_fu_743_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd9)) | ((icmp_ln133_fu_743_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd10)) | ((icmp_ln133_fu_743_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd11)) | ((icmp_ln133_fu_743_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd12)) | ((icmp_ln133_fu_743_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln138_fu_775_p2 == 1'd0) & 
    (trunc_ln133_fu_760_p1 == 4'd13)) | ((icmp_ln133_fu_743_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd15)))) begin
        ap_phi_reg_pp0_iter2_wt_2_reg_521 <= wt_3_fu_1213_p2;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_wt_2_reg_521 <= ap_phi_reg_pp0_iter1_wt_2_reg_521;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            b_fu_304 <= state_read;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln133_reg_1839 == 1'd0))) begin
            b_fu_304 <= a_fu_1608_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            c_fu_300 <= state_read_8;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln133_reg_1839 == 1'd0))) begin
            c_fu_300 <= b_fu_304;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            d_1_fu_296 <= state_read_9;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln133_reg_1839 == 1'd0))) begin
            d_1_fu_296 <= c_fu_300;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            d_fu_212 <= state_read_10;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln133_reg_1839 == 1'd0))) begin
            d_fu_212 <= d_1_fu_296;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            f_fu_292 <= state_read_11;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln133_reg_1839 == 1'd0))) begin
            f_fu_292 <= e_fu_1536_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            g_fu_288 <= state_read_12;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln133_reg_1839 == 1'd0))) begin
            g_fu_288 <= f_fu_292;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            h_1_fu_284 <= state_read_13;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln133_reg_1839 == 1'd0))) begin
            h_1_fu_284 <= g_fu_288;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            h_fu_208 <= state_read_14;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln133_reg_1839 == 1'd0))) begin
            h_fu_208 <= h_1_fu_284;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_216 <= 7'd0;
        end else if (((icmp_ln133_fu_743_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_fu_216 <= add_ln133_fu_749_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            w_10_fu_260 <= w_75_reload;
        end else if ((1'b1 == ap_condition_827)) begin
            w_10_fu_260 <= wt_3_fu_1213_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            w_11_fu_264 <= w_76_reload;
        end else if ((1'b1 == ap_condition_830)) begin
            w_11_fu_264 <= wt_3_fu_1213_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            w_12_fu_268 <= w_77_reload;
        end else if ((1'b1 == ap_condition_833)) begin
            w_12_fu_268 <= wt_3_fu_1213_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            w_13_fu_272 <= w_78_reload;
        end else if ((1'b1 == ap_condition_836)) begin
            w_13_fu_272 <= wt_3_fu_1213_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            w_14_fu_276 <= w_79_reload;
        end else if ((1'b1 == ap_condition_839)) begin
            w_14_fu_276 <= wt_3_fu_1213_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            w_15_fu_280 <= w_80_reload;
        end else if ((1'b1 == ap_condition_842)) begin
            w_15_fu_280 <= wt_3_fu_1213_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            w_1_fu_224 <= w_66_reload;
        end else if ((1'b1 == ap_condition_845)) begin
            w_1_fu_224 <= wt_3_fu_1213_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            w_2_fu_228 <= w_67_reload;
        end else if ((1'b1 == ap_condition_848)) begin
            w_2_fu_228 <= wt_3_fu_1213_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            w_3_fu_232 <= w_68_reload;
        end else if ((1'b1 == ap_condition_851)) begin
            w_3_fu_232 <= wt_3_fu_1213_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            w_4_fu_236 <= w_69_reload;
        end else if ((1'b1 == ap_condition_854)) begin
            w_4_fu_236 <= wt_3_fu_1213_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            w_5_fu_240 <= w_70_reload;
        end else if ((1'b1 == ap_condition_857)) begin
            w_5_fu_240 <= wt_3_fu_1213_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            w_6_fu_244 <= w_71_reload;
        end else if ((1'b1 == ap_condition_860)) begin
            w_6_fu_244 <= wt_3_fu_1213_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            w_7_fu_248 <= w_72_reload;
        end else if ((1'b1 == ap_condition_863)) begin
            w_7_fu_248 <= wt_3_fu_1213_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            w_8_fu_252 <= w_73_reload;
        end else if ((1'b1 == ap_condition_866)) begin
            w_8_fu_252 <= wt_3_fu_1213_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            w_9_fu_256 <= w_74_reload;
        end else if ((1'b1 == ap_condition_869)) begin
            w_9_fu_256 <= wt_3_fu_1213_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            w_fu_220 <= w_reload;
        end else if ((1'b1 == ap_condition_872)) begin
            w_fu_220 <= wt_3_fu_1213_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_wt_2_reg_521 <= ap_phi_reg_pp0_iter0_wt_2_reg_521;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln133_reg_1839 <= icmp_ln133_fu_743_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        K_ce0_local = 1'b1;
    end else begin
        K_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln133_reg_1839 == 1'd1))) begin
        a_4_out_ap_vld = 1'b1;
    end else begin
        a_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln133_fu_743_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln133_reg_1839 == 1'd1))) begin
        b_out_ap_vld = 1'b1;
    end else begin
        b_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln133_reg_1839 == 1'd1))) begin
        c_out_ap_vld = 1'b1;
    end else begin
        c_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln133_reg_1839 == 1'd1))) begin
        d_out_ap_vld = 1'b1;
    end else begin
        d_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln133_reg_1839 == 1'd1))) begin
        e_4_out_ap_vld = 1'b1;
    end else begin
        e_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln133_reg_1839 == 1'd1))) begin
        f_out_ap_vld = 1'b1;
    end else begin
        f_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln133_reg_1839 == 1'd1))) begin
        g_out_ap_vld = 1'b1;
    end else begin
        g_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln133_reg_1839 == 1'd1))) begin
        h_01_out_ap_vld = 1'b1;
    end else begin
        h_01_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign K_address0 = zext_ln133_fu_755_p1;

assign a_4_out = b_fu_304;

assign a_fu_1608_p2 = (add_ln195_fu_1602_p2 + xor_ln195_1_fu_1576_p2);

assign add_ln133_fu_749_p2 = (i_fu_216 + 7'd1);

assign add_ln159_1_fu_1201_p2 = (tmp_s_fu_1073_p35 + xor_ln159_3_fu_1195_p2);

assign add_ln159_fu_1207_p2 = (xor_ln159_1_fu_1175_p2 + grp_fu_560_p35);

assign add_ln173_1_fu_1476_p2 = (h_fu_208 + xor_ln173_1_fu_1444_p2);

assign add_ln173_2_fu_1482_p2 = (ap_phi_reg_pp0_iter2_wt_2_reg_521 + add_ln173_1_fu_1476_p2);

assign add_ln173_fu_1470_p2 = (K_q0 + xor_ln173_3_fu_1464_p2);

assign add_ln195_fu_1602_p2 = (t1_fu_1488_p2 + xor_ln195_3_fu_1596_p2);

assign and_ln173_1_fu_1422_p2 = (g_fu_288 & f_fu_292);

assign and_ln173_fu_1416_p2 = (xor_ln173_fu_1410_p2 & h_1_fu_284);

assign and_ln195_1_fu_1554_p2 = (d_1_fu_296 & c_fu_300);

assign and_ln195_fu_1548_p2 = (xor_ln195_fu_1542_p2 & b_fu_304);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_827 = ((icmp_ln133_fu_743_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd10));
end

always @ (*) begin
    ap_condition_830 = ((icmp_ln133_fu_743_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd11));
end

always @ (*) begin
    ap_condition_833 = ((icmp_ln133_fu_743_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd12));
end

always @ (*) begin
    ap_condition_836 = ((icmp_ln133_fu_743_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd13));
end

always @ (*) begin
    ap_condition_839 = ((icmp_ln133_fu_743_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd14));
end

always @ (*) begin
    ap_condition_842 = ((icmp_ln133_fu_743_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd15));
end

always @ (*) begin
    ap_condition_845 = ((icmp_ln133_fu_743_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd1));
end

always @ (*) begin
    ap_condition_848 = ((icmp_ln133_fu_743_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd2));
end

always @ (*) begin
    ap_condition_851 = ((icmp_ln133_fu_743_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd3));
end

always @ (*) begin
    ap_condition_854 = ((icmp_ln133_fu_743_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd4));
end

always @ (*) begin
    ap_condition_857 = ((icmp_ln133_fu_743_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd5));
end

always @ (*) begin
    ap_condition_860 = ((icmp_ln133_fu_743_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd6));
end

always @ (*) begin
    ap_condition_863 = ((icmp_ln133_fu_743_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd7));
end

always @ (*) begin
    ap_condition_866 = ((icmp_ln133_fu_743_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd8));
end

always @ (*) begin
    ap_condition_869 = ((icmp_ln133_fu_743_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd9));
end

always @ (*) begin
    ap_condition_872 = ((icmp_ln133_fu_743_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln138_fu_775_p2 == 1'd0) & (trunc_ln133_fu_760_p1 == 4'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_phi_reg_pp0_iter0_wt_2_reg_521 = 'bx;

assign ap_ready = ap_ready_sig;

assign b_out = c_fu_300;

assign c_out = d_1_fu_296;

assign d_out = d_fu_212;

assign e_4_out = f_fu_292;

assign e_fu_1536_p2 = (t1_fu_1488_p2 + d_fu_212);

assign f_out = g_fu_288;

assign g_out = h_1_fu_284;

assign grp_fu_560_p33 = 'bx;

assign h_01_out = h_fu_208;

assign icmp_ln133_fu_743_p2 = ((i_fu_216 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln138_fu_775_p2 = ((tmp_1_fu_765_p4 == 3'd0) ? 1'b1 : 1'b0);

assign lshr_ln33_1_fu_1031_p4 = {{x2_fu_917_p35[31:17]}};

assign lshr_ln33_2_fu_1045_p4 = {{x2_fu_917_p35[31:19]}};

assign lshr_ln33_3_fu_1368_p4 = {{f_fu_292[31:6]}};

assign lshr_ln33_4_fu_1382_p4 = {{f_fu_292[31:11]}};

assign lshr_ln33_5_fu_1396_p4 = {{f_fu_292[31:25]}};

assign lshr_ln33_6_fu_1494_p4 = {{b_fu_304[31:2]}};

assign lshr_ln33_7_fu_1508_p4 = {{b_fu_304[31:13]}};

assign lshr_ln33_8_fu_1522_p4 = {{b_fu_304[31:22]}};

assign lshr_ln33_s_fu_1003_p4 = {{x15_fu_845_p35[31:18]}};

assign lshr_ln3_fu_1017_p4 = {{x15_fu_845_p35[31:3]}};

assign lshr_ln4_fu_1059_p4 = {{x2_fu_917_p35[31:10]}};

assign lshr_ln_fu_989_p4 = {{x15_fu_845_p35[31:7]}};

assign or_ln159_4_fu_1153_p3 = {{trunc_ln33_fu_999_p1}, {lshr_ln_fu_989_p4}};

assign or_ln159_5_fu_1161_p3 = {{trunc_ln33_3_fu_1055_p1}, {lshr_ln33_2_fu_1045_p4}};

assign or_ln159_6_fu_1181_p3 = {{trunc_ln33_2_fu_1041_p1}, {lshr_ln33_1_fu_1031_p4}};

assign or_ln173_3_fu_1436_p3 = {{trunc_ln33_5_fu_1392_p1}, {lshr_ln33_4_fu_1382_p4}};

assign or_ln173_4_fu_1450_p3 = {{trunc_ln33_6_fu_1406_p1}, {lshr_ln33_5_fu_1396_p4}};

assign or_ln195_3_fu_1568_p3 = {{trunc_ln33_8_fu_1518_p1}, {lshr_ln33_7_fu_1508_p4}};

assign or_ln195_4_fu_1582_p3 = {{trunc_ln33_9_fu_1532_p1}, {lshr_ln33_8_fu_1522_p4}};

assign or_ln3_fu_1428_p3 = {{trunc_ln33_4_fu_1378_p1}, {lshr_ln33_3_fu_1368_p4}};

assign or_ln4_fu_1560_p3 = {{trunc_ln33_7_fu_1504_p1}, {lshr_ln33_6_fu_1494_p4}};

assign or_ln_fu_1145_p3 = {{trunc_ln33_1_fu_1013_p1}, {lshr_ln33_s_fu_1003_p4}};

assign t1_fu_1488_p2 = (add_ln173_2_fu_1482_p2 + add_ln173_fu_1470_p2);

assign tmp_1_fu_765_p4 = {{i_fu_216[6:4]}};

assign tmp_s_fu_1073_p33 = 'bx;

assign trunc_ln133_fu_760_p1 = i_fu_216[3:0];

assign trunc_ln33_1_fu_1013_p1 = x15_fu_845_p35[17:0];

assign trunc_ln33_2_fu_1041_p1 = x2_fu_917_p35[16:0];

assign trunc_ln33_3_fu_1055_p1 = x2_fu_917_p35[18:0];

assign trunc_ln33_4_fu_1378_p1 = f_fu_292[5:0];

assign trunc_ln33_5_fu_1392_p1 = f_fu_292[10:0];

assign trunc_ln33_6_fu_1406_p1 = f_fu_292[24:0];

assign trunc_ln33_7_fu_1504_p1 = b_fu_304[1:0];

assign trunc_ln33_8_fu_1518_p1 = b_fu_304[12:0];

assign trunc_ln33_9_fu_1532_p1 = b_fu_304[21:0];

assign trunc_ln33_fu_999_p1 = x15_fu_845_p35[6:0];

assign wt_3_fu_1213_p2 = (add_ln159_fu_1207_p2 + add_ln159_1_fu_1201_p2);

assign x15_fu_845_p33 = 'bx;

assign x2_fu_917_p33 = 'bx;

assign xor_ln159_1_fu_1175_p2 = (xor_ln159_fu_1169_p2 ^ or_ln_fu_1145_p3);

assign xor_ln159_2_fu_1189_p2 = (zext_ln154_fu_1069_p1 ^ or_ln159_6_fu_1181_p3);

assign xor_ln159_3_fu_1195_p2 = (xor_ln159_2_fu_1189_p2 ^ or_ln159_5_fu_1161_p3);

assign xor_ln159_fu_1169_p2 = (zext_ln149_fu_1027_p1 ^ or_ln159_4_fu_1153_p3);

assign xor_ln173_1_fu_1444_p2 = (and_ln173_fu_1416_p2 ^ and_ln173_1_fu_1422_p2);

assign xor_ln173_2_fu_1458_p2 = (or_ln173_4_fu_1450_p3 ^ or_ln173_3_fu_1436_p3);

assign xor_ln173_3_fu_1464_p2 = (xor_ln173_2_fu_1458_p2 ^ or_ln3_fu_1428_p3);

assign xor_ln173_fu_1410_p2 = (f_fu_292 ^ 32'd4294967295);

assign xor_ln195_1_fu_1576_p2 = (and_ln195_fu_1548_p2 ^ and_ln195_1_fu_1554_p2);

assign xor_ln195_2_fu_1590_p2 = (or_ln195_4_fu_1582_p3 ^ or_ln195_3_fu_1568_p3);

assign xor_ln195_3_fu_1596_p2 = (xor_ln195_2_fu_1590_p2 ^ or_ln4_fu_1560_p3);

assign xor_ln195_fu_1542_p2 = (d_1_fu_296 ^ c_fu_300);

assign zext_ln133_fu_755_p1 = i_fu_216;

assign zext_ln149_fu_1027_p1 = lshr_ln3_fu_1017_p4;

assign zext_ln154_fu_1069_p1 = lshr_ln4_fu_1059_p4;

endmodule //mine_sha256_compress_words_Pipeline_SHA256_ROUNDS
