// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mine_sha256_compress_words_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        block_words_0_val,
        block_words_1_val,
        block_words_2_val,
        block_words_3_val,
        block_words_4_val,
        block_words_5_val,
        block_words_6_val,
        block_words_7_val,
        block_words_8_val,
        block_words_9_val,
        block_words_10_val,
        block_words_11_val,
        block_words_12_val,
        block_words_13_val,
        block_words_14_val,
        block_words_15_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] block_words_0_val;
input  [31:0] block_words_1_val;
input  [31:0] block_words_2_val;
input  [31:0] block_words_3_val;
input  [31:0] block_words_4_val;
input  [31:0] block_words_5_val;
input  [31:0] block_words_6_val;
input  [31:0] block_words_7_val;
input  [31:0] block_words_8_val;
input  [31:0] block_words_9_val;
input  [31:0] block_words_10_val;
input  [31:0] block_words_11_val;
input  [31:0] block_words_12_val;
input  [31:0] block_words_13_val;
input  [31:0] block_words_14_val;
input  [31:0] block_words_15_val;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
output  [31:0] ap_return_2;
output  [31:0] ap_return_3;
output  [31:0] ap_return_4;
output  [31:0] ap_return_5;
output  [31:0] ap_return_6;
output  [31:0] ap_return_7;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start;
wire    grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_done;
wire    grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_idle;
wire    grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_ready;
wire   [31:0] grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_15_out;
wire    grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_15_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_14_out;
wire    grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_14_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_13_out;
wire    grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_13_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_12_out;
wire    grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_12_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_11_out;
wire    grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_11_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_10_out;
wire    grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_10_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_9_out;
wire    grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_9_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_8_out;
wire    grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_8_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_7_out;
wire    grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_7_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_6_out;
wire    grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_6_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_5_out;
wire    grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_5_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_4_out;
wire    grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_4_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_3_out;
wire    grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_3_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_2_out;
wire    grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_2_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_1_out;
wire    grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_1_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_out;
wire    grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_out_ap_vld;
wire    grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_start;
wire    grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_done;
wire    grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_idle;
wire    grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_ready;
wire   [31:0] grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_a_2_out;
wire    grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_a_2_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_b_out;
wire    grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_b_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_c_out;
wire    grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_c_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_d_out;
wire    grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_d_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_e_2_out;
wire    grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_e_2_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_f_out;
wire    grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_f_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_g_out;
wire    grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_g_out_ap_vld;
wire   [31:0] grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_h_out;
wire    grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_h_out_ap_vld;
reg    grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire   [31:0] add_ln198_fu_422_p2;
wire   [31:0] add_ln199_fu_428_p2;
wire   [31:0] add_ln200_fu_434_p2;
wire   [31:0] add_ln201_fu_440_p2;
wire   [31:0] add_ln202_fu_446_p2;
wire   [31:0] add_ln203_fu_452_p2;
wire   [31:0] add_ln204_fu_458_p2;
wire   [31:0] add_ln205_fu_464_p2;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start_reg = 1'b0;
#0 grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_start_reg = 1'b0;
end

mine_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start),
    .ap_done(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_done),
    .ap_idle(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_idle),
    .ap_ready(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_ready),
    .block_words_0_val(block_words_0_val),
    .block_words_1_val(block_words_1_val),
    .block_words_2_val(block_words_2_val),
    .block_words_3_val(block_words_3_val),
    .block_words_4_val(block_words_4_val),
    .block_words_5_val(block_words_5_val),
    .block_words_6_val(block_words_6_val),
    .block_words_7_val(block_words_7_val),
    .block_words_8_val(block_words_8_val),
    .block_words_9_val(block_words_9_val),
    .block_words_10_val(block_words_10_val),
    .block_words_11_val(block_words_11_val),
    .block_words_12_val(block_words_12_val),
    .block_words_13_val(block_words_13_val),
    .block_words_14_val(block_words_14_val),
    .block_words_15_val(block_words_15_val),
    .w_15_out(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_15_out),
    .w_15_out_ap_vld(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_15_out_ap_vld),
    .w_14_out(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_14_out),
    .w_14_out_ap_vld(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_14_out_ap_vld),
    .w_13_out(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_13_out),
    .w_13_out_ap_vld(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_13_out_ap_vld),
    .w_12_out(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_12_out),
    .w_12_out_ap_vld(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_12_out_ap_vld),
    .w_11_out(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_11_out),
    .w_11_out_ap_vld(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_11_out_ap_vld),
    .w_10_out(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_10_out),
    .w_10_out_ap_vld(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_10_out_ap_vld),
    .w_9_out(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_9_out),
    .w_9_out_ap_vld(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_9_out_ap_vld),
    .w_8_out(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_8_out),
    .w_8_out_ap_vld(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_8_out_ap_vld),
    .w_7_out(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_7_out),
    .w_7_out_ap_vld(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_7_out_ap_vld),
    .w_6_out(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_6_out),
    .w_6_out_ap_vld(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_6_out_ap_vld),
    .w_5_out(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_5_out),
    .w_5_out_ap_vld(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_5_out_ap_vld),
    .w_4_out(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_4_out),
    .w_4_out_ap_vld(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_4_out_ap_vld),
    .w_3_out(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_3_out),
    .w_3_out_ap_vld(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_3_out_ap_vld),
    .w_2_out(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_2_out),
    .w_2_out_ap_vld(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_2_out_ap_vld),
    .w_1_out(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_1_out),
    .w_1_out_ap_vld(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_1_out_ap_vld),
    .w_out(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_out),
    .w_out_ap_vld(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_out_ap_vld)
);

mine_sha256_compress_words_1_Pipeline_SHA256_ROUNDS grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_start),
    .ap_done(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_done),
    .ap_idle(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_idle),
    .ap_ready(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_ready),
    .w_15_reload(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_15_out),
    .w_14_reload(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_14_out),
    .w_13_reload(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_13_out),
    .w_12_reload(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_12_out),
    .w_11_reload(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_11_out),
    .w_10_reload(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_10_out),
    .w_9_reload(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_9_out),
    .w_8_reload(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_8_out),
    .w_7_reload(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_7_out),
    .w_6_reload(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_6_out),
    .w_5_reload(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_5_out),
    .w_4_reload(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_4_out),
    .w_3_reload(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_3_out),
    .w_2_reload(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_2_out),
    .w_1_reload(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_1_out),
    .w_reload(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_out),
    .a_2_out(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_a_2_out),
    .a_2_out_ap_vld(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_a_2_out_ap_vld),
    .b_out(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_b_out),
    .b_out_ap_vld(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_b_out_ap_vld),
    .c_out(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_c_out),
    .c_out_ap_vld(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_c_out_ap_vld),
    .d_out(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_d_out),
    .d_out_ap_vld(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_d_out_ap_vld),
    .e_2_out(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_e_2_out),
    .e_2_out_ap_vld(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_e_2_out_ap_vld),
    .f_out(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_f_out),
    .f_out_ap_vld(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_f_out_ap_vld),
    .g_out(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_g_out),
    .g_out_ap_vld(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_g_out_ap_vld),
    .h_out(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_h_out),
    .h_out_ap_vld(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_h_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start_reg <= 1'b1;
        end else if ((grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_ready == 1'b1)) begin
            grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_start_reg <= 1'b1;
        end else if ((grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_ready == 1'b1)) begin
            grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln198_fu_422_p2 = (grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_a_2_out + 32'd1779033703);

assign add_ln199_fu_428_p2 = ($signed(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_b_out) + $signed(32'd3144134277));

assign add_ln200_fu_434_p2 = (grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_c_out + 32'd1013904242);

assign add_ln201_fu_440_p2 = ($signed(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_d_out) + $signed(32'd2773480762));

assign add_ln202_fu_446_p2 = (grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_e_2_out + 32'd1359893119);

assign add_ln203_fu_452_p2 = ($signed(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_f_out) + $signed(32'd2600822924));

assign add_ln204_fu_458_p2 = (grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_g_out + 32'd528734635);

assign add_ln205_fu_464_p2 = (grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_h_out + 32'd1541459225);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_return_0 = add_ln198_fu_422_p2;

assign ap_return_1 = add_ln199_fu_428_p2;

assign ap_return_2 = add_ln200_fu_434_p2;

assign ap_return_3 = add_ln201_fu_440_p2;

assign ap_return_4 = add_ln202_fu_446_p2;

assign ap_return_5 = add_ln203_fu_452_p2;

assign ap_return_6 = add_ln204_fu_458_p2;

assign ap_return_7 = add_ln205_fu_464_p2;

assign grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start = grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start_reg;

assign grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_start = grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_start_reg;

endmodule //mine_sha256_compress_words_1
