

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "6", "8", "10", "21", "33", "35", "36", "37", "38"],
		"CDFG" : "mine",
		"Protocol" : "ap_ctrl_chain",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "grp_mine_Pipeline_VITIS_LOOP_448_1_fu_341", "Port" : "gmem0", "Inst_start_state" : "74", "Inst_end_state" : "75"}]},
			{"Name" : "gmem1", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem1_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem1_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "gmem2", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem2_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem2_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem2_blk_n_B", "Type" : "RtlSignal"}]},
			{"Name" : "header", "Type" : "None", "Direction" : "I"},
			{"Name" : "target", "Type" : "None", "Direction" : "I"},
			{"Name" : "nonce_start", "Type" : "None", "Direction" : "I"},
			{"Name" : "nonce_count", "Type" : "None", "Direction" : "I"},
			{"Name" : "found_nonce", "Type" : "None", "Direction" : "I"},
			{"Name" : "found", "Type" : "None", "Direction" : "I"},
			{"Name" : "K", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "10", "SubInstance" : "grp_sha256_compress_words_1_fu_376", "Port" : "K", "Inst_start_state" : "78", "Inst_end_state" : "79"},
					{"ID" : "21", "SubInstance" : "grp_sha256d_from_midstate_fu_398", "Port" : "K", "Inst_start_state" : "81", "Inst_end_state" : "82"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_468_3", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "155", "FirstState" : "ap_ST_fsm_state80", "LastState" : ["ap_ST_fsm_state85"], "QuitState" : ["ap_ST_fsm_state85"], "PreState" : ["ap_ST_fsm_state79"], "PostState" : ["ap_ST_fsm_state86"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hdr_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.tgt_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.h_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_mine_Pipeline_VITIS_LOOP_448_1_fu_341", "Parent" : "0", "Child" : ["5"],
		"CDFG" : "mine_Pipeline_VITIS_LOOP_448_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "23", "EstimateLatencyMax" : "23",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "hdr", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "sext_ln448", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_448_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mine_Pipeline_VITIS_LOOP_448_1_fu_341.flow_control_loop_pipe_sequential_init_U", "Parent" : "4"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_mine_Pipeline_VITIS_LOOP_453_2_fu_349", "Parent" : "0", "Child" : ["7"],
		"CDFG" : "mine_Pipeline_VITIS_LOOP_453_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem1_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "tgt", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_453_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mine_Pipeline_VITIS_LOOP_453_2_fu_349.flow_control_loop_pipe_sequential_init_U", "Parent" : "6"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_mine_Pipeline_BUILD_FIRST_BLOCK_fu_355", "Parent" : "0", "Child" : ["9"],
		"CDFG" : "mine_Pipeline_BUILD_FIRST_BLOCK",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "18", "EstimateLatencyMax" : "18",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "hdr", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "or7_i_i37_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "or7_i_i35_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "or7_i_i33_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "or7_i_i31_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "or7_i_i29_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "or7_i_i27_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "or7_i_i25_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "or7_i_i23_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "or7_i_i21_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "or7_i_i19_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "or7_i_i17_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "or7_i_i15_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "or7_i_i13_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "or7_i_i11_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "or7_i_i9_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "or7_i_i7_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "BUILD_FIRST_BLOCK", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mine_Pipeline_BUILD_FIRST_BLOCK_fu_355.flow_control_loop_pipe_sequential_init_U", "Parent" : "8"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_sha256_compress_words_1_fu_376", "Parent" : "0", "Child" : ["11", "14"],
		"CDFG" : "sha256_compress_words_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "89", "EstimateLatencyMax" : "89",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "block_words_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_1_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_2_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_3_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_4_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_5_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_6_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_7_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_8_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_9_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_10_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_11_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_12_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_13_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_14_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_15_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "K", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "14", "SubInstance" : "grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304", "Port" : "K", "Inst_start_state" : "3", "Inst_end_state" : "4"}]}]},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_sha256_compress_words_1_fu_376.grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252", "Parent" : "10", "Child" : ["12", "13"],
		"CDFG" : "sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "18", "EstimateLatencyMax" : "18",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "block_words_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_1_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_2_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_3_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_4_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_5_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_6_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_7_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_8_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_9_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_10_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_11_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_12_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_13_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_14_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_15_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_15_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_14_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_13_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_12_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_11_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_10_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_9_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_8_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_7_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_6_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_5_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_4_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_3_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_1_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "LOAD_INITIAL_WORDS", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state1", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state1_blk", "QuitState" : "ap_ST_fsm_state1", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state1_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "12", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_sha256_compress_words_1_fu_376.grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252.sparsemux_33_4_32_1_1_U23", "Parent" : "11"},
	{"ID" : "13", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_sha256_compress_words_1_fu_376.grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252.flow_control_loop_pipe_sequential_init_U", "Parent" : "11"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_sha256_compress_words_1_fu_376.grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304", "Parent" : "10", "Child" : ["15", "16", "17", "18", "19", "20"],
		"CDFG" : "sha256_compress_words_1_Pipeline_SHA256_ROUNDS",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "67", "EstimateLatencyMax" : "67",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "w_15_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_14_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_13_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_12_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_11_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_10_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_9_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_8_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_7_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_6_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_5_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_4_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_3_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_2_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_1_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "a_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "b_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "c_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "d_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "e_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "f_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "g_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "h_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "K", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "SHA256_ROUNDS", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "15", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_sha256_compress_words_1_fu_376.grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304.K_U", "Parent" : "14"},
	{"ID" : "16", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_sha256_compress_words_1_fu_376.grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304.sparsemux_33_4_32_1_1_U57", "Parent" : "14"},
	{"ID" : "17", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_sha256_compress_words_1_fu_376.grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304.sparsemux_33_4_32_1_1_x_U58", "Parent" : "14"},
	{"ID" : "18", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_sha256_compress_words_1_fu_376.grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304.sparsemux_33_4_32_1_1_x_U59", "Parent" : "14"},
	{"ID" : "19", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_sha256_compress_words_1_fu_376.grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304.sparsemux_33_4_32_1_1_x_U60", "Parent" : "14"},
	{"ID" : "20", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_sha256_compress_words_1_fu_376.grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304.flow_control_loop_pipe_sequential_init_U", "Parent" : "14"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_sha256d_from_midstate_fu_398", "Parent" : "0", "Child" : ["22"],
		"CDFG" : "sha256d_from_midstate",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "199", "EstimateLatencyMax" : "199",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "midstate_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "midstate_read_15", "Type" : "None", "Direction" : "I"},
			{"Name" : "midstate_read_16", "Type" : "None", "Direction" : "I"},
			{"Name" : "midstate_read_17", "Type" : "None", "Direction" : "I"},
			{"Name" : "midstate_read_18", "Type" : "None", "Direction" : "I"},
			{"Name" : "midstate_read_19", "Type" : "None", "Direction" : "I"},
			{"Name" : "midstate_read_20", "Type" : "None", "Direction" : "I"},
			{"Name" : "midstate_read_21", "Type" : "None", "Direction" : "I"},
			{"Name" : "header_tail", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "out_r", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "K", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "22", "SubInstance" : "grp_sha256_compress_words_fu_526", "Port" : "K", "Inst_start_state" : "4", "Inst_end_state" : "5"}]}]},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_sha256d_from_midstate_fu_398.grp_sha256_compress_words_fu_526", "Parent" : "21", "Child" : ["23", "26"],
		"CDFG" : "sha256_compress_words",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "90", "EstimateLatencyMax" : "90",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "state_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_read_30", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_read_31", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_read_32", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_read_33", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_read_34", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_read_35", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_read_36", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_read_38", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_read_39", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_read_40", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_read_41", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_read_42", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_read_43", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_read_44", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_read_45", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_read_46", "Type" : "None", "Direction" : "I"},
			{"Name" : "K", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "26", "SubInstance" : "grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291", "Port" : "K", "Inst_start_state" : "3", "Inst_end_state" : "4"}]}]},
	{"ID" : "23", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_sha256d_from_midstate_fu_398.grp_sha256_compress_words_fu_526.grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252", "Parent" : "22", "Child" : ["24", "25"],
		"CDFG" : "sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "18", "EstimateLatencyMax" : "18",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "block_words_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_read_10", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_read_11", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_read_12", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_read_13", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_read_14", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_read_15", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_read_16", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_read_17", "Type" : "None", "Direction" : "I"},
			{"Name" : "block_words_read_18", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_80_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_79_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_78_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_77_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_76_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_75_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_74_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_73_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_72_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_71_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_70_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_69_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_68_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_67_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_66_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "LOAD_INITIAL_WORDS", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state1", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state1_blk", "QuitState" : "ap_ST_fsm_state1", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state1_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "24", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_sha256d_from_midstate_fu_398.grp_sha256_compress_words_fu_526.grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252.sparsemux_33_4_32_1_1_U105", "Parent" : "23"},
	{"ID" : "25", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_sha256d_from_midstate_fu_398.grp_sha256_compress_words_fu_526.grp_sha256_compress_words_Pipeline_LOAD_INITIAL_WORDS_fu_252.flow_control_loop_pipe_sequential_init_U", "Parent" : "23"},
	{"ID" : "26", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_sha256d_from_midstate_fu_398.grp_sha256_compress_words_fu_526.grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291", "Parent" : "22", "Child" : ["27", "28", "29", "30", "31", "32"],
		"CDFG" : "sha256_compress_words_Pipeline_SHA256_ROUNDS",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "67", "EstimateLatencyMax" : "67",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "w_80_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_79_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_78_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_77_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_76_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_75_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_74_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_73_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_72_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_71_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_70_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_69_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_68_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_67_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_66_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_read_8", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_read_9", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_read_10", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_read_11", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_read_12", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_read_13", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_read_14", "Type" : "None", "Direction" : "I"},
			{"Name" : "a_4_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "b_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "c_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "d_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "e_4_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "f_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "g_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "h_01_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "K", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "SHA256_ROUNDS", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "27", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_sha256d_from_midstate_fu_398.grp_sha256_compress_words_fu_526.grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291.K_U", "Parent" : "26"},
	{"ID" : "28", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_sha256d_from_midstate_fu_398.grp_sha256_compress_words_fu_526.grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291.sparsemux_33_4_32_1_1_U132", "Parent" : "26"},
	{"ID" : "29", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_sha256d_from_midstate_fu_398.grp_sha256_compress_words_fu_526.grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291.sparsemux_33_4_32_1_1_x_U133", "Parent" : "26"},
	{"ID" : "30", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_sha256d_from_midstate_fu_398.grp_sha256_compress_words_fu_526.grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291.sparsemux_33_4_32_1_1_x_U134", "Parent" : "26"},
	{"ID" : "31", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_sha256d_from_midstate_fu_398.grp_sha256_compress_words_fu_526.grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291.sparsemux_33_4_32_1_1_x_U135", "Parent" : "26"},
	{"ID" : "32", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_sha256d_from_midstate_fu_398.grp_sha256_compress_words_fu_526.grp_sha256_compress_words_Pipeline_SHA256_ROUNDS_fu_291.flow_control_loop_pipe_sequential_init_U", "Parent" : "26"},
	{"ID" : "33", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_mine_Pipeline_COMPARE_HASH_fu_414", "Parent" : "0", "Child" : ["34"],
		"CDFG" : "mine_Pipeline_COMPARE_HASH",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "3", "EstimateLatencyMax" : "67",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "h", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "tgt", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "retval_1_i35_ce_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "cleanup_dest_slot_1_i_ce_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "COMPARE_HASH", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state2", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state2_blk", "QuitState" : "ap_ST_fsm_state2", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state2_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mine_Pipeline_COMPARE_HASH_fu_414.flow_control_loop_pipe_sequential_init_U", "Parent" : "33"},
	{"ID" : "35", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "36", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_m_axi_U", "Parent" : "0"},
	{"ID" : "37", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_m_axi_U", "Parent" : "0"},
	{"ID" : "38", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem2_m_axi_U", "Parent" : "0"}]}
