-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mine_mine_Pipeline_COMPARE_HASH is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    h_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    h_ce0 : OUT STD_LOGIC;
    h_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    tgt_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    tgt_ce0 : OUT STD_LOGIC;
    tgt_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    retval_1_i35_ce_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    retval_1_i35_ce_out_ap_vld : OUT STD_LOGIC;
    cleanup_dest_slot_1_i_ce_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    cleanup_dest_slot_1_i_ce_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of mine_mine_Pipeline_COMPARE_HASH is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln424_fu_213_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln420_fu_207_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln410_reg_230 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal retval_1_i35_ce_reg_100 : STD_LOGIC_VECTOR (0 downto 0);
    signal cleanup_dest_slot_1_i_ce_reg_116 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln410_fu_140_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal add_ln410_fu_146_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln410_reg_234 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln417_fu_182_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln417_reg_249 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln411_fu_162_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln417_fu_177_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_56 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_5 : STD_LOGIC_VECTOR (5 downto 0);
    signal h_ce0_local : STD_LOGIC;
    signal tgt_ce0_local : STD_LOGIC;
    signal trunc_ln410_fu_152_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal xor_ln411_fu_156_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal word_index_fu_167_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal shl_ln_fu_186_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln417_1_fu_193_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln417_fu_197_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tb_fu_203_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component mine_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component mine_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    cleanup_dest_slot_1_i_ce_reg_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((icmp_ln410_reg_230 = ap_const_lv1_0) and (icmp_ln420_fu_207_p2 = ap_const_lv1_0) and (icmp_ln424_fu_213_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((icmp_ln410_reg_230 = ap_const_lv1_0) and (icmp_ln420_fu_207_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
                cleanup_dest_slot_1_i_ce_reg_116 <= ap_const_lv1_1;
            elsif (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (icmp_ln410_fu_140_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                cleanup_dest_slot_1_i_ce_reg_116 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    i_fu_56_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_fu_56 <= ap_const_lv6_0;
            elsif (((icmp_ln410_reg_230 = ap_const_lv1_0) and (icmp_ln420_fu_207_p2 = ap_const_lv1_0) and (icmp_ln424_fu_213_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_fu_56 <= add_ln410_reg_234;
            end if; 
        end if;
    end process;

    retval_1_i35_ce_reg_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln410_reg_230 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                if (((icmp_ln420_fu_207_p2 = ap_const_lv1_0) and (icmp_ln424_fu_213_p2 = ap_const_lv1_1))) then 
                    retval_1_i35_ce_reg_100 <= ap_const_lv1_0;
                elsif ((icmp_ln420_fu_207_p2 = ap_const_lv1_1)) then 
                    retval_1_i35_ce_reg_100 <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                add_ln410_reg_234 <= add_ln410_fu_146_p2;
                icmp_ln410_reg_230 <= icmp_ln410_fu_140_p2;
                trunc_ln417_reg_249 <= trunc_ln417_fu_182_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_block_state1_pp0_stage0_iter0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln410_fu_146_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_5) + unsigned(ap_const_lv6_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_CS_fsm_state2, icmp_ln424_fu_213_p2, icmp_ln420_fu_207_p2, icmp_ln410_reg_230)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and ((icmp_ln410_reg_230 = ap_const_lv1_1) or ((icmp_ln420_fu_207_p2 = ap_const_lv1_1) or (icmp_ln424_fu_213_p2 = ap_const_lv1_1))))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_state2, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_5_assign_proc : process(ap_CS_fsm_state1, i_fu_56, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_i_5 <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_i_5 <= i_fu_56;
        end if; 
    end process;

    cleanup_dest_slot_1_i_ce_out <= cleanup_dest_slot_1_i_ce_reg_116;

    cleanup_dest_slot_1_i_ce_out_ap_vld_assign_proc : process(ap_CS_fsm_state2, icmp_ln424_fu_213_p2, icmp_ln420_fu_207_p2, icmp_ln410_reg_230, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and ((icmp_ln410_reg_230 = ap_const_lv1_1) or ((icmp_ln420_fu_207_p2 = ap_const_lv1_1) or (icmp_ln424_fu_213_p2 = ap_const_lv1_1))))) then 
            cleanup_dest_slot_1_i_ce_out_ap_vld <= ap_const_logic_1;
        else 
            cleanup_dest_slot_1_i_ce_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    h_address0 <= zext_ln411_fu_162_p1(5 - 1 downto 0);
    h_ce0 <= h_ce0_local;

    h_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            h_ce0_local <= ap_const_logic_1;
        else 
            h_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln410_fu_140_p2 <= "1" when (ap_sig_allocacmp_i_5 = ap_const_lv6_20) else "0";
    icmp_ln420_fu_207_p2 <= "1" when (unsigned(h_q0) < unsigned(tb_fu_203_p1)) else "0";
    icmp_ln424_fu_213_p2 <= "1" when (unsigned(h_q0) > unsigned(tb_fu_203_p1)) else "0";
    lshr_ln417_fu_197_p2 <= std_logic_vector(shift_right(unsigned(tgt_q0),to_integer(unsigned('0' & zext_ln417_1_fu_193_p1(31-1 downto 0)))));
    retval_1_i35_ce_out <= retval_1_i35_ce_reg_100;

    retval_1_i35_ce_out_ap_vld_assign_proc : process(ap_CS_fsm_state2, icmp_ln424_fu_213_p2, icmp_ln420_fu_207_p2, icmp_ln410_reg_230, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and ((icmp_ln410_reg_230 = ap_const_lv1_1) or ((icmp_ln420_fu_207_p2 = ap_const_lv1_1) or (icmp_ln424_fu_213_p2 = ap_const_lv1_1))))) then 
            retval_1_i35_ce_out_ap_vld <= ap_const_logic_1;
        else 
            retval_1_i35_ce_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    shl_ln_fu_186_p3 <= (trunc_ln417_reg_249 & ap_const_lv3_0);
    tb_fu_203_p1 <= lshr_ln417_fu_197_p2(8 - 1 downto 0);
    tgt_address0 <= zext_ln417_fu_177_p1(3 - 1 downto 0);
    tgt_ce0 <= tgt_ce0_local;

    tgt_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            tgt_ce0_local <= ap_const_logic_1;
        else 
            tgt_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln410_fu_152_p1 <= ap_sig_allocacmp_i_5(5 - 1 downto 0);
    trunc_ln417_fu_182_p1 <= ap_sig_allocacmp_i_5(2 - 1 downto 0);
    word_index_fu_167_p4 <= ap_sig_allocacmp_i_5(4 downto 2);
    xor_ln411_fu_156_p2 <= (trunc_ln410_fu_152_p1 xor ap_const_lv5_1F);
    zext_ln411_fu_162_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xor_ln411_fu_156_p2),64));
    zext_ln417_1_fu_193_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_186_p3),32));
    zext_ln417_fu_177_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(word_index_fu_167_p4),64));
end behav;
