-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mine_sha256_compress_words_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    block_words_0_val : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_1_val : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_2_val : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_3_val : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_4_val : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_5_val : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_6_val : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_7_val : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_8_val : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_9_val : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_10_val : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_11_val : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_12_val : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_13_val : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_14_val : IN STD_LOGIC_VECTOR (31 downto 0);
    block_words_15_val : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of mine_sha256_compress_words_1 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6A09E667 : STD_LOGIC_VECTOR (31 downto 0) := "01101010000010011110011001100111";
    constant ap_const_lv32_BB67AE85 : STD_LOGIC_VECTOR (31 downto 0) := "10111011011001111010111010000101";
    constant ap_const_lv32_3C6EF372 : STD_LOGIC_VECTOR (31 downto 0) := "00111100011011101111001101110010";
    constant ap_const_lv32_A54FF53A : STD_LOGIC_VECTOR (31 downto 0) := "10100101010011111111010100111010";
    constant ap_const_lv32_510E527F : STD_LOGIC_VECTOR (31 downto 0) := "01010001000011100101001001111111";
    constant ap_const_lv32_9B05688C : STD_LOGIC_VECTOR (31 downto 0) := "10011011000001010110100010001100";
    constant ap_const_lv32_1F83D9AB : STD_LOGIC_VECTOR (31 downto 0) := "00011111100000111101100110101011";
    constant ap_const_lv32_5BE0CD19 : STD_LOGIC_VECTOR (31 downto 0) := "01011011111000001100110100011001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_done : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_idle : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_ready : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_15_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_15_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_14_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_14_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_13_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_13_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_12_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_12_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_11_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_11_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_10_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_10_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_9_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_9_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_8_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_8_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_7_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_7_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_6_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_6_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_5_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_5_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_4_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_4_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_3_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_2_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_2_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_1_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_start : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_done : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_idle : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_ready : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_a_2_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_a_2_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_b_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_b_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_c_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_c_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_d_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_d_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_e_2_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_e_2_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_f_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_f_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_g_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_g_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_h_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_h_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal add_ln198_fu_422_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln199_fu_428_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln200_fu_434_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln201_fu_440_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln202_fu_446_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln203_fu_452_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln204_fu_458_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln205_fu_464_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component mine_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        block_words_0_val : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_1_val : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_2_val : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_3_val : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_4_val : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_5_val : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_6_val : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_7_val : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_8_val : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_9_val : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_10_val : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_11_val : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_12_val : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_13_val : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_14_val : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_15_val : IN STD_LOGIC_VECTOR (31 downto 0);
        w_15_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_15_out_ap_vld : OUT STD_LOGIC;
        w_14_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_14_out_ap_vld : OUT STD_LOGIC;
        w_13_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_13_out_ap_vld : OUT STD_LOGIC;
        w_12_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_12_out_ap_vld : OUT STD_LOGIC;
        w_11_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_11_out_ap_vld : OUT STD_LOGIC;
        w_10_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_10_out_ap_vld : OUT STD_LOGIC;
        w_9_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_9_out_ap_vld : OUT STD_LOGIC;
        w_8_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_8_out_ap_vld : OUT STD_LOGIC;
        w_7_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_7_out_ap_vld : OUT STD_LOGIC;
        w_6_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_6_out_ap_vld : OUT STD_LOGIC;
        w_5_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_5_out_ap_vld : OUT STD_LOGIC;
        w_4_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_4_out_ap_vld : OUT STD_LOGIC;
        w_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_3_out_ap_vld : OUT STD_LOGIC;
        w_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_2_out_ap_vld : OUT STD_LOGIC;
        w_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_1_out_ap_vld : OUT STD_LOGIC;
        w_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_out_ap_vld : OUT STD_LOGIC );
    end component;


    component mine_sha256_compress_words_1_Pipeline_SHA256_ROUNDS IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        w_15_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_14_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_13_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_12_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_11_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_10_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_9_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_8_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_7_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_6_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_5_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_4_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_2_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_1_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        a_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        a_2_out_ap_vld : OUT STD_LOGIC;
        b_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        b_out_ap_vld : OUT STD_LOGIC;
        c_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        c_out_ap_vld : OUT STD_LOGIC;
        d_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        d_out_ap_vld : OUT STD_LOGIC;
        e_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        e_2_out_ap_vld : OUT STD_LOGIC;
        f_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        f_out_ap_vld : OUT STD_LOGIC;
        g_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        g_out_ap_vld : OUT STD_LOGIC;
        h_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        h_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252 : component mine_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start,
        ap_done => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_done,
        ap_idle => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_idle,
        ap_ready => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_ready,
        block_words_0_val => block_words_0_val,
        block_words_1_val => block_words_1_val,
        block_words_2_val => block_words_2_val,
        block_words_3_val => block_words_3_val,
        block_words_4_val => block_words_4_val,
        block_words_5_val => block_words_5_val,
        block_words_6_val => block_words_6_val,
        block_words_7_val => block_words_7_val,
        block_words_8_val => block_words_8_val,
        block_words_9_val => block_words_9_val,
        block_words_10_val => block_words_10_val,
        block_words_11_val => block_words_11_val,
        block_words_12_val => block_words_12_val,
        block_words_13_val => block_words_13_val,
        block_words_14_val => block_words_14_val,
        block_words_15_val => block_words_15_val,
        w_15_out => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_15_out,
        w_15_out_ap_vld => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_15_out_ap_vld,
        w_14_out => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_14_out,
        w_14_out_ap_vld => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_14_out_ap_vld,
        w_13_out => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_13_out,
        w_13_out_ap_vld => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_13_out_ap_vld,
        w_12_out => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_12_out,
        w_12_out_ap_vld => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_12_out_ap_vld,
        w_11_out => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_11_out,
        w_11_out_ap_vld => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_11_out_ap_vld,
        w_10_out => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_10_out,
        w_10_out_ap_vld => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_10_out_ap_vld,
        w_9_out => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_9_out,
        w_9_out_ap_vld => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_9_out_ap_vld,
        w_8_out => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_8_out,
        w_8_out_ap_vld => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_8_out_ap_vld,
        w_7_out => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_7_out,
        w_7_out_ap_vld => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_7_out_ap_vld,
        w_6_out => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_6_out,
        w_6_out_ap_vld => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_6_out_ap_vld,
        w_5_out => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_5_out,
        w_5_out_ap_vld => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_5_out_ap_vld,
        w_4_out => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_4_out,
        w_4_out_ap_vld => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_4_out_ap_vld,
        w_3_out => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_3_out,
        w_3_out_ap_vld => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_3_out_ap_vld,
        w_2_out => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_2_out,
        w_2_out_ap_vld => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_2_out_ap_vld,
        w_1_out => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_1_out,
        w_1_out_ap_vld => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_1_out_ap_vld,
        w_out => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_out,
        w_out_ap_vld => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_out_ap_vld);

    grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304 : component mine_sha256_compress_words_1_Pipeline_SHA256_ROUNDS
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_start,
        ap_done => grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_done,
        ap_idle => grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_idle,
        ap_ready => grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_ready,
        w_15_reload => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_15_out,
        w_14_reload => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_14_out,
        w_13_reload => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_13_out,
        w_12_reload => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_12_out,
        w_11_reload => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_11_out,
        w_10_reload => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_10_out,
        w_9_reload => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_9_out,
        w_8_reload => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_8_out,
        w_7_reload => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_7_out,
        w_6_reload => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_6_out,
        w_5_reload => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_5_out,
        w_4_reload => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_4_out,
        w_3_reload => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_3_out,
        w_2_reload => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_2_out,
        w_1_reload => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_1_out,
        w_reload => grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_w_out,
        a_2_out => grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_a_2_out,
        a_2_out_ap_vld => grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_a_2_out_ap_vld,
        b_out => grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_b_out,
        b_out_ap_vld => grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_b_out_ap_vld,
        c_out => grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_c_out,
        c_out_ap_vld => grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_c_out_ap_vld,
        d_out => grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_d_out,
        d_out_ap_vld => grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_d_out_ap_vld,
        e_2_out => grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_e_2_out,
        e_2_out_ap_vld => grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_e_2_out_ap_vld,
        f_out => grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_f_out,
        f_out_ap_vld => grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_f_out_ap_vld,
        g_out => grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_g_out,
        g_out_ap_vld => grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_g_out_ap_vld,
        h_out => grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_h_out,
        h_out_ap_vld => grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_h_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_ready = ap_const_logic_1)) then 
                    grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_ready = ap_const_logic_1)) then 
                    grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_done, grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln198_fu_422_p2 <= std_logic_vector(unsigned(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_a_2_out) + unsigned(ap_const_lv32_6A09E667));
    add_ln199_fu_428_p2 <= std_logic_vector(unsigned(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_b_out) + unsigned(ap_const_lv32_BB67AE85));
    add_ln200_fu_434_p2 <= std_logic_vector(unsigned(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_c_out) + unsigned(ap_const_lv32_3C6EF372));
    add_ln201_fu_440_p2 <= std_logic_vector(unsigned(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_d_out) + unsigned(ap_const_lv32_A54FF53A));
    add_ln202_fu_446_p2 <= std_logic_vector(unsigned(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_e_2_out) + unsigned(ap_const_lv32_510E527F));
    add_ln203_fu_452_p2 <= std_logic_vector(unsigned(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_f_out) + unsigned(ap_const_lv32_9B05688C));
    add_ln204_fu_458_p2 <= std_logic_vector(unsigned(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_g_out) + unsigned(ap_const_lv32_1F83D9AB));
    add_ln205_fu_464_p2 <= std_logic_vector(unsigned(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_h_out) + unsigned(ap_const_lv32_5BE0CD19));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_done)
    begin
        if ((grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_done)
    begin
        if ((grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= add_ln198_fu_422_p2;
    ap_return_1 <= add_ln199_fu_428_p2;
    ap_return_2 <= add_ln200_fu_434_p2;
    ap_return_3 <= add_ln201_fu_440_p2;
    ap_return_4 <= add_ln202_fu_446_p2;
    ap_return_5 <= add_ln203_fu_452_p2;
    ap_return_6 <= add_ln204_fu_458_p2;
    ap_return_7 <= add_ln205_fu_464_p2;
    grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start <= grp_sha256_compress_words_1_Pipeline_LOAD_INITIAL_WORDS_fu_252_ap_start_reg;
    grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_start <= grp_sha256_compress_words_1_Pipeline_SHA256_ROUNDS_fu_304_ap_start_reg;
end behav;
