-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mine_sha256d_from_midstate is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    midstate_read : IN STD_LOGIC_VECTOR (31 downto 0);
    midstate_read_15 : IN STD_LOGIC_VECTOR (31 downto 0);
    midstate_read_16 : IN STD_LOGIC_VECTOR (31 downto 0);
    midstate_read_17 : IN STD_LOGIC_VECTOR (31 downto 0);
    midstate_read_18 : IN STD_LOGIC_VECTOR (31 downto 0);
    midstate_read_19 : IN STD_LOGIC_VECTOR (31 downto 0);
    midstate_read_20 : IN STD_LOGIC_VECTOR (31 downto 0);
    midstate_read_21 : IN STD_LOGIC_VECTOR (31 downto 0);
    header_tail_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    header_tail_ce0 : OUT STD_LOGIC;
    header_tail_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    header_tail_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    header_tail_ce1 : OUT STD_LOGIC;
    header_tail_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    out_r_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    out_r_ce0 : OUT STD_LOGIC;
    out_r_we0 : OUT STD_LOGIC;
    out_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    out_r_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    out_r_ce1 : OUT STD_LOGIC;
    out_r_we1 : OUT STD_LOGIC;
    out_r_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of mine_sha256d_from_midstate is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (19 downto 0) := "00000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (19 downto 0) := "00000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (19 downto 0) := "00000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (19 downto 0) := "00000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (19 downto 0) := "00000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (19 downto 0) := "00000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (19 downto 0) := "00001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (19 downto 0) := "00010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (19 downto 0) := "00100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (19 downto 0) := "01000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (19 downto 0) := "10000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6A09E667 : STD_LOGIC_VECTOR (31 downto 0) := "01101010000010011110011001100111";
    constant ap_const_lv32_BB67AE85 : STD_LOGIC_VECTOR (31 downto 0) := "10111011011001111010111010000101";
    constant ap_const_lv32_3C6EF372 : STD_LOGIC_VECTOR (31 downto 0) := "00111100011011101111001101110010";
    constant ap_const_lv32_A54FF53A : STD_LOGIC_VECTOR (31 downto 0) := "10100101010011111111010100111010";
    constant ap_const_lv32_510E527F : STD_LOGIC_VECTOR (31 downto 0) := "01010001000011100101001001111111";
    constant ap_const_lv32_9B05688C : STD_LOGIC_VECTOR (31 downto 0) := "10011011000001010110100010001100";
    constant ap_const_lv32_1F83D9AB : STD_LOGIC_VECTOR (31 downto 0) := "00011111100000111101100110101011";
    constant ap_const_lv32_5BE0CD19 : STD_LOGIC_VECTOR (31 downto 0) := "01011011111000001100110100011001";
    constant ap_const_lv32_80000000 : STD_LOGIC_VECTOR (31 downto 0) := "10000000000000000000000000000000";
    constant ap_const_lv32_280 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010000000";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv64_10 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010000";
    constant ap_const_lv64_11 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010001";
    constant ap_const_lv64_12 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010010";
    constant ap_const_lv64_13 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010011";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv64_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv64_5 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000101";
    constant ap_const_lv64_6 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv64_7 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000111";
    constant ap_const_lv64_8 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv64_9 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001001";
    constant ap_const_lv64_A : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001010";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv64_B : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001011";
    constant ap_const_lv64_C : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001100";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv64_D : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001101";
    constant ap_const_lv64_E : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001110";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv64_F : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv64_14 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010100";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv64_15 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010101";
    constant ap_const_lv64_16 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv64_17 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010111";
    constant ap_const_lv64_18 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000011000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv64_19 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000011001";
    constant ap_const_lv64_1A : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000011010";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv64_1B : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000011011";
    constant ap_const_lv64_1C : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000011100";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv64_1D : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000011101";
    constant ap_const_lv64_1E : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000011110";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv64_1F : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000011111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal empty_fu_728_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_reg_1072 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_fu_628_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_3_reg_1077 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_638_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_1_reg_1082 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_648_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_2_reg_1087 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_40_fu_732_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_40_reg_1092 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_658_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_4_reg_1097 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_668_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_5_reg_1102 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_678_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_6_reg_1107 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal block_words_fu_736_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal block_words_reg_1162 : STD_LOGIC_VECTOR (31 downto 0);
    signal block_words_1_fu_745_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal block_words_1_reg_1167 : STD_LOGIC_VECTOR (31 downto 0);
    signal block_words_2_fu_758_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal block_words_2_reg_1172 : STD_LOGIC_VECTOR (31 downto 0);
    signal block_words_3_fu_775_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal block_words_3_reg_1177 : STD_LOGIC_VECTOR (31 downto 0);
    signal s_16_reg_1182 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal s_17_reg_1187 : STD_LOGIC_VECTOR (31 downto 0);
    signal s_18_reg_1192 : STD_LOGIC_VECTOR (31 downto 0);
    signal s_19_reg_1197 : STD_LOGIC_VECTOR (31 downto 0);
    signal s_20_reg_1202 : STD_LOGIC_VECTOR (31 downto 0);
    signal s_21_reg_1207 : STD_LOGIC_VECTOR (31 downto 0);
    signal s_22_reg_1212 : STD_LOGIC_VECTOR (31 downto 0);
    signal s_23_reg_1217 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln2_reg_1222 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal trunc_ln323_fu_820_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln323_reg_1227 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln320_1_reg_1232 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln321_1_reg_1237 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln322_1_reg_1242 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln323_1_fu_854_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln323_1_reg_1247 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln320_2_reg_1252 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln321_2_reg_1257 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln322_2_reg_1262 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln323_2_fu_888_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln323_2_reg_1267 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln320_3_reg_1272 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln321_3_reg_1277 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln322_3_reg_1282 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln323_3_fu_922_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln323_3_reg_1287 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln320_4_reg_1292 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln321_4_reg_1297 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln322_4_reg_1302 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln323_4_fu_956_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln323_4_reg_1307 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln320_5_reg_1312 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln321_5_reg_1317 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln322_5_reg_1322 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln323_5_fu_990_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln323_5_reg_1327 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln320_6_reg_1332 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln321_6_reg_1337 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln322_6_reg_1342 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln323_6_fu_1024_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln323_6_reg_1347 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln320_7_reg_1352 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln321_7_reg_1357 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln322_7_reg_1362 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln323_7_fu_1058_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln323_7_reg_1367 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_sha256_compress_words_fu_526_ap_start : STD_LOGIC;
    signal grp_sha256_compress_words_fu_526_ap_done : STD_LOGIC;
    signal grp_sha256_compress_words_fu_526_ap_idle : STD_LOGIC;
    signal grp_sha256_compress_words_fu_526_ap_ready : STD_LOGIC;
    signal grp_sha256_compress_words_fu_526_state_read : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_fu_526_state_read_30 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_fu_526_state_read_31 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_fu_526_state_read_32 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_fu_526_state_read_33 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_fu_526_state_read_34 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_fu_526_state_read_35 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_fu_526_state_read_36 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_fu_526_block_words_read : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_fu_526_block_words_read_38 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_fu_526_block_words_read_39 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_fu_526_block_words_read_40 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_fu_526_block_words_read_41 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_fu_526_block_words_read_42 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_fu_526_block_words_read_43 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_fu_526_block_words_read_44 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_fu_526_block_words_read_45 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_fu_526_block_words_read_46 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_fu_526_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_fu_526_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_fu_526_ap_return_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_fu_526_ap_return_3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_fu_526_ap_return_4 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_fu_526_ap_return_5 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_fu_526_ap_return_6 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_fu_526_ap_return_7 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_words_fu_526_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal header_tail_ce1_local : STD_LOGIC;
    signal header_tail_address1_local : STD_LOGIC_VECTOR (4 downto 0);
    signal header_tail_ce0_local : STD_LOGIC;
    signal header_tail_address0_local : STD_LOGIC_VECTOR (4 downto 0);
    signal out_r_we1_local : STD_LOGIC;
    signal out_r_d1_local : STD_LOGIC_VECTOR (7 downto 0);
    signal out_r_ce1_local : STD_LOGIC;
    signal out_r_address1_local : STD_LOGIC_VECTOR (4 downto 0);
    signal out_r_we0_local : STD_LOGIC;
    signal out_r_d0_local : STD_LOGIC_VECTOR (7 downto 0);
    signal out_r_ce0_local : STD_LOGIC;
    signal out_r_address0_local : STD_LOGIC_VECTOR (4 downto 0);
    signal empty_41_fu_754_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_42_fu_771_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component mine_sha256_compress_words IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        state_read : IN STD_LOGIC_VECTOR (31 downto 0);
        state_read_30 : IN STD_LOGIC_VECTOR (31 downto 0);
        state_read_31 : IN STD_LOGIC_VECTOR (31 downto 0);
        state_read_32 : IN STD_LOGIC_VECTOR (31 downto 0);
        state_read_33 : IN STD_LOGIC_VECTOR (31 downto 0);
        state_read_34 : IN STD_LOGIC_VECTOR (31 downto 0);
        state_read_35 : IN STD_LOGIC_VECTOR (31 downto 0);
        state_read_36 : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_read : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_read_38 : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_read_39 : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_read_40 : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_read_41 : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_read_42 : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_read_43 : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_read_44 : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_read_45 : IN STD_LOGIC_VECTOR (31 downto 0);
        block_words_read_46 : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_sha256_compress_words_fu_526 : component mine_sha256_compress_words
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_sha256_compress_words_fu_526_ap_start,
        ap_done => grp_sha256_compress_words_fu_526_ap_done,
        ap_idle => grp_sha256_compress_words_fu_526_ap_idle,
        ap_ready => grp_sha256_compress_words_fu_526_ap_ready,
        state_read => grp_sha256_compress_words_fu_526_state_read,
        state_read_30 => grp_sha256_compress_words_fu_526_state_read_30,
        state_read_31 => grp_sha256_compress_words_fu_526_state_read_31,
        state_read_32 => grp_sha256_compress_words_fu_526_state_read_32,
        state_read_33 => grp_sha256_compress_words_fu_526_state_read_33,
        state_read_34 => grp_sha256_compress_words_fu_526_state_read_34,
        state_read_35 => grp_sha256_compress_words_fu_526_state_read_35,
        state_read_36 => grp_sha256_compress_words_fu_526_state_read_36,
        block_words_read => grp_sha256_compress_words_fu_526_block_words_read,
        block_words_read_38 => grp_sha256_compress_words_fu_526_block_words_read_38,
        block_words_read_39 => grp_sha256_compress_words_fu_526_block_words_read_39,
        block_words_read_40 => grp_sha256_compress_words_fu_526_block_words_read_40,
        block_words_read_41 => grp_sha256_compress_words_fu_526_block_words_read_41,
        block_words_read_42 => grp_sha256_compress_words_fu_526_block_words_read_42,
        block_words_read_43 => grp_sha256_compress_words_fu_526_block_words_read_43,
        block_words_read_44 => grp_sha256_compress_words_fu_526_block_words_read_44,
        block_words_read_45 => grp_sha256_compress_words_fu_526_block_words_read_45,
        block_words_read_46 => grp_sha256_compress_words_fu_526_block_words_read_46,
        ap_return_0 => grp_sha256_compress_words_fu_526_ap_return_0,
        ap_return_1 => grp_sha256_compress_words_fu_526_ap_return_1,
        ap_return_2 => grp_sha256_compress_words_fu_526_ap_return_2,
        ap_return_3 => grp_sha256_compress_words_fu_526_ap_return_3,
        ap_return_4 => grp_sha256_compress_words_fu_526_ap_return_4,
        ap_return_5 => grp_sha256_compress_words_fu_526_ap_return_5,
        ap_return_6 => grp_sha256_compress_words_fu_526_ap_return_6,
        ap_return_7 => grp_sha256_compress_words_fu_526_ap_return_7);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_sha256_compress_words_fu_526_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_sha256_compress_words_fu_526_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((grp_sha256_compress_words_fu_526_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
                    grp_sha256_compress_words_fu_526_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sha256_compress_words_fu_526_ap_ready = ap_const_logic_1)) then 
                    grp_sha256_compress_words_fu_526_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                block_words_1_reg_1167 <= block_words_1_fu_745_p5;
                block_words_2_reg_1172 <= block_words_2_fu_758_p5;
                block_words_3_reg_1177 <= block_words_3_fu_775_p5;
                block_words_reg_1162 <= block_words_fu_736_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                empty_40_reg_1092 <= empty_40_fu_732_p1;
                empty_reg_1072 <= empty_fu_728_p1;
                p_1_reg_1082 <= header_tail_q1(15 downto 8);
                p_2_reg_1087 <= header_tail_q1(23 downto 16);
                p_3_reg_1077 <= header_tail_q1(31 downto 24);
                p_4_reg_1097 <= header_tail_q0(31 downto 24);
                p_5_reg_1102 <= header_tail_q0(15 downto 8);
                p_6_reg_1107 <= header_tail_q0(23 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                s_16_reg_1182 <= grp_sha256_compress_words_fu_526_ap_return_0;
                s_17_reg_1187 <= grp_sha256_compress_words_fu_526_ap_return_1;
                s_18_reg_1192 <= grp_sha256_compress_words_fu_526_ap_return_2;
                s_19_reg_1197 <= grp_sha256_compress_words_fu_526_ap_return_3;
                s_20_reg_1202 <= grp_sha256_compress_words_fu_526_ap_return_4;
                s_21_reg_1207 <= grp_sha256_compress_words_fu_526_ap_return_5;
                s_22_reg_1212 <= grp_sha256_compress_words_fu_526_ap_return_6;
                s_23_reg_1217 <= grp_sha256_compress_words_fu_526_ap_return_7;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                trunc_ln2_reg_1222 <= grp_sha256_compress_words_fu_526_ap_return_0(15 downto 8);
                trunc_ln320_1_reg_1232 <= grp_sha256_compress_words_fu_526_ap_return_1(31 downto 24);
                trunc_ln320_2_reg_1252 <= grp_sha256_compress_words_fu_526_ap_return_2(31 downto 24);
                trunc_ln320_3_reg_1272 <= grp_sha256_compress_words_fu_526_ap_return_3(31 downto 24);
                trunc_ln320_4_reg_1292 <= grp_sha256_compress_words_fu_526_ap_return_4(31 downto 24);
                trunc_ln320_5_reg_1312 <= grp_sha256_compress_words_fu_526_ap_return_5(31 downto 24);
                trunc_ln320_6_reg_1332 <= grp_sha256_compress_words_fu_526_ap_return_6(31 downto 24);
                trunc_ln320_7_reg_1352 <= grp_sha256_compress_words_fu_526_ap_return_7(31 downto 24);
                trunc_ln321_1_reg_1237 <= grp_sha256_compress_words_fu_526_ap_return_1(23 downto 16);
                trunc_ln321_2_reg_1257 <= grp_sha256_compress_words_fu_526_ap_return_2(23 downto 16);
                trunc_ln321_3_reg_1277 <= grp_sha256_compress_words_fu_526_ap_return_3(23 downto 16);
                trunc_ln321_4_reg_1297 <= grp_sha256_compress_words_fu_526_ap_return_4(23 downto 16);
                trunc_ln321_5_reg_1317 <= grp_sha256_compress_words_fu_526_ap_return_5(23 downto 16);
                trunc_ln321_6_reg_1337 <= grp_sha256_compress_words_fu_526_ap_return_6(23 downto 16);
                trunc_ln321_7_reg_1357 <= grp_sha256_compress_words_fu_526_ap_return_7(23 downto 16);
                trunc_ln322_1_reg_1242 <= grp_sha256_compress_words_fu_526_ap_return_1(15 downto 8);
                trunc_ln322_2_reg_1262 <= grp_sha256_compress_words_fu_526_ap_return_2(15 downto 8);
                trunc_ln322_3_reg_1282 <= grp_sha256_compress_words_fu_526_ap_return_3(15 downto 8);
                trunc_ln322_4_reg_1302 <= grp_sha256_compress_words_fu_526_ap_return_4(15 downto 8);
                trunc_ln322_5_reg_1322 <= grp_sha256_compress_words_fu_526_ap_return_5(15 downto 8);
                trunc_ln322_6_reg_1342 <= grp_sha256_compress_words_fu_526_ap_return_6(15 downto 8);
                trunc_ln322_7_reg_1362 <= grp_sha256_compress_words_fu_526_ap_return_7(15 downto 8);
                trunc_ln323_1_reg_1247 <= trunc_ln323_1_fu_854_p1;
                trunc_ln323_2_reg_1267 <= trunc_ln323_2_fu_888_p1;
                trunc_ln323_3_reg_1287 <= trunc_ln323_3_fu_922_p1;
                trunc_ln323_4_reg_1307 <= trunc_ln323_4_fu_956_p1;
                trunc_ln323_5_reg_1327 <= trunc_ln323_5_fu_990_p1;
                trunc_ln323_6_reg_1347 <= trunc_ln323_6_fu_1024_p1;
                trunc_ln323_7_reg_1367 <= trunc_ln323_7_fu_1058_p1;
                trunc_ln323_reg_1227 <= trunc_ln323_fu_820_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state4, ap_CS_fsm_state5, grp_sha256_compress_words_fu_526_ap_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_sha256_compress_words_fu_526_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((grp_sha256_compress_words_fu_526_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_sha256_compress_words_fu_526_ap_done)
    begin
        if ((grp_sha256_compress_words_fu_526_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(grp_sha256_compress_words_fu_526_ap_done)
    begin
        if ((grp_sha256_compress_words_fu_526_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state20)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state20) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    block_words_1_fu_745_p5 <= (((empty_40_reg_1092 & p_5_reg_1102) & p_6_reg_1107) & p_4_reg_1097);
    block_words_2_fu_758_p5 <= (((empty_41_fu_754_p1 & grp_fu_638_p4) & grp_fu_648_p4) & grp_fu_628_p4);
    block_words_3_fu_775_p5 <= (((empty_42_fu_771_p1 & grp_fu_668_p4) & grp_fu_678_p4) & grp_fu_658_p4);
    block_words_fu_736_p5 <= (((empty_reg_1072 & p_1_reg_1082) & p_2_reg_1087) & p_3_reg_1077);
    empty_40_fu_732_p1 <= header_tail_q0(8 - 1 downto 0);
    empty_41_fu_754_p1 <= header_tail_q1(8 - 1 downto 0);
    empty_42_fu_771_p1 <= header_tail_q0(8 - 1 downto 0);
    empty_fu_728_p1 <= header_tail_q1(8 - 1 downto 0);
    grp_fu_628_p4 <= header_tail_q1(31 downto 24);
    grp_fu_638_p4 <= header_tail_q1(15 downto 8);
    grp_fu_648_p4 <= header_tail_q1(23 downto 16);
    grp_fu_658_p4 <= header_tail_q0(31 downto 24);
    grp_fu_668_p4 <= header_tail_q0(15 downto 8);
    grp_fu_678_p4 <= header_tail_q0(23 downto 16);
    grp_sha256_compress_words_fu_526_ap_start <= grp_sha256_compress_words_fu_526_ap_start_reg;

    grp_sha256_compress_words_fu_526_block_words_read_assign_proc : process(block_words_reg_1162, s_16_reg_1182, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_sha256_compress_words_fu_526_block_words_read <= s_16_reg_1182;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_sha256_compress_words_fu_526_block_words_read <= block_words_reg_1162;
        else 
            grp_sha256_compress_words_fu_526_block_words_read <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_sha256_compress_words_fu_526_block_words_read_38_assign_proc : process(block_words_1_reg_1167, ap_CS_fsm_state4, s_17_reg_1187, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_sha256_compress_words_fu_526_block_words_read_38 <= s_17_reg_1187;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_sha256_compress_words_fu_526_block_words_read_38 <= block_words_1_reg_1167;
        else 
            grp_sha256_compress_words_fu_526_block_words_read_38 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_sha256_compress_words_fu_526_block_words_read_39_assign_proc : process(block_words_2_reg_1172, ap_CS_fsm_state4, s_18_reg_1192, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_sha256_compress_words_fu_526_block_words_read_39 <= s_18_reg_1192;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_sha256_compress_words_fu_526_block_words_read_39 <= block_words_2_reg_1172;
        else 
            grp_sha256_compress_words_fu_526_block_words_read_39 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_sha256_compress_words_fu_526_block_words_read_40_assign_proc : process(block_words_3_reg_1177, ap_CS_fsm_state4, s_19_reg_1197, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_sha256_compress_words_fu_526_block_words_read_40 <= s_19_reg_1197;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_sha256_compress_words_fu_526_block_words_read_40 <= block_words_3_reg_1177;
        else 
            grp_sha256_compress_words_fu_526_block_words_read_40 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_sha256_compress_words_fu_526_block_words_read_41_assign_proc : process(ap_CS_fsm_state4, s_20_reg_1202, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_sha256_compress_words_fu_526_block_words_read_41 <= s_20_reg_1202;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_sha256_compress_words_fu_526_block_words_read_41 <= ap_const_lv32_80000000;
        else 
            grp_sha256_compress_words_fu_526_block_words_read_41 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_sha256_compress_words_fu_526_block_words_read_42_assign_proc : process(ap_CS_fsm_state4, s_21_reg_1207, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_sha256_compress_words_fu_526_block_words_read_42 <= s_21_reg_1207;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_sha256_compress_words_fu_526_block_words_read_42 <= ap_const_lv32_0;
        else 
            grp_sha256_compress_words_fu_526_block_words_read_42 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_sha256_compress_words_fu_526_block_words_read_43_assign_proc : process(ap_CS_fsm_state4, s_22_reg_1212, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_sha256_compress_words_fu_526_block_words_read_43 <= s_22_reg_1212;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_sha256_compress_words_fu_526_block_words_read_43 <= ap_const_lv32_0;
        else 
            grp_sha256_compress_words_fu_526_block_words_read_43 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_sha256_compress_words_fu_526_block_words_read_44_assign_proc : process(ap_CS_fsm_state4, s_23_reg_1217, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_sha256_compress_words_fu_526_block_words_read_44 <= s_23_reg_1217;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_sha256_compress_words_fu_526_block_words_read_44 <= ap_const_lv32_0;
        else 
            grp_sha256_compress_words_fu_526_block_words_read_44 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_sha256_compress_words_fu_526_block_words_read_45_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_sha256_compress_words_fu_526_block_words_read_45 <= ap_const_lv32_80000000;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_sha256_compress_words_fu_526_block_words_read_45 <= ap_const_lv32_0;
        else 
            grp_sha256_compress_words_fu_526_block_words_read_45 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_sha256_compress_words_fu_526_block_words_read_46_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_sha256_compress_words_fu_526_block_words_read_46 <= ap_const_lv32_100;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_sha256_compress_words_fu_526_block_words_read_46 <= ap_const_lv32_280;
        else 
            grp_sha256_compress_words_fu_526_block_words_read_46 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_sha256_compress_words_fu_526_state_read_assign_proc : process(midstate_read, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_sha256_compress_words_fu_526_state_read <= ap_const_lv32_6A09E667;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_sha256_compress_words_fu_526_state_read <= midstate_read;
        else 
            grp_sha256_compress_words_fu_526_state_read <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_sha256_compress_words_fu_526_state_read_30_assign_proc : process(midstate_read_15, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_sha256_compress_words_fu_526_state_read_30 <= ap_const_lv32_BB67AE85;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_sha256_compress_words_fu_526_state_read_30 <= midstate_read_15;
        else 
            grp_sha256_compress_words_fu_526_state_read_30 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_sha256_compress_words_fu_526_state_read_31_assign_proc : process(midstate_read_16, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_sha256_compress_words_fu_526_state_read_31 <= ap_const_lv32_3C6EF372;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_sha256_compress_words_fu_526_state_read_31 <= midstate_read_16;
        else 
            grp_sha256_compress_words_fu_526_state_read_31 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_sha256_compress_words_fu_526_state_read_32_assign_proc : process(midstate_read_17, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_sha256_compress_words_fu_526_state_read_32 <= ap_const_lv32_A54FF53A;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_sha256_compress_words_fu_526_state_read_32 <= midstate_read_17;
        else 
            grp_sha256_compress_words_fu_526_state_read_32 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_sha256_compress_words_fu_526_state_read_33_assign_proc : process(midstate_read_18, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_sha256_compress_words_fu_526_state_read_33 <= ap_const_lv32_510E527F;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_sha256_compress_words_fu_526_state_read_33 <= midstate_read_18;
        else 
            grp_sha256_compress_words_fu_526_state_read_33 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_sha256_compress_words_fu_526_state_read_34_assign_proc : process(midstate_read_19, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_sha256_compress_words_fu_526_state_read_34 <= ap_const_lv32_9B05688C;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_sha256_compress_words_fu_526_state_read_34 <= midstate_read_19;
        else 
            grp_sha256_compress_words_fu_526_state_read_34 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_sha256_compress_words_fu_526_state_read_35_assign_proc : process(midstate_read_20, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_sha256_compress_words_fu_526_state_read_35 <= ap_const_lv32_1F83D9AB;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_sha256_compress_words_fu_526_state_read_35 <= midstate_read_20;
        else 
            grp_sha256_compress_words_fu_526_state_read_35 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_sha256_compress_words_fu_526_state_read_36_assign_proc : process(midstate_read_21, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_sha256_compress_words_fu_526_state_read_36 <= ap_const_lv32_5BE0CD19;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_sha256_compress_words_fu_526_state_read_36 <= midstate_read_21;
        else 
            grp_sha256_compress_words_fu_526_state_read_36 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    header_tail_address0 <= header_tail_address0_local;

    header_tail_address0_local_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            header_tail_address0_local <= ap_const_lv64_13(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            header_tail_address0_local <= ap_const_lv64_11(5 - 1 downto 0);
        else 
            header_tail_address0_local <= "XXXXX";
        end if; 
    end process;

    header_tail_address1 <= header_tail_address1_local;

    header_tail_address1_local_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            header_tail_address1_local <= ap_const_lv64_12(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            header_tail_address1_local <= ap_const_lv64_10(5 - 1 downto 0);
        else 
            header_tail_address1_local <= "XXXXX";
        end if; 
    end process;

    header_tail_ce0 <= header_tail_ce0_local;

    header_tail_ce0_local_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            header_tail_ce0_local <= ap_const_logic_1;
        else 
            header_tail_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    header_tail_ce1 <= header_tail_ce1_local;

    header_tail_ce1_local_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            header_tail_ce1_local <= ap_const_logic_1;
        else 
            header_tail_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    out_r_address0 <= out_r_address0_local;

    out_r_address0_local_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18, ap_CS_fsm_state19, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            out_r_address0_local <= ap_const_lv64_1F(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            out_r_address0_local <= ap_const_lv64_1D(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            out_r_address0_local <= ap_const_lv64_1B(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            out_r_address0_local <= ap_const_lv64_19(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            out_r_address0_local <= ap_const_lv64_17(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            out_r_address0_local <= ap_const_lv64_15(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            out_r_address0_local <= ap_const_lv64_13(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            out_r_address0_local <= ap_const_lv64_11(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            out_r_address0_local <= ap_const_lv64_F(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            out_r_address0_local <= ap_const_lv64_D(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            out_r_address0_local <= ap_const_lv64_B(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            out_r_address0_local <= ap_const_lv64_9(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            out_r_address0_local <= ap_const_lv64_7(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_r_address0_local <= ap_const_lv64_5(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            out_r_address0_local <= ap_const_lv64_3(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            out_r_address0_local <= ap_const_lv64_1(5 - 1 downto 0);
        else 
            out_r_address0_local <= "XXXXX";
        end if; 
    end process;

    out_r_address1 <= out_r_address1_local;

    out_r_address1_local_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18, ap_CS_fsm_state19, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            out_r_address1_local <= ap_const_lv64_1E(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            out_r_address1_local <= ap_const_lv64_1C(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            out_r_address1_local <= ap_const_lv64_1A(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            out_r_address1_local <= ap_const_lv64_18(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            out_r_address1_local <= ap_const_lv64_16(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            out_r_address1_local <= ap_const_lv64_14(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            out_r_address1_local <= ap_const_lv64_12(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            out_r_address1_local <= ap_const_lv64_10(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            out_r_address1_local <= ap_const_lv64_E(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            out_r_address1_local <= ap_const_lv64_C(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            out_r_address1_local <= ap_const_lv64_A(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            out_r_address1_local <= ap_const_lv64_8(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            out_r_address1_local <= ap_const_lv64_6(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_r_address1_local <= ap_const_lv64_4(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            out_r_address1_local <= ap_const_lv64_2(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            out_r_address1_local <= ap_const_lv64_0(5 - 1 downto 0);
        else 
            out_r_address1_local <= "XXXXX";
        end if; 
    end process;

    out_r_ce0 <= out_r_ce0_local;

    out_r_ce0_local_assign_proc : process(ap_CS_fsm_state5, grp_sha256_compress_words_fu_526_ap_done, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18, ap_CS_fsm_state19, ap_CS_fsm_state20)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state20) or (ap_const_logic_1 = ap_CS_fsm_state19) or (ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or ((grp_sha256_compress_words_fu_526_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            out_r_ce0_local <= ap_const_logic_1;
        else 
            out_r_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    out_r_ce1 <= out_r_ce1_local;

    out_r_ce1_local_assign_proc : process(ap_CS_fsm_state5, grp_sha256_compress_words_fu_526_ap_done, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18, ap_CS_fsm_state19, ap_CS_fsm_state20)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state20) or (ap_const_logic_1 = ap_CS_fsm_state19) or (ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or ((grp_sha256_compress_words_fu_526_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            out_r_ce1_local <= ap_const_logic_1;
        else 
            out_r_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    out_r_d0 <= out_r_d0_local;

    out_r_d0_local_assign_proc : process(ap_CS_fsm_state5, trunc_ln323_reg_1227, trunc_ln321_1_reg_1237, trunc_ln323_1_reg_1247, trunc_ln321_2_reg_1257, trunc_ln323_2_reg_1267, trunc_ln321_3_reg_1277, trunc_ln323_3_reg_1287, trunc_ln321_4_reg_1297, trunc_ln323_4_reg_1307, trunc_ln321_5_reg_1317, trunc_ln323_5_reg_1327, trunc_ln321_6_reg_1337, trunc_ln323_6_reg_1347, trunc_ln321_7_reg_1357, trunc_ln323_7_reg_1367, grp_sha256_compress_words_fu_526_ap_return_0, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18, ap_CS_fsm_state19, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            out_r_d0_local <= trunc_ln323_7_reg_1367;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            out_r_d0_local <= trunc_ln321_7_reg_1357;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            out_r_d0_local <= trunc_ln323_6_reg_1347;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            out_r_d0_local <= trunc_ln321_6_reg_1337;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            out_r_d0_local <= trunc_ln323_5_reg_1327;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            out_r_d0_local <= trunc_ln321_5_reg_1317;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            out_r_d0_local <= trunc_ln323_4_reg_1307;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            out_r_d0_local <= trunc_ln321_4_reg_1297;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            out_r_d0_local <= trunc_ln323_3_reg_1287;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            out_r_d0_local <= trunc_ln321_3_reg_1277;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            out_r_d0_local <= trunc_ln323_2_reg_1267;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            out_r_d0_local <= trunc_ln321_2_reg_1257;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            out_r_d0_local <= trunc_ln323_1_reg_1247;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_r_d0_local <= trunc_ln321_1_reg_1237;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            out_r_d0_local <= trunc_ln323_reg_1227;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            out_r_d0_local <= grp_sha256_compress_words_fu_526_ap_return_0(23 downto 16);
        else 
            out_r_d0_local <= "XXXXXXXX";
        end if; 
    end process;

    out_r_d1 <= out_r_d1_local;

    out_r_d1_local_assign_proc : process(trunc_ln2_reg_1222, ap_CS_fsm_state5, trunc_ln320_1_reg_1232, trunc_ln322_1_reg_1242, trunc_ln320_2_reg_1252, trunc_ln322_2_reg_1262, trunc_ln320_3_reg_1272, trunc_ln322_3_reg_1282, trunc_ln320_4_reg_1292, trunc_ln322_4_reg_1302, trunc_ln320_5_reg_1312, trunc_ln322_5_reg_1322, trunc_ln320_6_reg_1332, trunc_ln322_6_reg_1342, trunc_ln320_7_reg_1352, trunc_ln322_7_reg_1362, grp_sha256_compress_words_fu_526_ap_return_0, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18, ap_CS_fsm_state19, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            out_r_d1_local <= trunc_ln322_7_reg_1362;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            out_r_d1_local <= trunc_ln320_7_reg_1352;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            out_r_d1_local <= trunc_ln322_6_reg_1342;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            out_r_d1_local <= trunc_ln320_6_reg_1332;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            out_r_d1_local <= trunc_ln322_5_reg_1322;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            out_r_d1_local <= trunc_ln320_5_reg_1312;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            out_r_d1_local <= trunc_ln322_4_reg_1302;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            out_r_d1_local <= trunc_ln320_4_reg_1292;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            out_r_d1_local <= trunc_ln322_3_reg_1282;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            out_r_d1_local <= trunc_ln320_3_reg_1272;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            out_r_d1_local <= trunc_ln322_2_reg_1262;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            out_r_d1_local <= trunc_ln320_2_reg_1252;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            out_r_d1_local <= trunc_ln322_1_reg_1242;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_r_d1_local <= trunc_ln320_1_reg_1232;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            out_r_d1_local <= trunc_ln2_reg_1222;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            out_r_d1_local <= grp_sha256_compress_words_fu_526_ap_return_0(31 downto 24);
        else 
            out_r_d1_local <= "XXXXXXXX";
        end if; 
    end process;

    out_r_we0 <= out_r_we0_local;

    out_r_we0_local_assign_proc : process(ap_CS_fsm_state5, grp_sha256_compress_words_fu_526_ap_done, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18, ap_CS_fsm_state19, ap_CS_fsm_state20)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state20) or (ap_const_logic_1 = ap_CS_fsm_state19) or (ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or ((grp_sha256_compress_words_fu_526_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            out_r_we0_local <= ap_const_logic_1;
        else 
            out_r_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    out_r_we1 <= out_r_we1_local;

    out_r_we1_local_assign_proc : process(ap_CS_fsm_state5, grp_sha256_compress_words_fu_526_ap_done, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18, ap_CS_fsm_state19, ap_CS_fsm_state20)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state20) or (ap_const_logic_1 = ap_CS_fsm_state19) or (ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or ((grp_sha256_compress_words_fu_526_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            out_r_we1_local <= ap_const_logic_1;
        else 
            out_r_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln323_1_fu_854_p1 <= grp_sha256_compress_words_fu_526_ap_return_1(8 - 1 downto 0);
    trunc_ln323_2_fu_888_p1 <= grp_sha256_compress_words_fu_526_ap_return_2(8 - 1 downto 0);
    trunc_ln323_3_fu_922_p1 <= grp_sha256_compress_words_fu_526_ap_return_3(8 - 1 downto 0);
    trunc_ln323_4_fu_956_p1 <= grp_sha256_compress_words_fu_526_ap_return_4(8 - 1 downto 0);
    trunc_ln323_5_fu_990_p1 <= grp_sha256_compress_words_fu_526_ap_return_5(8 - 1 downto 0);
    trunc_ln323_6_fu_1024_p1 <= grp_sha256_compress_words_fu_526_ap_return_6(8 - 1 downto 0);
    trunc_ln323_7_fu_1058_p1 <= grp_sha256_compress_words_fu_526_ap_return_7(8 - 1 downto 0);
    trunc_ln323_fu_820_p1 <= grp_sha256_compress_words_fu_526_ap_return_0(8 - 1 downto 0);
end behav;
